// AUTO-GENERATED by gen_dashboard_data.py - do not edit
/* eslint-disable */
export const TYPE_DIST: any[] = [{"type": "Founder / Operator", "count": 146}, {"type": "VC", "count": 136}, {"type": "Hedge Fund", "count": 37}, {"type": "Public Markets", "count": 36}, {"type": "Academic / Author", "count": 36}, {"type": "Other", "count": 32}, {"type": "PE / Buyout", "count": 27}, {"type": "Public-Co CEO", "count": 18}];
