// AUTO-GENERATED by gen_dashboard_data.py — do not edit
/* eslint-disable */
export const KINDNESS: any[] = [
 {
  "slug": "beshore-cultivating-a-disaster-resistant-compound-interest-machine",
  "guest": "Brent Beshore",
  "date": "2016-11-08",
  "title": "Cultivating a Disaster Resistant, Compound Interest Machine",
  "k": "Wow. Kindest thing. My entrepreneurial journey was rough early on, and I hit the bottom. Craig Brace, an older, wiser employee, saw me breaking and spent a month nurturing me back to health mentally and emotionally. He was a rock. I think we all need people we can cry in front of and be our worst selves around, and hope they love us regardless."
 },
 {
  "slug": "brown-the-reformation",
  "guest": "Josh Brown",
  "date": "2016-12-06",
  "title": "The Reformation",
  "k": "People forgave me early work when I wasn't knowledgeable; gave me time to grow. When I stumbled on European macro in 2011, readers stuck with me. That grace helped build everything that followed."
 },
 {
  "slug": "cole-small-bets-huge-payoffs",
  "guest": "Chris Cole",
  "date": "2016-11-29",
  "title": "Small Bets, Huge Payoffs",
  "k": "A partner sacrificed significant money to let my business continue growing. Out of love, not necessity. That's the kindest thing."
 },
 {
  "slug": "egan-designing-better-decisions",
  "guest": "Dan Egan",
  "date": "2017-01-03",
  "title": "Designing Better Decisions",
  "k": "My wife supported my move to NYC for career, then my giant pay cut to join Betterment as a startup. She's a diplomat who could move freely, but she chose my dreams first. We have the best arguments because we disagree well; I owe her repayment by supporting her dreams equally. Also, in 6th/7th grade, my math teacher gave me rides home. I lied about homework once, saying I forgot it, but he saw me do it in class. He said: 'I've done good things for you, and you've disappointed me by lying.' That moment—not shaming, just a line in the sand about honesty—stuck with me forever."
 },
 {
  "slug": "gramm-activist-investing",
  "guest": "Jeff Gramm",
  "date": "2016-09-11",
  "title": "Activist Investing",
  "k": "Arthur Levitt got me into Columbia Business School. I got in because of him. The dean of admissions told me after my first week of school I wouldn't have been admitted without Arthur. It motivated me rather than making me resent them. Without him, I wouldn't have gotten in—I was rejected by NYU."
 },
 {
  "slug": "housel-walking-and-thinking",
  "guest": "Morgan Housel",
  "date": "2016-10-04",
  "title": "Walking and Thinking",
  "k": "Jason Zweig took hours to have lunch with me as a stranger who emailed him. Most busy people say no; he said yes. That generosity shaped my entire career trajectory."
 },
 {
  "slug": "koppelman-chasing-curiosity",
  "guest": "Brian Koppelman",
  "date": "2017-01-24",
  "title": "Chasing Curiosity",
  "k": "The kindest thing was Dave saying, 'Yeah, I'll write a script with you.' He was already writing and had written scripts on his own. He could have just shown me the way, but instead he said, 'Let's do this together.' That professional partnership has been going strong for 20 years. There have been many other kindnesses—from Amy, my father, and my Mom who is no longer here—but professionally it was Dave believing in me and saying we could do this thing together."
 },
 {
  "slug": "maddox-the-ace-of-spades",
  "guest": "Eric Maddox",
  "date": "2016-12-13",
  "title": "The Ace of Spades",
  "k": "My birth mother had courage to carry me through ridicule rather than abort. Gave me adoption, family, life. Day one gratitude."
 },
 {
  "slug": "parrish-mastering-mental-models",
  "guest": "Shane Parrish",
  "date": "2016-12-27",
  "title": "Mastering Mental Models",
  "k": "The kindest thing people do is give me their time. Time is the one thing we really can't create more of. You can easily make more money, but you can't make more time. I'm surrounded by incredibly kind people and incredibly generous people. It's peoples' time and thoughtfulness that makes a big difference."
 },
 {
  "slug": "ptak-the-prospects-for-active-management",
  "guest": "Jeff Ptak",
  "date": "2016-12-20",
  "title": "The Prospects for Active Management",
  "k": "Professionally, my biggest kindness was at Arthur Andersen's Professional Standards Group in the early 2000s. These extremely accomplished partners took a chance on me—a young, unpolished analyst—and let me work at their feet for six years. John Stewart, Amy Ripepi, Rick Peterson, and Benjamin Neuhausen tolerated me without having to. Personally, I try to show my four children daily that not everyone lives as safely and comfortably as we do, building empathy in them for different circumstances."
 },
 {
  "slug": "rowley-vanguards-gerry-oreilly-and-jim-rowley",
  "guest": "Gerry O'Reilly & Jim Rowley",
  "date": "2016-10-18",
  "title": "Vanguard's Gerry O'Reilly and Jim Rowley",
  "k": "Impossible to pick one mentor or one act. Gerry mentioned coaches instilling work ethic, Gus's early belief in him, Mike Bucoy teaching market structure. Jim spoke of people helping him reach dream jobs. Both said they wouldn't be where they are without many mentors and colleagues."
 },
 {
  "slug": "shapiro-better-for-you-better-for-the-world",
  "guest": "Craig Shapiro",
  "date": "2016-11-14",
  "title": "Better for You, Better for the World",
  "k": "Yeah, I think outside of the just very tangible way of trusting me with their capital, I think supporting us through challenging times, right? So one of our investors told me early on, actually prior to him investing, said, \"Craig, I'm going to make an investment in you with one condition.\" And I said, \"Okay, what's that?\" He said, \"Don't shine the turd.\" And I said, \"What does that even mean?\" An"
 },
 {
  "slug": "shapiro-watching-a-venture-fund-at-work",
  "guest": "Lauren Loktev, Kanyi Maqubela & Craig Shapiro",
  "date": "2017-01-10",
  "title": "Watching a Venture Fund at Work",
  "k": "Lauren: My parents made tough choices to change the education system in Kentucky because I wasn't challenged in school. They faced pushback but showed resilience, paving the way for other kids. Kanyi: My parents gave me an education and forced me to study chemistry, math, and writing when all I wanted was to play. That's how serious they were, and it's why I value education today."
 },
 {
  "slug": "stein-the-state-of-automated-investing",
  "guest": "Jon Stein",
  "date": "2016-11-01",
  "title": "The State of Automated Investing",
  "k": "So many people have been so generous to us along the way, and our partners with various firms have been so giving. I had so many great mentors during my consulting days, and I'd be leaving someone out if I singled one person out."
 },
 {
  "slug": "zweig-the-power-of-serendipity",
  "guest": "Jason Zweig",
  "date": "2016-09-27",
  "title": "The Power of Serendipity",
  "k": "An editor at HarperCollins asked me to update The Intelligent Investor. I asked why they chose me. He said Nina Munk recommended me—we'd reconnected at a conference a few months earlier. I'd 'plowed across the room' to say hello. If I hadn't made that effort, I wouldn't have been top of mind. Serendipity depends on the effort you make."
 }
];
