// AUTO-GENERATED by gen_dashboard_data.py — do not edit
/* eslint-disable */
export const WISDOM: any[] = [
 {
  "slug": "adams-an-internal-locus-of-control",
  "guest": "Kiley Adams",
  "date": "2016-10-28",
  "title": "An Internal Locus of Control",
  "t": "Perseverance and attitude—holding every action accountable to integrity—compound over years into mastery when consistency is non-negotiable.",
  "cat": "life"
 },
 {
  "slug": "adams-an-internal-locus-of-control",
  "guest": "Kiley Adams",
  "date": "2016-10-28",
  "title": "An Internal Locus of Control",
  "t": "Internal locus of control means never blaming circumstances; always reframe as 'What can I do differently?' not 'Why is this unfair?'",
  "cat": "life"
 },
 {
  "slug": "adams-an-internal-locus-of-control",
  "guest": "Kiley Adams",
  "date": "2016-10-28",
  "title": "An Internal Locus of Control",
  "t": "Unbroken forward momentum without retreat becomes self-reinforcing; learning to move relentlessly turns pain into motion.",
  "cat": "leadership"
 },
 {
  "slug": "adams-an-internal-locus-of-control",
  "guest": "Kiley Adams",
  "date": "2016-10-28",
  "title": "An Internal Locus of Control",
  "t": "Mastery requires obsession with details; fights are won on foot placement and breathing, not broad strategy concepts.",
  "cat": "craft"
 },
 {
  "slug": "adams-an-internal-locus-of-control",
  "guest": "Kiley Adams",
  "date": "2016-10-28",
  "title": "An Internal Locus of Control",
  "t": "Community and support systems are non-negotiable for success across athletics, research, and ambition; isolation breaks momentum.",
  "cat": "life"
 },
 {
  "slug": "adams-an-internal-locus-of-control",
  "guest": "Kiley Adams",
  "date": "2016-10-28",
  "title": "An Internal Locus of Control",
  "t": "Relentlessness is cultivable through parents and institutions; individuals who adopt it early gain decades of compounding advantage.",
  "cat": "building"
 },
 {
  "slug": "adams-an-internal-locus-of-control",
  "guest": "Kiley Adams",
  "date": "2016-10-28",
  "title": "An Internal Locus of Control",
  "t": "Living fully means finishing each day exhausted; rest without accomplishment feels like retreat.",
  "cat": "life"
 },
 {
  "slug": "beshore-cultivating-a-disaster-resistant-compound-interest-machine",
  "guest": "Brent Beshore",
  "date": "2016-11-08",
  "title": "Cultivating a Disaster Resistant, Compound Interest Machine",
  "t": "Buy boring businesses and make them less boring through operational improvements and smart capital allocation.",
  "cat": "investing"
 },
 {
  "slug": "beshore-cultivating-a-disaster-resistant-compound-interest-machine",
  "guest": "Brent Beshore",
  "date": "2016-11-08",
  "title": "Cultivating a Disaster Resistant, Compound Interest Machine",
  "t": "Play in inefficient markets with high opportunity costs where few competitors operate.",
  "cat": "investing"
 },
 {
  "slug": "beshore-cultivating-a-disaster-resistant-compound-interest-machine",
  "guest": "Brent Beshore",
  "date": "2016-11-08",
  "title": "Cultivating a Disaster Resistant, Compound Interest Machine",
  "t": "Creating a stable company from scratch is like eating glass - daily, brutal, persistent work.",
  "cat": "building"
 },
 {
  "slug": "beshore-cultivating-a-disaster-resistant-compound-interest-machine",
  "guest": "Brent Beshore",
  "date": "2016-11-08",
  "title": "Cultivating a Disaster Resistant, Compound Interest Machine",
  "t": "Business culture of everyone killing it is false - success requires real relationships where you can cry and be your worst self.",
  "cat": "leadership"
 },
 {
  "slug": "beshore-cultivating-a-disaster-resistant-compound-interest-machine",
  "guest": "Brent Beshore",
  "date": "2016-11-08",
  "title": "Cultivating a Disaster Resistant, Compound Interest Machine",
  "t": "Compounding knowledge through deep thinking and learning is the single biggest determining factor of long-term success.",
  "cat": "building"
 },
 {
  "slug": "beshore-cultivating-a-disaster-resistant-compound-interest-machine",
  "guest": "Brent Beshore",
  "date": "2016-11-08",
  "title": "Cultivating a Disaster Resistant, Compound Interest Machine",
  "t": "In a low-interest-rate environment, all asset values inflate - position for the washout when you can deploy cash.",
  "cat": "markets"
 },
 {
  "slug": "beshore-cultivating-a-disaster-resistant-compound-interest-machine",
  "guest": "Brent Beshore",
  "date": "2016-11-08",
  "title": "Cultivating a Disaster Resistant, Compound Interest Machine",
  "t": "Conservative capital deployment without outside investors preserves optionality and allows retaining all exceptional returns.",
  "cat": "investing"
 },
 {
  "slug": "beshore-cultivating-a-disaster-resistant-compound-interest-machine",
  "guest": "Brent Beshore",
  "date": "2016-11-08",
  "title": "Cultivating a Disaster Resistant, Compound Interest Machine",
  "t": "The lower middle market ($1-10M owner earnings) has massive inefficiency and few competitors compared to larger M&A.",
  "cat": "investing"
 },
 {
  "slug": "brown-the-reformation",
  "guest": "Josh Brown",
  "date": "2016-12-06",
  "title": "The Reformation",
  "t": "Shift from stock-picking to holistic planning. Role of advisor evolves from investment manager to behavioral guard rail and relationship keeper.",
  "cat": "building"
 },
 {
  "slug": "brown-the-reformation",
  "guest": "Josh Brown",
  "date": "2016-12-06",
  "title": "The Reformation",
  "t": "Align advisor incentives with clients: use same portfolios you recommend. Advisor bleeding out -2% annually is better than hedge fund up 15% and down 40% the next.",
  "cat": "investing"
 },
 {
  "slug": "brown-the-reformation",
  "guest": "Josh Brown",
  "date": "2016-12-06",
  "title": "The Reformation",
  "t": "Process beats personality except for Jedi investors. 99% need systematized rules; handful like Icahn/Tepper succeed on instinct. Don't glorify the 1% in marketing.",
  "cat": "leadership"
 },
 {
  "slug": "brown-the-reformation",
  "guest": "Josh Brown",
  "date": "2016-12-06",
  "title": "The Reformation",
  "t": "Screen for client fit, not just AUM. Taking bad-fit clients impedes growth and good service. Saying no saves time for people you can help.",
  "cat": "building"
 },
 {
  "slug": "brown-the-reformation",
  "guest": "Josh Brown",
  "date": "2016-12-06",
  "title": "The Reformation",
  "t": "Content isn't work when it's your passion. Reading and writing about markets 80+ hours weekly feels like play, not labor. Find the asymmetry.",
  "cat": "life"
 },
 {
  "slug": "brown-the-reformation",
  "guest": "Josh Brown",
  "date": "2016-12-06",
  "title": "The Reformation",
  "t": "Twitter success = right time + consistent voice + refusal to fight. Early 2009 meant 20 people talking investing. Avoided drama others couldn't.",
  "cat": "craft"
 },
 {
  "slug": "brown-the-reformation",
  "guest": "Josh Brown",
  "date": "2016-12-06",
  "title": "The Reformation",
  "t": "Kids learn investing via individual stocks (Disney, Under Armour) before 401ks. Ownership mindset earlier; natural gateway to business models and fundamentals.",
  "cat": "building"
 },
 {
  "slug": "brown-the-reformation",
  "guest": "Josh Brown",
  "date": "2016-12-06",
  "title": "The Reformation",
  "t": "Standardize process, customize advice. Technology is like TurboTax—doesn't replace accountants, multiplies them. Scales advising, frees capacity for better counsel.",
  "cat": "craft"
 },
 {
  "slug": "cole-small-bets-huge-payoffs",
  "guest": "Chris Cole",
  "date": "2016-11-29",
  "title": "Small Bets, Huge Payoffs",
  "t": "Most portfolios are 97% short convexity; crises hit hard. Pair convexity with traditional beta to survive drawdowns with conviction.",
  "cat": "investing"
 },
 {
  "slug": "cole-small-bets-huge-payoffs",
  "guest": "Chris Cole",
  "date": "2016-11-29",
  "title": "Small Bets, Huge Payoffs",
  "t": "Time is linear but happiness is non-linear. Make small investments in meditation, exercise, reading—compounding gains over years.",
  "cat": "life"
 },
 {
  "slug": "cole-small-bets-huge-payoffs",
  "guest": "Chris Cole",
  "date": "2016-11-29",
  "title": "Small Bets, Huge Payoffs",
  "t": "Long vol is not insurance (tail risk); it's active management. Sell expensive volatility, buy cheap convexity to minimize carry.",
  "cat": "investing"
 },
 {
  "slug": "cole-small-bets-huge-payoffs",
  "guest": "Chris Cole",
  "date": "2016-11-29",
  "title": "Small Bets, Huge Payoffs",
  "t": "Value investing works most of the time, crashes hard during crises. Build long volatility around it to protect without bleeding 50% annually.",
  "cat": "investing"
 },
 {
  "slug": "cole-small-bets-huge-payoffs",
  "guest": "Chris Cole",
  "date": "2016-11-29",
  "title": "Small Bets, Huge Payoffs",
  "t": "Suppressing small volatility creates larger future volatility: avalanches, forest fires, marriages. Central banks are removing intermediate risks to create systemic ones.",
  "cat": "markets"
 },
 {
  "slug": "cole-small-bets-huge-payoffs",
  "guest": "Chris Cole",
  "date": "2016-11-29",
  "title": "Small Bets, Huge Payoffs",
  "t": "A legendary macro investor is wrong 8-9 times out of 10. The 1-2 times he's right pay for everything. Process beats prediction.",
  "cat": "investing"
 },
 {
  "slug": "cole-small-bets-huge-payoffs",
  "guest": "Chris Cole",
  "date": "2016-11-29",
  "title": "Small Bets, Huge Payoffs",
  "t": "Convexity in daily life: approaching someone you're attracted to has small linear loss, massive exponential gain. Take small asymmetric bets.",
  "cat": "life"
 },
 {
  "slug": "cole-small-bets-huge-payoffs",
  "guest": "Chris Cole",
  "date": "2016-11-29",
  "title": "Small Bets, Huge Payoffs",
  "t": "Dennis Rodman got 6 standard deviations away from mean in rebounding. Anti-correlated assets do for portfolios what Rodman did for teams: amplify non-linear gains.",
  "cat": "investing"
 },
 {
  "slug": "egan-designing-better-decisions",
  "guest": "Dan Egan",
  "date": "2017-01-03",
  "title": "Designing Better Decisions",
  "t": "Good sci-fi isolates one assumption and shows cascading consequences—change attractiveness perception or reproducibility defaults, and entire societies reorganize.",
  "cat": "life"
 },
 {
  "slug": "egan-designing-better-decisions",
  "guest": "Dan Egan",
  "date": "2017-01-03",
  "title": "Designing Better Decisions",
  "t": "Defaults structure behavior without prohibition. By making the default non-obvious (e.g., attractiveness off, reproducibility opt-in), you shift outcomes massively.",
  "cat": "building"
 },
 {
  "slug": "egan-designing-better-decisions",
  "guest": "Dan Egan",
  "date": "2017-01-03",
  "title": "Designing Better Decisions",
  "t": "Tax Impact Preview reduced portfolio rebalancing 70% by surfacing small certain cost ($1) vs uncertain feared loss (market drop)—salience > magnitude.",
  "cat": "investing"
 },
 {
  "slug": "egan-designing-better-decisions",
  "guest": "Dan Egan",
  "date": "2017-01-03",
  "title": "Designing Better Decisions",
  "t": "Behavioral nudges work at moment of decision during stress (login-time messaging), not pre-emptive (blast email). Surgical > broad; self-selected > broadcast.",
  "cat": "investing"
 },
 {
  "slug": "egan-designing-better-decisions",
  "guest": "Dan Egan",
  "date": "2017-01-03",
  "title": "Designing Better Decisions",
  "t": "Judges' parole decisions swing from ~65% approval (just-eaten) to ~0% (hungry after 4.5 hours). Humans in high-stakes execution are hostage to biological state.",
  "cat": "leadership"
 },
 {
  "slug": "egan-designing-better-decisions",
  "guest": "Dan Egan",
  "date": "2017-01-03",
  "title": "Designing Better Decisions",
  "t": "Automation creates strategic blindness. Dashboards are maps, not territory. When systems run on autopilot, you lose fluency with underlying reality and miss changes.",
  "cat": "building"
 },
 {
  "slug": "egan-designing-better-decisions",
  "guest": "Dan Egan",
  "date": "2017-01-03",
  "title": "Designing Better Decisions",
  "t": "The future of automation depends on society finding dignity, purpose, community beyond money as repeatable labor disappears. Otherwise: inequality + unhappiness.",
  "cat": "life"
 },
 {
  "slug": "egan-designing-better-decisions",
  "guest": "Dan Egan",
  "date": "2017-01-03",
  "title": "Designing Better Decisions",
  "t": "Personalization isn't always good. Constraints (Henry Ford's black cars) reduce harmful speculation. Fully flexible choice often leads to worse outcomes than limited good options.",
  "cat": "investing"
 },
 {
  "slug": "gramm-activist-investing",
  "guest": "Jeff Gramm",
  "date": "2016-09-11",
  "title": "Activist Investing",
  "t": "Market information asymmetries persist; competitors who do hard work to find public disclosures outperform those who don't.",
  "cat": "investing"
 },
 {
  "slug": "gramm-activist-investing",
  "guest": "Jeff Gramm",
  "date": "2016-09-11",
  "title": "Activist Investing",
  "t": "Institutional investors now control voting power, making activism about persuasion rather than hostile takeovers or public shaming.",
  "cat": "markets"
 },
 {
  "slug": "gramm-activist-investing",
  "guest": "Jeff Gramm",
  "date": "2016-09-11",
  "title": "Activist Investing",
  "t": "Buyback quality varies drastically: well-timed repurchases create tremendous value; autopilot programs directly destroy it.",
  "cat": "investing"
 },
 {
  "slug": "gramm-activist-investing",
  "guest": "Jeff Gramm",
  "date": "2016-09-11",
  "title": "Activist Investing",
  "t": "Great capital allocators are rare; screen to avoid terrible allocation rather than expecting to find exceptional ones.",
  "cat": "investing"
 },
 {
  "slug": "gramm-activist-investing",
  "guest": "Jeff Gramm",
  "date": "2016-09-11",
  "title": "Activist Investing",
  "t": "Value investors must be journalists: compelled to gather their own facts and do original analysis competitors won't.",
  "cat": "craft"
 },
 {
  "slug": "gramm-activist-investing",
  "guest": "Jeff Gramm",
  "date": "2016-09-11",
  "title": "Activist Investing",
  "t": "Your investor base quality determines strategy freedom; choose long-term, illiquid-comfortable capital over performance-chasing institutions.",
  "cat": "building"
 },
 {
  "slug": "gramm-activist-investing",
  "guest": "Jeff Gramm",
  "date": "2016-09-11",
  "title": "Activist Investing",
  "t": "Boards fundamentally misunderstand buybacks: most don't grasp intrinsic value or when execution creates vs destroys shareholder value.",
  "cat": "leadership"
 },
 {
  "slug": "gramm-activist-investing",
  "guest": "Jeff Gramm",
  "date": "2016-09-11",
  "title": "Activist Investing",
  "t": "Microcap activism exploits information asymmetry and liquidity constraints of concentrated shareholders willing to exit at any price.",
  "cat": "investing"
 },
 {
  "slug": "housel-walking-and-thinking",
  "guest": "Morgan Housel",
  "date": "2016-10-04",
  "title": "Walking and Thinking",
  "t": "Venture capital requires conviction about founders, not spreadsheet precision. Range of outcomes is enormous—100x or 0x, not 20% precision.",
  "cat": "investing"
 },
 {
  "slug": "housel-walking-and-thinking",
  "guest": "Morgan Housel",
  "date": "2016-10-04",
  "title": "Walking and Thinking",
  "t": "Innovation and invention are different. Gap between discovering something transformational and world adoption can be 10-20 years.",
  "cat": "markets"
 },
 {
  "slug": "housel-walking-and-thinking",
  "guest": "Morgan Housel",
  "date": "2016-10-04",
  "title": "Walking and Thinking",
  "t": "Saving rate matters far more than investment strategy. Wealth comes from spending less than you make, not beating the market.",
  "cat": "investing"
 },
 {
  "slug": "housel-walking-and-thinking",
  "guest": "Morgan Housel",
  "date": "2016-10-04",
  "title": "Walking and Thinking",
  "t": "Best ideas come during walks, showers, or casual moments—not sitting at desk trying to force creativity. Subconscious needs raw inputs.",
  "cat": "craft"
 },
 {
  "slug": "housel-walking-and-thinking",
  "guest": "Morgan Housel",
  "date": "2016-10-04",
  "title": "Walking and Thinking",
  "t": "Flattest organizations (Zappos, Valve) drive creativity through obsessive hiring, not process. Requires trusting people with full freedom.",
  "cat": "building"
 },
 {
  "slug": "housel-walking-and-thinking",
  "guest": "Morgan Housel",
  "date": "2016-10-04",
  "title": "Walking and Thinking",
  "t": "Empathy—understanding people who disagree with you—is the most undervalued professional skill and predictor of long-term success.",
  "cat": "leadership"
 },
 {
  "slug": "housel-walking-and-thinking",
  "guest": "Morgan Housel",
  "date": "2016-10-04",
  "title": "Walking and Thinking",
  "t": "For writers and readers, work and pleasure blur. Reading is part of the job; you need trusted curators to filter infinite content.",
  "cat": "craft"
 },
 {
  "slug": "housel-walking-and-thinking",
  "guest": "Morgan Housel",
  "date": "2016-10-04",
  "title": "Walking and Thinking",
  "t": "Reading old newspapers reveals bias check: events that seemed obvious in hindsight weren't obvious at the time.",
  "cat": "life"
 },
 {
  "slug": "housel-walking-and-thinking",
  "guest": "Morgan Housel",
  "date": "2016-10-04",
  "title": "Walking and Thinking",
  "t": "Hybrid advisors win: online automation for 99% + human touchpoint for complex decisions. Pure online or pure human both lose.",
  "cat": "investing"
 },
 {
  "slug": "housel-walking-and-thinking",
  "guest": "Morgan Housel",
  "date": "2016-10-04",
  "title": "Walking and Thinking",
  "t": "Great investors become more humble over time. At 22, you think you've got it figured out. Decades later you know you don't.",
  "cat": "life"
 },
 {
  "slug": "koppelman-chasing-curiosity",
  "guest": "Brian Koppelman",
  "date": "2017-01-24",
  "title": "Chasing Curiosity",
  "t": "Humans are happiest when accessing their most creative self; creativity matters in every job and mission.",
  "cat": "life"
 },
 {
  "slug": "koppelman-chasing-curiosity",
  "guest": "Brian Koppelman",
  "date": "2017-01-24",
  "title": "Chasing Curiosity",
  "t": "Great creative work has strangeness to it—something that feels like it should exist but never has before.",
  "cat": "craft"
 },
 {
  "slug": "koppelman-chasing-curiosity",
  "guest": "Brian Koppelman",
  "date": "2017-01-24",
  "title": "Chasing Curiosity",
  "t": "Curiosity and fascination are north stars; follow those to create work with original spark, not formulas.",
  "cat": "building"
 },
 {
  "slug": "koppelman-chasing-curiosity",
  "guest": "Brian Koppelman",
  "date": "2017-01-24",
  "title": "Chasing Curiosity",
  "t": "Morning pages eliminate perfectionism by allowing uncensored output without judgment; three pages daily, never read for five years.",
  "cat": "craft"
 },
 {
  "slug": "koppelman-chasing-curiosity",
  "guest": "Brian Koppelman",
  "date": "2017-01-24",
  "title": "Chasing Curiosity",
  "t": "Flow state—where conscious thought disappears—comes from preparation, routine, and authentic interest in the subject.",
  "cat": "life"
 },
 {
  "slug": "koppelman-chasing-curiosity",
  "guest": "Brian Koppelman",
  "date": "2017-01-24",
  "title": "Chasing Curiosity",
  "t": "Money creates transactional relationships; genuine relationships require awareness of what's transactional versus authentic.",
  "cat": "life"
 },
 {
  "slug": "koppelman-chasing-curiosity",
  "guest": "Brian Koppelman",
  "date": "2017-01-24",
  "title": "Chasing Curiosity",
  "t": "Billionaires fascinate us because they represent mastery and power; but obsessing reveals truths about human ambition.",
  "cat": "markets"
 },
 {
  "slug": "koppelman-chasing-curiosity",
  "guest": "Brian Koppelman",
  "date": "2017-01-24",
  "title": "Chasing Curiosity",
  "t": "Compounding works in every domain: small improvements over time create enormous change when you love the process.",
  "cat": "investing"
 },
 {
  "slug": "koppelman-chasing-curiosity",
  "guest": "Brian Koppelman",
  "date": "2017-01-24",
  "title": "Chasing Curiosity",
  "t": "Mastery has no shortcuts; study your craft deeply by consuming it: read screenplays, watch films, read books repeatedly.",
  "cat": "building"
 },
 {
  "slug": "koppelman-chasing-curiosity",
  "guest": "Brian Koppelman",
  "date": "2017-01-24",
  "title": "Chasing Curiosity",
  "t": "Meditation and running create conditions for creativity by eliminating anxiety and accessing deeper thought and connection.",
  "cat": "life"
 },
 {
  "slug": "maddox-the-ace-of-spades",
  "guest": "Eric Maddox",
  "date": "2016-12-13",
  "title": "The Ace of Spades",
  "t": "Listening rate is 25% baseline. Remove distractors → 50%. Add empathy (know their distractors) → 70-90%. At 80%+, you have overwhelming influence power.",
  "cat": "craft"
 },
 {
  "slug": "maddox-the-ace-of-spades",
  "guest": "Eric Maddox",
  "date": "2016-12-13",
  "title": "The Ace of Spades",
  "t": "Empathy isn't feeling; it's knowing their distractors. Before a conversation, map theirs as you'd map your own: fatigue, bias, objective, listening speed gaps.",
  "cat": "life"
 },
 {
  "slug": "maddox-the-ace-of-spades",
  "guest": "Eric Maddox",
  "date": "2016-12-13",
  "title": "The Ace of Spades",
  "t": "You listen at 5x mouth speed. Brain zigzags filling 80% with your stuff. Tether yourself to the speaker via distraction removal. Empathy puts you inside their world.",
  "cat": "craft"
 },
 {
  "slug": "maddox-the-ace-of-spades",
  "guest": "Eric Maddox",
  "date": "2016-12-13",
  "title": "The Ace of Spades",
  "t": "Old method broke 4% of prisoners. New method (rapport + mapping network) broke 65%. Dominance paralyzes; trust and aligned goals unlock everything.",
  "cat": "leadership"
 },
 {
  "slug": "maddox-the-ace-of-spades",
  "guest": "Eric Maddox",
  "date": "2016-12-13",
  "title": "The Ace of Spades",
  "t": "Entrench the wrong system by punishing courage to deviate. Delta commander took heat for trusting unknown interrogator with crazy hunch. Leadership means bearing the backlash.",
  "cat": "leadership"
 },
 {
  "slug": "maddox-the-ace-of-spades",
  "guest": "Eric Maddox",
  "date": "2016-12-13",
  "title": "The Ace of Spades",
  "t": "Continuity questioning: jump around but maintain narrative thread. Prisoners omit what threatens them. Staying linear lets them skip what you need.",
  "cat": "craft"
 },
 {
  "slug": "maddox-the-ace-of-spades",
  "guest": "Eric Maddox",
  "date": "2016-12-13",
  "title": "The Ace of Spades",
  "t": "Good listening makes you attractive. People are starved for genuine attention. Charisma = power + empathy. A great listener draws people in.",
  "cat": "life"
 },
 {
  "slug": "maddox-the-ace-of-spades",
  "guest": "Eric Maddox",
  "date": "2016-12-13",
  "title": "The Ace of Spades",
  "t": "Interrogation is just conversation: gather info or influence (usually both). Remove your agenda distractions first, then know theirs. Then you're ready to listen.",
  "cat": "craft"
 },
 {
  "slug": "mauboussin-active-asset-management",
  "guest": "Michael Mauboussin",
  "date": "2016-09-20",
  "title": "Active Asset Management",
  "t": "Stock prices reflect market expectations; outperformance comes from beating consensus forecasts, not just performing well in absolute terms.",
  "cat": "investing"
 },
 {
  "slug": "mauboussin-active-asset-management",
  "guest": "Michael Mauboussin",
  "date": "2016-09-20",
  "title": "Active Asset Management",
  "t": "Great clients are partners who write checks when you ask and cash them when you hand them over, allowing opportunistic capital deployment.",
  "cat": "building"
 },
 {
  "slug": "mauboussin-active-asset-management",
  "guest": "Michael Mauboussin",
  "date": "2016-09-20",
  "title": "Active Asset Management",
  "t": "Analyst-run funds outperform PM-run funds in same families because pure stock picking without sector tilts creates measurable edge.",
  "cat": "craft"
 },
 {
  "slug": "mauboussin-active-asset-management",
  "guest": "Michael Mauboussin",
  "date": "2016-09-20",
  "title": "Active Asset Management",
  "t": "Buyback quality varies: high-conviction purchases at cheap valuations create value, while methodical quarterly programs may destroy it.",
  "cat": "investing"
 },
 {
  "slug": "mauboussin-active-asset-management",
  "guest": "Michael Mauboussin",
  "date": "2016-09-20",
  "title": "Active Asset Management",
  "t": "Skill in investing combines analytical edge, behavioral discipline, and organizational structure—no single factor dominates alone.",
  "cat": "craft"
 },
 {
  "slug": "mauboussin-active-asset-management",
  "guest": "Michael Mauboussin",
  "date": "2016-09-20",
  "title": "Active Asset Management",
  "t": "Information edge is harder than behavioral edge; quality of data matters more than sophisticated analytics for machine learning models.",
  "cat": "investing"
 },
 {
  "slug": "mauboussin-active-asset-management",
  "guest": "Michael Mauboussin",
  "date": "2016-09-20",
  "title": "Active Asset Management",
  "t": "Sleep, exercise, and dedicated reading time are foundational—productivity suffers more from sleep deprivation than any other factor.",
  "cat": "life"
 },
 {
  "slug": "mauboussin-active-asset-management",
  "guest": "Michael Mauboussin",
  "date": "2016-09-20",
  "title": "Active Asset Management",
  "t": "Float-generating businesses offer compounding advantage: guaranteed capital source to deploy without asking clients, as Berkshire Hathaway exemplifies.",
  "cat": "investing"
 },
 {
  "slug": "parrish-mastering-mental-models",
  "guest": "Shane Parrish",
  "date": "2016-12-27",
  "title": "Mastering Mental Models",
  "t": "Re-reading great books reveals new meaning as you evolve—the same words speak differently when you're a different person. Re-reads yield more than fresh reads.",
  "cat": "life"
 },
 {
  "slug": "parrish-mastering-mental-models",
  "guest": "Shane Parrish",
  "date": "2016-12-27",
  "title": "Mastering Mental Models",
  "t": "Growth mindset—believing effort creates improvement—compounds when practiced in zones just beyond competence. Requires coaching, safe struggle, deliberate discomfort.",
  "cat": "building"
 },
 {
  "slug": "parrish-mastering-mental-models",
  "guest": "Shane Parrish",
  "date": "2016-12-27",
  "title": "Mastering Mental Models",
  "t": "Automation creates blindness. Dashboards are maps, not territory. When systems automate, you lose fluency with underlying reality and miss when it changes.",
  "cat": "building"
 },
 {
  "slug": "parrish-mastering-mental-models",
  "guest": "Shane Parrish",
  "date": "2016-12-27",
  "title": "Mastering Mental Models",
  "t": "Culture is the hardest competitive moat—uncopied by rivals; determined by stories told inside organizations and the mindsets they reinforce (growth vs fixed).",
  "cat": "leadership"
 },
 {
  "slug": "parrish-mastering-mental-models",
  "guest": "Shane Parrish",
  "date": "2016-12-27",
  "title": "Mastering Mental Models",
  "t": "Multidisciplinary thinking prevents domain dependence. Collecting mental models across fields lets you recognize patterns others miss and combine them in novel ways.",
  "cat": "investing"
 },
 {
  "slug": "parrish-mastering-mental-models",
  "guest": "Shane Parrish",
  "date": "2016-12-27",
  "title": "Mastering Mental Models",
  "t": "Biology enables, culture forbids—most behavioral limits are social norms, not natural. Deviation from cultural norms, done correctly, moves you to distribution tails.",
  "cat": "life"
 },
 {
  "slug": "parrish-mastering-mental-models",
  "guest": "Shane Parrish",
  "date": "2016-12-27",
  "title": "Mastering Mental Models",
  "t": "Personal competitive advantage isn't being best at one thing—it's being good at several non-overlapping skills that combine non-linearly into rare capability.",
  "cat": "building"
 },
 {
  "slug": "parrish-mastering-mental-models",
  "guest": "Shane Parrish",
  "date": "2016-12-27",
  "title": "Mastering Mental Models",
  "t": "Most bestsellers disappear in 10 years. Filter reading by: what's still in print from 1970s/80s/90s? That's where enduring wisdom lives, not 2-month trends.",
  "cat": "craft"
 },
 {
  "slug": "ptak-the-prospects-for-active-management",
  "guest": "Jeff Ptak",
  "date": "2016-12-20",
  "title": "The Prospects for Active Management",
  "t": "Lowest-cost funds are 3x more likely to survive and succeed than most expensive ones—fee structure is the strongest predictor of manager success.",
  "cat": "investing"
 },
 {
  "slug": "ptak-the-prospects-for-active-management",
  "guest": "Jeff Ptak",
  "date": "2016-12-20",
  "title": "The Prospects for Active Management",
  "t": "Winning active funds often underperform for 10+ years before proving value. Winners look like losers—patience is required before drawing conclusions.",
  "cat": "investing"
 },
 {
  "slug": "ptak-the-prospects-for-active-management",
  "guest": "Jeff Ptak",
  "date": "2016-12-20",
  "title": "The Prospects for Active Management",
  "t": "Manager ownership + tenure + low turnover signal conviction, not just luck. These traits reveal how a manager thinks about investments before studying results.",
  "cat": "investing"
 },
 {
  "slug": "ptak-the-prospects-for-active-management",
  "guest": "Jeff Ptak",
  "date": "2016-12-20",
  "title": "The Prospects for Active Management",
  "t": "Success in active investing requires doing homework upfront then doing nothing. Frequent trading and monitoring destroys returns more than manager skill does.",
  "cat": "investing"
 },
 {
  "slug": "ptak-the-prospects-for-active-management",
  "guest": "Jeff Ptak",
  "date": "2016-12-20",
  "title": "The Prospects for Active Management",
  "t": "Style leadership cycles (growth vs value, large vs small) determine active manager timing more than skill—managers need styles out of favor to outperform indices.",
  "cat": "markets"
 },
 {
  "slug": "ptak-the-prospects-for-active-management",
  "guest": "Jeff Ptak",
  "date": "2016-12-20",
  "title": "The Prospects for Active Management",
  "t": "Transparency is a virtue but overused—obsessively watching portfolios leads to emotional trades, widening the gap between actual and earned returns.",
  "cat": "life"
 },
 {
  "slug": "ptak-the-prospects-for-active-management",
  "guest": "Jeff Ptak",
  "date": "2016-12-20",
  "title": "The Prospects for Active Management",
  "t": "Behavioral gaps in mutual funds (6-7% annualized loss from poor timing) dwarf manager selection skill—fixing investor discipline matters more than picking managers.",
  "cat": "investing"
 },
 {
  "slug": "ptak-the-prospects-for-active-management",
  "guest": "Jeff Ptak",
  "date": "2016-12-20",
  "title": "The Prospects for Active Management",
  "t": "Performance-based fees, not asset-based, align long-term incentives. Hedge funds get this right despite high fees—should apply discipline to mutual funds.",
  "cat": "markets"
 },
 {
  "slug": "rowley-vanguards-gerry-oreilly-and-jim-rowley",
  "guest": "Gerry O'Reilly & Jim Rowley",
  "date": "2016-10-18",
  "title": "Vanguard's Gerry O'Reilly and Jim Rowley",
  "t": "Vanguard culture: 'do the right thing' and speak 'we' not 'I'. Drives 20+ year tenures in finance.",
  "cat": "building"
 },
 {
  "slug": "rowley-vanguards-gerry-oreilly-and-jim-rowley",
  "guest": "Gerry O'Reilly & Jim Rowley",
  "date": "2016-10-18",
  "title": "Vanguard's Gerry O'Reilly and Jim Rowley",
  "t": "Passive indexing wins via zero-sum game: only half of dollars beat average, so low costs compound.",
  "cat": "investing"
 },
 {
  "slug": "rowley-vanguards-gerry-oreilly-and-jim-rowley",
  "guest": "Gerry O'Reilly & Jim Rowley",
  "date": "2016-10-18",
  "title": "Vanguard's Gerry O'Reilly and Jim Rowley",
  "t": "Tracking error vs. impact tradeoff: must balance small trades early vs. large end-of-day trades.",
  "cat": "craft"
 },
 {
  "slug": "rowley-vanguards-gerry-oreilly-and-jim-rowley",
  "guest": "Gerry O'Reilly & Jim Rowley",
  "date": "2016-10-18",
  "title": "Vanguard's Gerry O'Reilly and Jim Rowley",
  "t": "Market fragmented across 13 exchanges + dark pools. HFT provides liquidity; spreads collapsed 15 years.",
  "cat": "markets"
 },
 {
  "slug": "rowley-vanguards-gerry-oreilly-and-jim-rowley",
  "guest": "Gerry O'Reilly & Jim Rowley",
  "date": "2016-10-18",
  "title": "Vanguard's Gerry O'Reilly and Jim Rowley",
  "t": "Active manager selection: talent (subjective), cost (objective), patience (requisite). All three matter.",
  "cat": "investing"
 },
 {
  "slug": "rowley-vanguards-gerry-oreilly-and-jim-rowley",
  "guest": "Gerry O'Reilly & Jim Rowley",
  "date": "2016-10-18",
  "title": "Vanguard's Gerry O'Reilly and Jim Rowley",
  "t": "Stock-bond allocation is the single most powerful risk-return decision. Beats stock-picking decisions.",
  "cat": "investing"
 },
 {
  "slug": "rowley-vanguards-gerry-oreilly-and-jim-rowley",
  "guest": "Gerry O'Reilly & Jim Rowley",
  "date": "2016-10-18",
  "title": "Vanguard's Gerry O'Reilly and Jim Rowley",
  "t": "Index rebalancing is knowable; public. Corporates buyback knowing indexes must sell; creates liquidity.",
  "cat": "markets"
 },
 {
  "slug": "rowley-vanguards-gerry-oreilly-and-jim-rowley",
  "guest": "Gerry O'Reilly & Jim Rowley",
  "date": "2016-10-18",
  "title": "Vanguard's Gerry O'Reilly and Jim Rowley",
  "t": "Tax efficiency comes from indexing strategy first (low turnover), then ETF structure second.",
  "cat": "investing"
 },
 {
  "slug": "rowley-vanguards-gerry-oreilly-and-jim-rowley",
  "guest": "Gerry O'Reilly & Jim Rowley",
  "date": "2016-10-18",
  "title": "Vanguard's Gerry O'Reilly and Jim Rowley",
  "t": "Running four-minute mile required belief shift: once certain of breaking it, the mind enabled body.",
  "cat": "life"
 },
 {
  "slug": "rowley-vanguards-gerry-oreilly-and-jim-rowley",
  "guest": "Gerry O'Reilly & Jim Rowley",
  "date": "2016-10-18",
  "title": "Vanguard's Gerry O'Reilly and Jim Rowley",
  "t": "Global expansion (non-US markets) is next frontier for Vanguard; index culture can scale internationally.",
  "cat": "building"
 },
 {
  "slug": "rudder-the-quantified-self",
  "guest": "Christian Rudder",
  "date": "2016-10-11",
  "title": "The Quantified Self",
  "t": "Variance in appearance/traits matters more than absolute attractiveness. High-variance people within same attractiveness band get more attention.",
  "cat": "life"
 },
 {
  "slug": "rudder-the-quantified-self",
  "guest": "Christian Rudder",
  "date": "2016-10-11",
  "title": "The Quantified Self",
  "t": "What people say they want rarely matches what they do. Gap between survey responses and actual behavior is persistent and large.",
  "cat": "life"
 },
 {
  "slug": "rudder-the-quantified-self",
  "guest": "Christian Rudder",
  "date": "2016-10-11",
  "title": "The Quantified Self",
  "t": "Dating data reveals systematic racial bias present universally across platforms—key demographic groups experience 75% of average attention.",
  "cat": "markets"
 },
 {
  "slug": "rudder-the-quantified-self",
  "guest": "Christian Rudder",
  "date": "2016-10-11",
  "title": "The Quantified Self",
  "t": "Entrepreneurship requires persistence but also flexibility. Don't cling to one idea if data shows it's not working.",
  "cat": "building"
 },
 {
  "slug": "rudder-the-quantified-self",
  "guest": "Christian Rudder",
  "date": "2016-10-11",
  "title": "The Quantified Self",
  "t": "Picking the right metric to measure success is harder than collecting data. OKCupid switched from engagement to conversation-count.",
  "cat": "building"
 },
 {
  "slug": "rudder-the-quantified-self",
  "guest": "Christian Rudder",
  "date": "2016-10-11",
  "title": "The Quantified Self",
  "t": "Hardest part of data analysis is asking the right questions, not answering them. Data is abundant; direction is rare.",
  "cat": "craft"
 },
 {
  "slug": "rudder-the-quantified-self",
  "guest": "Christian Rudder",
  "date": "2016-10-11",
  "title": "The Quantified Self",
  "t": "Corporate and government surveillance differ fundamentally. Corporate is aggregated/broad; government is targeted/personal. Both invasive but differently.",
  "cat": "life"
 },
 {
  "slug": "rudder-the-quantified-self",
  "guest": "Christian Rudder",
  "date": "2016-10-11",
  "title": "The Quantified Self",
  "t": "Luck plays a tremendous role in startup success. Most successful founders underestimate how much luck enabled their outcome.",
  "cat": "life"
 },
 {
  "slug": "rudder-the-quantified-self",
  "guest": "Christian Rudder",
  "date": "2016-10-11",
  "title": "The Quantified Self",
  "t": "Division of labor without overlap in co-founder roles reduces dysfunction and prevents territoriality.",
  "cat": "building"
 },
 {
  "slug": "rudder-the-quantified-self",
  "guest": "Christian Rudder",
  "date": "2016-10-11",
  "title": "The Quantified Self",
  "t": "Real-world data on person-to-person interactions (dating) offers unique lens for studying inequality that demographic surveys cannot capture.",
  "cat": "markets"
 },
 {
  "slug": "seides-a-deep-dive-into-hedge-funds",
  "guest": "Ted Seides",
  "date": "2016-10-25",
  "title": "A Deep Dive into Hedge Funds",
  "t": "Rigorous rebalancing discipline is a form of systematic buying low and selling high across asset classes.",
  "cat": "investing"
 },
 {
  "slug": "seides-a-deep-dive-into-hedge-funds",
  "guest": "Ted Seides",
  "date": "2016-10-25",
  "title": "A Deep Dive into Hedge Funds",
  "t": "Being an early, important investor lets you be a price maker; marginal investors are price takers.",
  "cat": "investing"
 },
 {
  "slug": "seides-a-deep-dive-into-hedge-funds",
  "guest": "Ted Seides",
  "date": "2016-10-25",
  "title": "A Deep Dive into Hedge Funds",
  "t": "Hedge fund failures blamed on operations often reflect the founder's time diverted from investing, not operational collapse.",
  "cat": "building"
 },
 {
  "slug": "seides-a-deep-dive-into-hedge-funds",
  "guest": "Ted Seides",
  "date": "2016-10-25",
  "title": "A Deep Dive into Hedge Funds",
  "t": "The required return for hedge fund portfolios has collapsed from 6% to near cost-of-capital, eroding the economic case for fees.",
  "cat": "markets"
 },
 {
  "slug": "seides-a-deep-dive-into-hedge-funds",
  "guest": "Ted Seides",
  "date": "2016-10-25",
  "title": "A Deep Dive into Hedge Funds",
  "t": "New hedge fund founders master investment skill but neglect business fundamentals; operations issues undermine half of failures.",
  "cat": "building"
 },
 {
  "slug": "seides-a-deep-dive-into-hedge-funds",
  "guest": "Ted Seides",
  "date": "2016-10-25",
  "title": "A Deep Dive into Hedge Funds",
  "t": "Skill portability from prestigious institutions is uncertain; some organizations' training repeats while others' success is contextual.",
  "cat": "investing"
 },
 {
  "slug": "seides-a-deep-dive-into-hedge-funds",
  "guest": "Ted Seides",
  "date": "2016-10-25",
  "title": "A Deep Dive into Hedge Funds",
  "t": "Charisma—the ability to connect with allocators and fit their needs—is now essential to raising capital and launching funds.",
  "cat": "leadership"
 },
 {
  "slug": "seides-a-deep-dive-into-hedge-funds",
  "guest": "Ted Seides",
  "date": "2016-10-25",
  "title": "A Deep Dive into Hedge Funds",
  "t": "Established funds face rational economic barriers to adopting better fee structures; inertia in business model is powerful.",
  "cat": "markets"
 },
 {
  "slug": "shapiro-better-for-you-better-for-the-world",
  "guest": "Craig Shapiro",
  "date": "2016-11-14",
  "title": "Better for You, Better for the World",
  "t": "Businesses balancing profit with social good will generate the greatest financial returns over the next decade.",
  "cat": "investing"
 },
 {
  "slug": "shapiro-better-for-you-better-for-the-world",
  "guest": "Craig Shapiro",
  "date": "2016-11-14",
  "title": "Better for You, Better for the World",
  "t": "Personal roots - where you come from - profoundly shape your professional outcomes and investment philosophy.",
  "cat": "life"
 },
 {
  "slug": "shapiro-better-for-you-better-for-the-world",
  "guest": "Craig Shapiro",
  "date": "2016-11-14",
  "title": "Better for You, Better for the World",
  "t": "Culture has shifted toward stakeholder value, but financial markets still reward old-school shareholder-only thinking.",
  "cat": "markets"
 },
 {
  "slug": "shapiro-better-for-you-better-for-the-world",
  "guest": "Craig Shapiro",
  "date": "2016-11-14",
  "title": "Better for You, Better for the World",
  "t": "Getting older grants the ability to judge people' character faster and more accurately.",
  "cat": "life"
 },
 {
  "slug": "shapiro-better-for-you-better-for-the-world",
  "guest": "Craig Shapiro",
  "date": "2016-11-14",
  "title": "Better for You, Better for the World",
  "t": "Transparency about downs and insecurities is more valuable than optimistic narratives to investors.",
  "cat": "leadership"
 },
 {
  "slug": "shapiro-better-for-you-better-for-the-world",
  "guest": "Craig Shapiro",
  "date": "2016-11-14",
  "title": "Better for You, Better for the World",
  "t": "Founder psychology and personal narrative are crucial factors in evaluating investment potential.",
  "cat": "investing"
 },
 {
  "slug": "shapiro-watching-a-venture-fund-at-work",
  "guest": "Lauren Loktev, Kanyi Maqubela & Craig Shapiro",
  "date": "2017-01-10",
  "title": "Watching a Venture Fund at Work",
  "t": "Quality of a team is crucial to success in investing—venture capital is fundamentally an investment in people and their capability.",
  "cat": "investing"
 },
 {
  "slug": "shapiro-watching-a-venture-fund-at-work",
  "guest": "Lauren Loktev, Kanyi Maqubela & Craig Shapiro",
  "date": "2017-01-10",
  "title": "Watching a Venture Fund at Work",
  "t": "At early stage, market size matters most: will this grow to a billion-dollar company? Price accordingly to let founders raise successfully.",
  "cat": "investing"
 },
 {
  "slug": "shapiro-watching-a-venture-fund-at-work",
  "guest": "Lauren Loktev, Kanyi Maqubela & Craig Shapiro",
  "date": "2017-01-10",
  "title": "Watching a Venture Fund at Work",
  "t": "Growth mindset means willingness to change your point of view when data changes, not blind conviction to an original thesis.",
  "cat": "leadership"
 },
 {
  "slug": "shapiro-watching-a-venture-fund-at-work",
  "guest": "Lauren Loktev, Kanyi Maqubela & Craig Shapiro",
  "date": "2017-01-10",
  "title": "Watching a Venture Fund at Work",
  "t": "Pre-product market fit is rapid experimentation with closed feedback loops to learn quickly and build proprietary, first-principles knowledge.",
  "cat": "building"
 },
 {
  "slug": "shapiro-watching-a-venture-fund-at-work",
  "guest": "Lauren Loktev, Kanyi Maqubela & Craig Shapiro",
  "date": "2017-01-10",
  "title": "Watching a Venture Fund at Work",
  "t": "Brand is community, experience, and shared identity—it communicates values without words through design, service, and relationships.",
  "cat": "building"
 },
 {
  "slug": "shapiro-watching-a-venture-fund-at-work",
  "guest": "Lauren Loktev, Kanyi Maqubela & Craig Shapiro",
  "date": "2017-01-10",
  "title": "Watching a Venture Fund at Work",
  "t": "Good founders scratch their own itch; they solve problems that genuinely matter to them, not market trends.",
  "cat": "building"
 },
 {
  "slug": "shapiro-watching-a-venture-fund-at-work",
  "guest": "Lauren Loktev, Kanyi Maqubela & Craig Shapiro",
  "date": "2017-01-10",
  "title": "Watching a Venture Fund at Work",
  "t": "Fundraising is not a business model; capital efficiency and path to profitability are true survival heuristics.",
  "cat": "investing"
 },
 {
  "slug": "shapiro-watching-a-venture-fund-at-work",
  "guest": "Lauren Loktev, Kanyi Maqubela & Craig Shapiro",
  "date": "2017-01-10",
  "title": "Watching a Venture Fund at Work",
  "t": "Cost-average investments across a 4-year fund period to hedge against valuation cycles, not time the market.",
  "cat": "investing"
 },
 {
  "slug": "shapiro-watching-a-venture-fund-at-work",
  "guest": "Lauren Loktev, Kanyi Maqubela & Craig Shapiro",
  "date": "2017-01-10",
  "title": "Watching a Venture Fund at Work",
  "t": "Pay forward: opportunity opens doors for others; creating pathways for success is both obligation and resilience builder.",
  "cat": "life"
 },
 {
  "slug": "simler-exploring-the-frontier",
  "guest": "Kevin Simler",
  "date": "2016-11-22",
  "title": "Exploring the Frontier",
  "t": "Startup culture maintains the frontier mindset - growth, exploration, and building at the edges.",
  "cat": "building"
 },
 {
  "slug": "simler-exploring-the-frontier",
  "guest": "Kevin Simler",
  "date": "2016-11-22",
  "title": "Exploring the Frontier",
  "t": "The frontier is not just about growth but about maintaining an exploratory, creative spirit.",
  "cat": "building"
 },
 {
  "slug": "simler-exploring-the-frontier",
  "guest": "Kevin Simler",
  "date": "2016-11-22",
  "title": "Exploring the Frontier",
  "t": "Social status functions like money - it's a medium of exchange with real economic consequences.",
  "cat": "markets"
 },
 {
  "slug": "simler-exploring-the-frontier",
  "guest": "Kevin Simler",
  "date": "2016-11-22",
  "title": "Exploring the Frontier",
  "t": "Small businesses could benefit from startup culture without needing to grow; growth isn't always the goal.",
  "cat": "building"
 },
 {
  "slug": "simler-exploring-the-frontier",
  "guest": "Kevin Simler",
  "date": "2016-11-22",
  "title": "Exploring the Frontier",
  "t": "Metaphors shape how we see the world - playful vs. mechanical views lead to different human possibilities.",
  "cat": "life"
 },
 {
  "slug": "simler-exploring-the-frontier",
  "guest": "Kevin Simler",
  "date": "2016-11-22",
  "title": "Exploring the Frontier",
  "t": "The Western mechanical creation metaphor led to Newton and Einstein but disconnects from human experience.",
  "cat": "life"
 },
 {
  "slug": "simler-exploring-the-frontier",
  "guest": "Kevin Simler",
  "date": "2016-11-22",
  "title": "Exploring the Frontier",
  "t": "Ideas are more fun and enchanting when viewed as playful metaphors than mechanical explanations.",
  "cat": "life"
 },
 {
  "slug": "simler-exploring-the-frontier",
  "guest": "Kevin Simler",
  "date": "2016-11-22",
  "title": "Exploring the Frontier",
  "t": "Essay writing forces clarity of thinking and exploring ideas you don't fully understand yet.",
  "cat": "craft"
 },
 {
  "slug": "stein-the-state-of-automated-investing",
  "guest": "Jon Stein",
  "date": "2016-11-01",
  "title": "The State of Automated Investing",
  "t": "Inertia is the biggest competitor to financial behavior change; friction of onboarding or decision-making keeps people stuck.",
  "cat": "investing"
 },
 {
  "slug": "stein-the-state-of-automated-investing",
  "guest": "Jon Stein",
  "date": "2016-11-01",
  "title": "The State of Automated Investing",
  "t": "Automating tedious tasks (rebalancing, tax harvesting) frees advisors to handle genuine planning work and life-event conversations.",
  "cat": "building"
 },
 {
  "slug": "stein-the-state-of-automated-investing",
  "guest": "Jon Stein",
  "date": "2016-11-01",
  "title": "The State of Automated Investing",
  "t": "Most customer calls during bear markets aren't about market emotions; they're triggered by life events like inheritance or divorce.",
  "cat": "investing"
 },
 {
  "slug": "stein-the-state-of-automated-investing",
  "guest": "Jon Stein",
  "date": "2016-11-01",
  "title": "The State of Automated Investing",
  "t": "Compete on continuously expanding value, not cutting fees to zero; fees remain rational when services grow under the same price (Amazon Prime model).",
  "cat": "markets"
 },
 {
  "slug": "stein-the-state-of-automated-investing",
  "guest": "Jon Stein",
  "date": "2016-11-01",
  "title": "The State of Automated Investing",
  "t": "Customization without guardrails erodes advice quality; flexibility works best within a coherent advice framework.",
  "cat": "building"
 },
 {
  "slug": "stein-the-state-of-automated-investing",
  "guest": "Jon Stein",
  "date": "2016-11-01",
  "title": "The State of Automated Investing",
  "t": "Removing friction in onboarding is the make-or-break moment; seamless signup converts inertia into action.",
  "cat": "building"
 },
 {
  "slug": "stein-the-state-of-automated-investing",
  "guest": "Jon Stein",
  "date": "2016-11-01",
  "title": "The State of Automated Investing",
  "t": "The future of financial advice is invisible; your kids won't think about IRA types or contribution limits any more than you think about state capitals.",
  "cat": "life"
 },
 {
  "slug": "zweig-the-power-of-serendipity",
  "guest": "Jason Zweig",
  "date": "2016-09-27",
  "title": "The Power of Serendipity",
  "t": "Serendipity differs from luck: luck happens to you, but serendipity is something you can influence through intentional effort and curiosity.",
  "cat": "life"
 },
 {
  "slug": "zweig-the-power-of-serendipity",
  "guest": "Jason Zweig",
  "date": "2016-09-27",
  "title": "The Power of Serendipity",
  "t": "Personal relationships are immensely important in professional success; they create unexpected opportunities through genuine connection.",
  "cat": "building"
 },
 {
  "slug": "zweig-the-power-of-serendipity",
  "guest": "Jason Zweig",
  "date": "2016-09-27",
  "title": "The Power of Serendipity",
  "t": "Financial advisors create real value through comprehensive planning (tax, estate, retirement), not portfolio construction which is becoming commoditized.",
  "cat": "leadership"
 },
 {
  "slug": "zweig-the-power-of-serendipity",
  "guest": "Jason Zweig",
  "date": "2016-09-27",
  "title": "The Power of Serendipity",
  "t": "Don't overemphasize money with young kids; teach habits through example rather than explicit financial lessons to avoid obsession.",
  "cat": "leadership"
 },
 {
  "slug": "zweig-the-power-of-serendipity",
  "guest": "Jason Zweig",
  "date": "2016-09-27",
  "title": "The Power of Serendipity",
  "t": "When not working, fully disconnect from markets and finance; mental rest is essential for creative thinking and clarity.",
  "cat": "life"
 },
 {
  "slug": "zweig-the-power-of-serendipity",
  "guest": "Jason Zweig",
  "date": "2016-09-27",
  "title": "The Power of Serendipity",
  "t": "Critical thinking means investigating for yourself rather than relying on experts, conditioning, and conventional wisdom.",
  "cat": "craft"
 },
 {
  "slug": "zweig-the-power-of-serendipity",
  "guest": "Jason Zweig",
  "date": "2016-09-27",
  "title": "The Power of Serendipity",
  "t": "Feynman's greatest gift was modeling what critical thinking looks like in practice—a brilliant mind engaging the world with curiosity.",
  "cat": "craft"
 },
 {
  "slug": "zweig-the-power-of-serendipity",
  "guest": "Jason Zweig",
  "date": "2016-09-27",
  "title": "The Power of Serendipity",
  "t": "Making effort to connect with people across rooms creates serendipity; passive luck never transforms careers the way intentional relationship does.",
  "cat": "life"
 }
];
