// AUTO-GENERATED by gen_dashboard_data.py - do not edit
/* eslint-disable */
export const TYPE_DIST: any[] = [{"type": "Founder / Operator", "count": 150}, {"type": "VC", "count": 142}, {"type": "Hedge Fund", "count": 38}, {"type": "Public Markets", "count": 32}, {"type": "PE / Buyout", "count": 25}, {"type": "Academic / Author", "count": 33}, {"type": "Public-Co CEO", "count": 18}, {"type": "Other", "count": 30}];
