// AUTO-GENERATED by gen_dashboard_data.py — do not edit
/* eslint-disable */
export const QUOTES: any[] = [
 {
  "slug": "adams-an-internal-locus-of-control",
  "guest": "Kiley Adams",
  "date": "2016-10-28",
  "title": "An Internal Locus of Control",
  "q": "I don't remember.",
  "who": "Kiley Adams"
 },
 {
  "slug": "adams-an-internal-locus-of-control",
  "guest": "Kiley Adams",
  "date": "2016-10-28",
  "title": "An Internal Locus of Control",
  "q": "We're going to see if we can sneak you into Myanmar.",
  "who": "Catholic Bishop"
 },
 {
  "slug": "adams-an-internal-locus-of-control",
  "guest": "Kiley Adams",
  "date": "2016-10-28",
  "title": "An Internal Locus of Control",
  "q": "You don't rise to the occasion. You resort to your level of training.",
  "who": "Kiley Adams"
 },
 {
  "slug": "adams-an-internal-locus-of-control",
  "guest": "Kiley Adams",
  "date": "2016-10-28",
  "title": "An Internal Locus of Control",
  "q": "There is no backward. You don't retreat in a battle.",
  "who": "Kiley Adams"
 },
 {
  "slug": "beshore-cultivating-a-disaster-resistant-compound-interest-machine",
  "guest": "Brent Beshore",
  "date": "2016-11-08",
  "title": "Cultivating a Disaster Resistant, Compound Interest Machine",
  "q": "We buy boring businesses and make them less boring.",
  "who": "Brent Beshore"
 },
 {
  "slug": "beshore-cultivating-a-disaster-resistant-compound-interest-machine",
  "guest": "Brent Beshore",
  "date": "2016-11-08",
  "title": "Cultivating a Disaster Resistant, Compound Interest Machine",
  "q": "Creating a stable company from scratch is like eating glass.",
  "who": "Brent Beshore"
 },
 {
  "slug": "beshore-cultivating-a-disaster-resistant-compound-interest-machine",
  "guest": "Brent Beshore",
  "date": "2016-11-08",
  "title": "Cultivating a Disaster Resistant, Compound Interest Machine",
  "q": "You need people you can cry in front of and be your worst self.",
  "who": "Brent Beshore"
 },
 {
  "slug": "beshore-cultivating-a-disaster-resistant-compound-interest-machine",
  "guest": "Brent Beshore",
  "date": "2016-11-08",
  "title": "Cultivating a Disaster Resistant, Compound Interest Machine",
  "q": "The single biggest determining factor of success is compounding of knowledge.",
  "who": "Brent Beshore"
 },
 {
  "slug": "brown-the-reformation",
  "guest": "Josh Brown",
  "date": "2016-12-06",
  "title": "The Reformation",
  "q": "This isn't Burger King. You cannot have it your way. We decide portfolio after we know your goals.",
  "who": "Josh Brown (paraphrasing Rick Edelman)"
 },
 {
  "slug": "brown-the-reformation",
  "guest": "Josh Brown",
  "date": "2016-12-06",
  "title": "The Reformation",
  "q": "We're glorifying investors at the end of their careers when they're closed and returns are tough. That's like urging people to chase Amazon but not Bezos.",
  "who": "Josh Brown"
 },
 {
  "slug": "brown-the-reformation",
  "guest": "Josh Brown",
  "date": "2016-12-06",
  "title": "The Reformation",
  "q": "If you don't have a process and chase the dream, you're taking risks you don't need to take.",
  "who": "Josh Brown"
 },
 {
  "slug": "brown-the-reformation",
  "guest": "Josh Brown",
  "date": "2016-12-06",
  "title": "The Reformation",
  "q": "Slack is the first technology that creates virtual serendipity across dispersed teams, like cities do for innovation.",
  "who": "Josh Brown"
 },
 {
  "slug": "cole-small-bets-huge-payoffs",
  "guest": "Chris Cole",
  "date": "2016-11-29",
  "title": "Small Bets, Huge Payoffs",
  "q": "A black swan is when fear turns to horror. A positive black swan is any surprise non-linear benefit.",
  "who": "Chris Cole"
 },
 {
  "slug": "cole-small-bets-huge-payoffs",
  "guest": "Chris Cole",
  "date": "2016-11-29",
  "title": "Small Bets, Huge Payoffs",
  "q": "I'm right 1-2 times out of 10, but those times pay for everything.",
  "who": "Chris Cole"
 },
 {
  "slug": "cole-small-bets-huge-payoffs",
  "guest": "Chris Cole",
  "date": "2016-11-29",
  "title": "Small Bets, Huge Payoffs",
  "q": "You can't destroy risk. You take returns from the future and bring them to the present, and you take tails and push them into the future.",
  "who": "Chris Cole"
 },
 {
  "slug": "cole-small-bets-huge-payoffs",
  "guest": "Chris Cole",
  "date": "2016-11-29",
  "title": "Small Bets, Huge Payoffs",
  "q": "Dennis Rodman is 6 standard deviations away from the mean in rebounding. Rodman is better at rebounding than Michael Jordan is at scoring.",
  "who": "Chris Cole"
 },
 {
  "slug": "egan-designing-better-decisions",
  "guest": "Dan Egan",
  "date": "2017-01-03",
  "title": "Designing Better Decisions",
  "q": "What if we changed this one thing? How does that reveal what's really going on?",
  "who": "Dan Egan"
 },
 {
  "slug": "egan-designing-better-decisions",
  "guest": "Dan Egan",
  "date": "2017-01-03",
  "title": "Designing Better Decisions",
  "q": "The best way to predict the future is to build it.",
  "who": "Abraham Lincoln (via Dan Egan)"
 },
 {
  "slug": "egan-designing-better-decisions",
  "guest": "Dan Egan",
  "date": "2017-01-03",
  "title": "Designing Better Decisions",
  "q": "Never compete against somebody who enjoys what they're doing more than you.",
  "who": "Dan Egan"
 },
 {
  "slug": "egan-designing-better-decisions",
  "guest": "Dan Egan",
  "date": "2017-01-03",
  "title": "Designing Better Decisions",
  "q": "Money is a symptom of poverty.",
  "who": "Ian M. Banks (via Dan Egan)"
 },
 {
  "slug": "gramm-activist-investing",
  "guest": "Jeff Gramm",
  "date": "2016-09-11",
  "title": "Activist Investing",
  "q": "Value investing is a nice way of saying very pessimistic outlook.",
  "who": "Jeff Gramm"
 },
 {
  "slug": "gramm-activist-investing",
  "guest": "Jeff Gramm",
  "date": "2016-09-11",
  "title": "Activist Investing",
  "q": "People are self-interested animals.",
  "who": "Jeff Gramm"
 },
 {
  "slug": "gramm-activist-investing",
  "guest": "Jeff Gramm",
  "date": "2016-09-11",
  "title": "Activist Investing",
  "q": "Great capital allocation is so rare. It can be hard to predict in the future.",
  "who": "Jeff Gramm"
 },
 {
  "slug": "gramm-activist-investing",
  "guest": "Jeff Gramm",
  "date": "2016-09-11",
  "title": "Activist Investing",
  "q": "Boards often don't know how to value companies or think about the value of their companies.",
  "who": "Jeff Gramm"
 },
 {
  "slug": "housel-walking-and-thinking",
  "guest": "Morgan Housel",
  "date": "2016-10-04",
  "title": "Walking and Thinking",
  "q": "The odds are this won't work. 1 in 50, that's great. Better than I thought.",
  "who": "Morgan Housel"
 },
 {
  "slug": "housel-walking-and-thinking",
  "guest": "Morgan Housel",
  "date": "2016-10-04",
  "title": "Walking and Thinking",
  "q": "You only think when you walk. I only think when I walk.",
  "who": "Morgan Housel"
 },
 {
  "slug": "housel-walking-and-thinking",
  "guest": "Morgan Housel",
  "date": "2016-10-04",
  "title": "Walking and Thinking",
  "q": "Almost every great investor gets more humble as time goes on.",
  "who": "Morgan Housel"
 },
 {
  "slug": "koppelman-chasing-curiosity",
  "guest": "Brian Koppelman",
  "date": "2017-01-24",
  "title": "Chasing Curiosity",
  "q": "I don't change things when they're still working. That's your move.",
  "who": "Solitary Man character (quoted)"
 },
 {
  "slug": "koppelman-chasing-curiosity",
  "guest": "Brian Koppelman",
  "date": "2017-01-24",
  "title": "Chasing Curiosity",
  "q": "Humans are happiest when accessing their most creative self.",
  "who": "Brian Koppelman"
 },
 {
  "slug": "koppelman-chasing-curiosity",
  "guest": "Brian Koppelman",
  "date": "2017-01-24",
  "title": "Chasing Curiosity",
  "q": "You overestimate what you accomplish in a year; underestimate what you accomplish in 10.",
  "who": "Tony Robbins (cited)"
 },
 {
  "slug": "koppelman-chasing-curiosity",
  "guest": "Brian Koppelman",
  "date": "2017-01-24",
  "title": "Chasing Curiosity",
  "q": "If I knew the answer, I'd have to stop writing it.",
  "who": "Brian Koppelman"
 },
 {
  "slug": "koppelman-chasing-curiosity",
  "guest": "Brian Koppelman",
  "date": "2017-01-24",
  "title": "Chasing Curiosity",
  "q": "The conscious mind disappears and you enter this alpha state.",
  "who": "Brian Koppelman"
 },
 {
  "slug": "maddox-the-ace-of-spades",
  "guest": "Eric Maddox",
  "date": "2016-12-13",
  "title": "The Ace of Spades",
  "q": "The old technique never got a single prisoner to open up. 4% success rate across military. My method: 65%.",
  "who": "Eric Maddox"
 },
 {
  "slug": "maddox-the-ace-of-spades",
  "guest": "Eric Maddox",
  "date": "2016-12-13",
  "title": "The Ace of Spades",
  "q": "I don't know much about this topic, but here's what I'm reading—join me. That openness changes everything.",
  "who": "Eric Maddox (on teaching approach)"
 },
 {
  "slug": "maddox-the-ace-of-spades",
  "guest": "Eric Maddox",
  "date": "2016-12-13",
  "title": "The Ace of Spades",
  "q": "Charisma is power plus empathy. A great listener is an attractive person. They know when you're listening.",
  "who": "Eric Maddox"
 },
 {
  "slug": "maddox-the-ace-of-spades",
  "guest": "Eric Maddox",
  "date": "2016-12-13",
  "title": "The Ace of Spades",
  "q": "Courage is knowing it's right to help the enemy at the lower level for the larger strategic mission, even when your soldiers hate it.",
  "who": "Eric Maddox (paraphrasing his Delta commander)"
 },
 {
  "slug": "mauboussin-active-asset-management",
  "guest": "Michael Mauboussin",
  "date": "2016-09-20",
  "title": "Active Asset Management",
  "q": "A great client is one who cashes a check when we hand it to him and writes us a check when we ask.",
  "who": "Michael Mauboussin"
 },
 {
  "slug": "mauboussin-active-asset-management",
  "guest": "Michael Mauboussin",
  "date": "2016-09-20",
  "title": "Active Asset Management",
  "q": "Skill is analytical skills and managing behavioral issues; portfolio construction is managing and mitigating behavioral problems.",
  "who": "Michael Mauboussin"
 },
 {
  "slug": "mauboussin-active-asset-management",
  "guest": "Michael Mauboussin",
  "date": "2016-09-20",
  "title": "Active Asset Management",
  "q": "For stock to go up, you must do better than what the market already expects.",
  "who": "Michael Mauboussin"
 },
 {
  "slug": "mauboussin-active-asset-management",
  "guest": "Michael Mauboussin",
  "date": "2016-09-20",
  "title": "Active Asset Management",
  "q": "Articles about buybacks by journalists are drivel—not informed or thoughtful.",
  "who": "Michael Mauboussin"
 },
 {
  "slug": "parrish-mastering-mental-models",
  "guest": "Shane Parrish",
  "date": "2016-12-27",
  "title": "Mastering Mental Models",
  "q": "The growth mindset is: if I work harder, I can learn how to do it.",
  "who": "Shane Parrish"
 },
 {
  "slug": "parrish-mastering-mental-models",
  "guest": "Shane Parrish",
  "date": "2016-12-27",
  "title": "Mastering Mental Models",
  "q": "Mastering the best of what other people have figured out.",
  "who": "Shane Parrish"
 },
 {
  "slug": "parrish-mastering-mental-models",
  "guest": "Shane Parrish",
  "date": "2016-12-27",
  "title": "Mastering Mental Models",
  "q": "Most of today's bestsellers disappear in 10 years.",
  "who": "Shane Parrish"
 },
 {
  "slug": "parrish-mastering-mental-models",
  "guest": "Shane Parrish",
  "date": "2016-12-27",
  "title": "Mastering Mental Models",
  "q": "You can create more money, but you can't create more time.",
  "who": "Shane Parrish"
 },
 {
  "slug": "ptak-the-prospects-for-active-management",
  "guest": "Jeff Ptak",
  "date": "2016-12-20",
  "title": "The Prospects for Active Management",
  "q": "The cheapest quintile are 3x as likely to survive than the most expensive quintile.",
  "who": "Jeff Ptak"
 },
 {
  "slug": "ptak-the-prospects-for-active-management",
  "guest": "Jeff Ptak",
  "date": "2016-12-20",
  "title": "The Prospects for Active Management",
  "q": "It's not the action that's important. In many cases, it's inaction.",
  "who": "Jeff Ptak"
 },
 {
  "slug": "ptak-the-prospects-for-active-management",
  "guest": "Jeff Ptak",
  "date": "2016-12-20",
  "title": "The Prospects for Active Management",
  "q": "Unless they're willing to do the work, they should index.",
  "who": "Jeff Ptak"
 },
 {
  "slug": "ptak-the-prospects-for-active-management",
  "guest": "Jeff Ptak",
  "date": "2016-12-20",
  "title": "The Prospects for Active Management",
  "q": "Winners very often don't look like winners for long stretches.",
  "who": "Jeff Ptak"
 },
 {
  "slug": "rowley-vanguards-gerry-oreilly-and-jim-rowley",
  "guest": "Gerry O'Reilly & Jim Rowley",
  "date": "2016-10-18",
  "title": "Vanguard's Gerry O'Reilly and Jim Rowley",
  "q": "Only half the dollars can do better than average, no matter what.",
  "who": "Jim Rowley"
 },
 {
  "slug": "rowley-vanguards-gerry-oreilly-and-jim-rowley",
  "guest": "Gerry O'Reilly & Jim Rowley",
  "date": "2016-10-18",
  "title": "Vanguard's Gerry O'Reilly and Jim Rowley",
  "q": "You start every sentence with 'we' not 'I.' That gets noticed.",
  "who": "Jim Rowley"
 },
 {
  "slug": "rowley-vanguards-gerry-oreilly-and-jim-rowley",
  "guest": "Gerry O'Reilly & Jim Rowley",
  "date": "2016-10-18",
  "title": "Vanguard's Gerry O'Reilly and Jim Rowley",
  "q": "The stock-bond decision is the most powerful risk-return decision you can make.",
  "who": "Jim Rowley"
 },
 {
  "slug": "rowley-vanguards-gerry-oreilly-and-jim-rowley",
  "guest": "Gerry O'Reilly & Jim Rowley",
  "date": "2016-10-18",
  "title": "Vanguard's Gerry O'Reilly and Jim Rowley",
  "q": "I look forward to coming in Monday morning. I think I'm in the minority.",
  "who": "Gerry O'Reilly"
 },
 {
  "slug": "rudder-the-quantified-self",
  "guest": "Christian Rudder",
  "date": "2016-10-11",
  "title": "The Quantified Self",
  "q": "Guys basically go after the youngest women period.",
  "who": "Christian Rudder"
 },
 {
  "slug": "rudder-the-quantified-self",
  "guest": "Christian Rudder",
  "date": "2016-10-11",
  "title": "The Quantified Self",
  "q": "What you do with the results of the math, that's by far the hardest part.",
  "who": "Christian Rudder"
 },
 {
  "slug": "rudder-the-quantified-self",
  "guest": "Christian Rudder",
  "date": "2016-10-11",
  "title": "The Quantified Self",
  "q": "Be persistent but don't be too committed to this one idea if people don't like it.",
  "who": "Christian Rudder"
 },
 {
  "slug": "rudder-the-quantified-self",
  "guest": "Christian Rudder",
  "date": "2016-10-11",
  "title": "The Quantified Self",
  "q": "Luck plays a tremendous amount. Things could've gone sideways very easily.",
  "who": "Christian Rudder"
 },
 {
  "slug": "seides-a-deep-dive-into-hedge-funds",
  "guest": "Ted Seides",
  "date": "2016-10-25",
  "title": "A Deep Dive into Hedge Funds",
  "q": "Be the hero of your own life.",
  "who": "Ted Seides"
 },
 {
  "slug": "seides-a-deep-dive-into-hedge-funds",
  "guest": "Ted Seides",
  "date": "2016-10-25",
  "title": "A Deep Dive into Hedge Funds",
  "q": "It's a people business. Ultimately you're making an assessment of the individual.",
  "who": "Ted Seides"
 },
 {
  "slug": "seides-a-deep-dive-into-hedge-funds",
  "guest": "Ted Seides",
  "date": "2016-10-25",
  "title": "A Deep Dive into Hedge Funds",
  "q": "Yeah, it worked.",
  "who": "John Paulson"
 },
 {
  "slug": "seides-a-deep-dive-into-hedge-funds",
  "guest": "Ted Seides",
  "date": "2016-10-25",
  "title": "A Deep Dive into Hedge Funds",
  "q": "Hedge fund operations are like going to the dentist; investors have zero patience for mistakes.",
  "who": "Ted Seides"
 },
 {
  "slug": "shapiro-better-for-you-better-for-the-world",
  "guest": "Craig Shapiro",
  "date": "2016-11-14",
  "title": "Better for You, Better for the World",
  "q": "Don't shine the turd - if something goes wrong, tell me immediately.",
  "who": "Anonymous investor to Craig"
 },
 {
  "slug": "shapiro-better-for-you-better-for-the-world",
  "guest": "Craig Shapiro",
  "date": "2016-11-14",
  "title": "Better for You, Better for the World",
  "q": "Businesses balancing profit and social good generate the greatest returns.",
  "who": "Craig Shapiro"
 },
 {
  "slug": "shapiro-better-for-you-better-for-the-world",
  "guest": "Craig Shapiro",
  "date": "2016-11-14",
  "title": "Better for You, Better for the World",
  "q": "Financial markets haven't shifted alongside culture toward stakeholder value.",
  "who": "Craig Shapiro"
 },
 {
  "slug": "shapiro-watching-a-venture-fund-at-work",
  "guest": "Lauren Loktev, Kanyi Maqubela & Craig Shapiro",
  "date": "2017-01-10",
  "title": "Watching a Venture Fund at Work",
  "q": "Investing in assets that don't exist yet requires hands-on work but also deep thematic conviction.",
  "who": "Craig Shapiro"
 },
 {
  "slug": "shapiro-watching-a-venture-fund-at-work",
  "guest": "Lauren Loktev, Kanyi Maqubela & Craig Shapiro",
  "date": "2017-01-10",
  "title": "Watching a Venture Fund at Work",
  "q": "Fundraising is not a business model.",
  "who": "Kanyi Maqubela"
 },
 {
  "slug": "shapiro-watching-a-venture-fund-at-work",
  "guest": "Lauren Loktev, Kanyi Maqubela & Craig Shapiro",
  "date": "2017-01-10",
  "title": "Watching a Venture Fund at Work",
  "q": "Brand is at least to some extent about relationships.",
  "who": "Kanyi Maqubela"
 },
 {
  "slug": "shapiro-watching-a-venture-fund-at-work",
  "guest": "Lauren Loktev, Kanyi Maqubela & Craig Shapiro",
  "date": "2017-01-10",
  "title": "Watching a Venture Fund at Work",
  "q": "The pace at which you uncover unknown unknowns is how you know a founder is really getting deep into their market.",
  "who": "Kanyi Maqubela"
 },
 {
  "slug": "simler-exploring-the-frontier",
  "guest": "Kevin Simler",
  "date": "2016-11-22",
  "title": "Exploring the Frontier",
  "q": "Palantir was and always will be a startup - in my heart.",
  "who": "Kevin Simler"
 },
 {
  "slug": "simler-exploring-the-frontier",
  "guest": "Kevin Simler",
  "date": "2016-11-22",
  "title": "Exploring the Frontier",
  "q": "If you think the world is playful, it's more fun to be in.",
  "who": "Kevin Simler"
 },
 {
  "slug": "simler-exploring-the-frontier",
  "guest": "Kevin Simler",
  "date": "2016-11-22",
  "title": "Exploring the Frontier",
  "q": "The frontier is not synonymous with growth, but highly implicative of it.",
  "who": "Kevin Simler"
 },
 {
  "slug": "simler-exploring-the-frontier",
  "guest": "Kevin Simler",
  "date": "2016-11-22",
  "title": "Exploring the Frontier",
  "q": "Math unlocks the inner workings of the world, but disconnects from what it means to be human.",
  "who": "Kevin Simler"
 },
 {
  "slug": "stein-the-state-of-automated-investing",
  "guest": "Jon Stein",
  "date": "2016-11-01",
  "title": "The State of Automated Investing",
  "q": "Inertia is our biggest competitor.",
  "who": "Jon Stein"
 },
 {
  "slug": "stein-the-state-of-automated-investing",
  "guest": "Jon Stein",
  "date": "2016-11-01",
  "title": "The State of Automated Investing",
  "q": "It only exists because we say it exists.",
  "who": "Jon Stein"
 },
 {
  "slug": "stein-the-state-of-automated-investing",
  "guest": "Jon Stein",
  "date": "2016-11-01",
  "title": "The State of Automated Investing",
  "q": "We're building an institution, and by that I mean, building for the long term.",
  "who": "Jon Stein"
 },
 {
  "slug": "stein-the-state-of-automated-investing",
  "guest": "Jon Stein",
  "date": "2016-11-01",
  "title": "The State of Automated Investing",
  "q": "You don't rise to the occasion. You resort to your level of training.",
  "who": "Jon Stein"
 },
 {
  "slug": "zweig-the-power-of-serendipity",
  "guest": "Jason Zweig",
  "date": "2016-09-27",
  "title": "The Power of Serendipity",
  "q": "You just seemed like the kind of person I should take a chance on.",
  "who": "Jason's early hiring manager"
 },
 {
  "slug": "zweig-the-power-of-serendipity",
  "guest": "Jason Zweig",
  "date": "2016-09-27",
  "title": "The Power of Serendipity",
  "q": "Good financial advisor is worth platinum. Portfolio management is commodity; financial planning is priceless.",
  "who": "Jason Zweig"
 },
 {
  "slug": "zweig-the-power-of-serendipity",
  "guest": "Jason Zweig",
  "date": "2016-09-27",
  "title": "The Power of Serendipity",
  "q": "Serendipity is something you can influence, you can shape. Luck happens to you.",
  "who": "Jason Zweig"
 },
 {
  "slug": "zweig-the-power-of-serendipity",
  "guest": "Jason Zweig",
  "date": "2016-09-27",
  "title": "The Power of Serendipity",
  "q": "Essay means attempt—bounded in expectations. You're making an attempt to make sense of the world, not solve universe.",
  "who": "Jason Zweig (on Montaigne)"
 }
];
