// AUTO-GENERATED by gen_dashboard_data.py — do not edit
/* eslint-disable */
export const REPEAT_GUESTS: any[] = [
 {
  "guest": "Gavin Baker",
  "count": 6
 },
 {
  "guest": "Michael Mauboussin",
  "count": 4
 },
 {
  "guest": "Ted Seides",
  "count": 3
 },
 {
  "guest": "Brent Beshore",
  "count": 3
 },
 {
  "guest": "Ali Hamed",
  "count": 3
 },
 {
  "guest": "Modest Proposal",
  "count": 3
 },
 {
  "guest": "Bill Gurley",
  "count": 3
 },
 {
  "guest": "David Senra",
  "count": 3
 },
 {
  "guest": "Jeremiah Lowin",
  "count": 2
 },
 {
  "guest": "Leigh Drogen",
  "count": 2
 },
 {
  "guest": "Jerry Neumann",
  "count": 2
 },
 {
  "guest": "Chris Dixon",
  "count": 2
 },
 {
  "guest": "Josh Wolfe",
  "count": 2
 },
 {
  "guest": "Dan Rasmussen",
  "count": 2
 },
 {
  "guest": "Matt Ball",
  "count": 2
 },
 {
  "guest": "Boyd Varty",
  "count": 2
 },
 {
  "guest": "Bryan Krug",
  "count": 2
 },
 {
  "guest": "Ben Gilbert and David Rosenthal of Acquired",
  "count": 2
 },
 {
  "guest": "Jesse Livermore",
  "count": 2
 },
 {
  "guest": "Chris Bloomstran",
  "count": 2
 },
 {
  "guest": "Chad Cascarilla",
  "count": 2
 },
 {
  "guest": "Daniel Ek",
  "count": 2
 },
 {
  "guest": "Jeremy Grantham",
  "count": 2
 },
 {
  "guest": "Marc Andreessen",
  "count": 2
 },
 {
  "guest": "Carl Kawaja",
  "count": 2
 },
 {
  "guest": "Karen Karniol-Tambour",
  "count": 2
 },
 {
  "guest": "Jay Hoag",
  "count": 2
 },
 {
  "guest": "Tobi Lütke",
  "count": 2
 },
 {
  "guest": "Aswath Damodaran",
  "count": 2
 },
 {
  "guest": "Martin Casado",
  "count": 2
 }
];
