// AUTO-GENERATED by gen_dashboard_data.py — do not edit
/* eslint-disable */
export const QUOTES: any[] = [
 {
  "slug": "adams-an-internal-locus-of-control",
  "guest": "Kiley Adams",
  "date": "2016-10-28",
  "title": "An Internal Locus of Control",
  "q": "I don't remember.",
  "who": "Kiley Adams"
 },
 {
  "slug": "adams-an-internal-locus-of-control",
  "guest": "Kiley Adams",
  "date": "2016-10-28",
  "title": "An Internal Locus of Control",
  "q": "We're going to see if we can sneak you into Myanmar.",
  "who": "Catholic Bishop"
 },
 {
  "slug": "adams-an-internal-locus-of-control",
  "guest": "Kiley Adams",
  "date": "2016-10-28",
  "title": "An Internal Locus of Control",
  "q": "You don't rise to the occasion. You resort to your level of training.",
  "who": "Kiley Adams"
 },
 {
  "slug": "adams-an-internal-locus-of-control",
  "guest": "Kiley Adams",
  "date": "2016-10-28",
  "title": "An Internal Locus of Control",
  "q": "There is no backward. You don't retreat in a battle.",
  "who": "Kiley Adams"
 },
 {
  "slug": "attia-how-to-live-a-longer-higher-quality-life",
  "guest": "Peter Attia, M.D.",
  "date": "2017-03-07",
  "title": "How to Live a Longer, Higher Quality Life",
  "q": "Mastery is my crack. I have to be mastering something.",
  "who": "Peter Attia"
 },
 {
  "slug": "attia-how-to-live-a-longer-higher-quality-life",
  "guest": "Peter Attia, M.D.",
  "date": "2017-03-07",
  "title": "How to Live a Longer, Higher Quality Life",
  "q": "The only thing worth doing in moderation is moderation.",
  "who": "Peter Attia"
 },
 {
  "slug": "attia-how-to-live-a-longer-higher-quality-life",
  "guest": "Peter Attia, M.D.",
  "date": "2017-03-07",
  "title": "How to Live a Longer, Higher Quality Life",
  "q": "I always followed the path of bliss over financial opportunity; compounding wins.",
  "who": "Peter Attia"
 },
 {
  "slug": "attia-how-to-live-a-longer-higher-quality-life",
  "guest": "Peter Attia, M.D.",
  "date": "2017-03-07",
  "title": "How to Live a Longer, Higher Quality Life",
  "q": "Define wealth by great people in your life, not money or success.",
  "who": "Peter Attia"
 },
 {
  "slug": "attia-peter-attia-live",
  "guest": "Peter Attia",
  "date": "2018-03-27",
  "title": "Peter Attia - Live",
  "q": "The single most important thing you can do to live longer is pick the right parents.",
  "who": "Peter Attia"
 },
 {
  "slug": "attia-peter-attia-live",
  "guest": "Peter Attia",
  "date": "2018-03-27",
  "title": "Peter Attia - Live",
  "q": "Your sport is life now—I'm more interested in not being hurt and doing things for as long as possible.",
  "who": "Peter Attia"
 },
 {
  "slug": "attia-peter-attia-live",
  "guest": "Peter Attia",
  "date": "2018-03-27",
  "title": "Peter Attia - Live",
  "q": "I would say it's actually really good to be hungry sometimes. It's physiologically relevant.",
  "who": "Peter Attia"
 },
 {
  "slug": "attia-peter-attia-live",
  "guest": "Peter Attia",
  "date": "2018-03-27",
  "title": "Peter Attia - Live",
  "q": "Never stop lifting weights. It's the difference between breaking your hip at 75 and not.",
  "who": "Peter Attia"
 },
 {
  "slug": "beshore-cultivating-a-disaster-resistant-compound-interest-machine",
  "guest": "Brent Beshore",
  "date": "2016-11-08",
  "title": "Cultivating a Disaster Resistant, Compound Interest Machine",
  "q": "We buy boring businesses and make them less boring.",
  "who": "Brent Beshore"
 },
 {
  "slug": "beshore-cultivating-a-disaster-resistant-compound-interest-machine",
  "guest": "Brent Beshore",
  "date": "2016-11-08",
  "title": "Cultivating a Disaster Resistant, Compound Interest Machine",
  "q": "Creating a stable company from scratch is like eating glass.",
  "who": "Brent Beshore"
 },
 {
  "slug": "beshore-cultivating-a-disaster-resistant-compound-interest-machine",
  "guest": "Brent Beshore",
  "date": "2016-11-08",
  "title": "Cultivating a Disaster Resistant, Compound Interest Machine",
  "q": "You need people you can cry in front of and be your worst self.",
  "who": "Brent Beshore"
 },
 {
  "slug": "beshore-cultivating-a-disaster-resistant-compound-interest-machine",
  "guest": "Brent Beshore",
  "date": "2016-11-08",
  "title": "Cultivating a Disaster Resistant, Compound Interest Machine",
  "q": "The single biggest determining factor of success is compounding of knowledge.",
  "who": "Brent Beshore"
 },
 {
  "slug": "beshore-private-equity-venture-capital-and-the-future-of-money-management",
  "guest": "Brent Beshore",
  "date": "2017-01-31",
  "title": "Private Equity, Venture Capital, and the Future of Money Management",
  "q": "Most businesses don't get large on purpose because the founder is the moat.",
  "who": "Brent"
 },
 {
  "slug": "beshore-private-equity-venture-capital-and-the-future-of-money-management",
  "guest": "Brent Beshore",
  "date": "2017-01-31",
  "title": "Private Equity, Venture Capital, and the Future of Money Management",
  "q": "Operating a company is like a knife fight; you get out of bed with a knife and try to keep the wild animals away.",
  "who": "Brent"
 },
 {
  "slug": "beshore-private-equity-venture-capital-and-the-future-of-money-management",
  "guest": "Brent Beshore",
  "date": "2017-01-31",
  "title": "Private Equity, Venture Capital, and the Future of Money Management",
  "q": "The biggest secret is there is no secret, you just got to test stuff and see what works.",
  "who": "Brent"
 },
 {
  "slug": "beshore-private-equity-venture-capital-and-the-future-of-money-management",
  "guest": "Brent Beshore",
  "date": "2017-01-31",
  "title": "Private Equity, Venture Capital, and the Future of Money Management",
  "q": "Nothing is worse than claiming one thing and doing something different.",
  "who": "Brent"
 },
 {
  "slug": "beshore-private-equity-venture-capital-and-the-future-of-money-management",
  "guest": "Brent Beshore",
  "date": "2017-01-31",
  "title": "Private Equity, Venture Capital, and the Future of Money Management",
  "q": "Brand is the distribution of likely outcomes that you can expect from any company or person.",
  "who": "Brent"
 },
 {
  "slug": "brown-the-reformation",
  "guest": "Josh Brown",
  "date": "2016-12-06",
  "title": "The Reformation",
  "q": "This isn't Burger King. You cannot have it your way. We decide portfolio after we know your goals.",
  "who": "Josh Brown (paraphrasing Rick Edelman)"
 },
 {
  "slug": "brown-the-reformation",
  "guest": "Josh Brown",
  "date": "2016-12-06",
  "title": "The Reformation",
  "q": "We're glorifying investors at the end of their careers when they're closed and returns are tough. That's like urging people to chase Amazon but not Bezos.",
  "who": "Josh Brown"
 },
 {
  "slug": "brown-the-reformation",
  "guest": "Josh Brown",
  "date": "2016-12-06",
  "title": "The Reformation",
  "q": "If you don't have a process and chase the dream, you're taking risks you don't need to take.",
  "who": "Josh Brown"
 },
 {
  "slug": "brown-the-reformation",
  "guest": "Josh Brown",
  "date": "2016-12-06",
  "title": "The Reformation",
  "q": "Slack is the first technology that creates virtual serendipity across dispersed teams, like cities do for innovation.",
  "who": "Josh Brown"
 },
 {
  "slug": "brown-the-wu-tang-clan-of-finance",
  "guest": "Josh Brown & Michael Batnick & Barry Ritholtz",
  "date": "2017-08-29",
  "title": "The Wu Tang Clan of Finance",
  "q": "I write for an audience of one, if other people want to read it, fantastic.",
  "who": "Barry"
 },
 {
  "slug": "brown-the-wu-tang-clan-of-finance",
  "guest": "Josh Brown & Michael Batnick & Barry Ritholtz",
  "date": "2017-08-29",
  "title": "The Wu Tang Clan of Finance",
  "q": "It's too early to have an extremely doctrinaire opinion about Bitcoin, but it's too late to not have some experimental project going on.",
  "who": "Josh"
 },
 {
  "slug": "brown-the-wu-tang-clan-of-finance",
  "guest": "Josh Brown & Michael Batnick & Barry Ritholtz",
  "date": "2017-08-29",
  "title": "The Wu Tang Clan of Finance",
  "q": "Everything's built on a story.",
  "who": "Patrick"
 },
 {
  "slug": "brown-the-wu-tang-clan-of-finance",
  "guest": "Josh Brown & Michael Batnick & Barry Ritholtz",
  "date": "2017-08-29",
  "title": "The Wu Tang Clan of Finance",
  "q": "We're like the Wu Tang clan—all the best MCs in one place but you know ODB from Liquid Swords instantly.",
  "who": "Josh"
 },
 {
  "slug": "byrne-cryptopocalypse",
  "guest": "Preston Byrne",
  "date": "2018-01-16",
  "title": "Cryptopocalypse",
  "q": "It's an unregulated penny stock casino of the 21st century.",
  "who": "Preston Byrne"
 },
 {
  "slug": "byrne-cryptopocalypse",
  "guest": "Preston Byrne",
  "date": "2018-01-16",
  "title": "Cryptopocalypse",
  "q": "Blockchains don't scale. And the bigger they get, the more unwieldy they get.",
  "who": "Preston Byrne"
 },
 {
  "slug": "byrne-cryptopocalypse",
  "guest": "Preston Byrne",
  "date": "2018-01-16",
  "title": "Cryptopocalypse",
  "q": "I say we take off and nuke the entire site from orbit.",
  "who": "Preston Byrne (quoting Aliens on SEC's Howey opinion)"
 },
 {
  "slug": "byrne-cryptopocalypse",
  "guest": "Preston Byrne",
  "date": "2018-01-16",
  "title": "Cryptopocalypse",
  "q": "You don't really need the coins to achieve distributed infrastructure. You can use Hyperledger.",
  "who": "Preston Byrne"
 },
 {
  "slug": "cassel-investing-in-tiny-stocks",
  "guest": "Ian Cassel",
  "date": "2017-02-14",
  "title": "Investing In Tiny Stocks",
  "q": "An intelligent fanatic is someone with genuine intellectual interest in something.",
  "who": "Ian"
 },
 {
  "slug": "cassel-investing-in-tiny-stocks",
  "guest": "Ian Cassel",
  "date": "2017-02-14",
  "title": "Investing In Tiny Stocks",
  "q": "Most of these companies can't be owned by large institutions because of minimum position sizes.",
  "who": "Ian"
 },
 {
  "slug": "cassel-investing-in-tiny-stocks",
  "guest": "Ian Cassel",
  "date": "2017-02-14",
  "title": "Investing In Tiny Stocks",
  "q": "I'd rather spend time studying the history of great companies when they were small.",
  "who": "Ian"
 },
 {
  "slug": "chilton-the-human-blitzkrieg",
  "guest": "Dave Chilton",
  "date": "2017-05-30",
  "title": "The Human Blitzkrieg",
  "q": "Everywhere I go, people say the book made a difference in their lives.",
  "who": "Dave Chilton"
 },
 {
  "slug": "chilton-the-human-blitzkrieg",
  "guest": "Dave Chilton",
  "date": "2017-05-30",
  "title": "The Human Blitzkrieg",
  "q": "I've never been sued, never sued anybody, never had major conflicts—I just kept it light and loose.",
  "who": "Dave Chilton"
 },
 {
  "slug": "cole-small-bets-huge-payoffs",
  "guest": "Chris Cole",
  "date": "2016-11-29",
  "title": "Small Bets, Huge Payoffs",
  "q": "A black swan is when fear turns to horror. A positive black swan is any surprise non-linear benefit.",
  "who": "Chris Cole"
 },
 {
  "slug": "cole-small-bets-huge-payoffs",
  "guest": "Chris Cole",
  "date": "2016-11-29",
  "title": "Small Bets, Huge Payoffs",
  "q": "I'm right 1-2 times out of 10, but those times pay for everything.",
  "who": "Chris Cole"
 },
 {
  "slug": "cole-small-bets-huge-payoffs",
  "guest": "Chris Cole",
  "date": "2016-11-29",
  "title": "Small Bets, Huge Payoffs",
  "q": "You can't destroy risk. You take returns from the future and bring them to the present, and you take tails and push them into the future.",
  "who": "Chris Cole"
 },
 {
  "slug": "cole-small-bets-huge-payoffs",
  "guest": "Chris Cole",
  "date": "2016-11-29",
  "title": "Small Bets, Huge Payoffs",
  "q": "Dennis Rodman is 6 standard deviations away from the mean in rebounding. Rodman is better at rebounding than Michael Jordan is at scoring.",
  "who": "Chris Cole"
 },
 {
  "slug": "dixon-the-future-of-tech",
  "guest": "Chris Dixon",
  "date": "2017-12-26",
  "title": "The Future of Tech",
  "q": "No matter how smart people work for you, the smartest people don't work for you.",
  "who": "Bill Joy (cited by Chris)"
 },
 {
  "slug": "dixon-the-future-of-tech",
  "guest": "Chris Dixon",
  "date": "2017-12-26",
  "title": "The Future of Tech",
  "q": "Software is the encoding of human ideas. If you can think it, you can write it.",
  "who": "Chris Dixon"
 },
 {
  "slug": "dixon-the-future-of-tech",
  "guest": "Chris Dixon",
  "date": "2017-12-26",
  "title": "The Future of Tech",
  "q": "Computer science was mis-titled. It should have been called algorithms and network design.",
  "who": "Chris Dixon"
 },
 {
  "slug": "dixon-the-future-of-tech",
  "guest": "Chris Dixon",
  "date": "2017-12-26",
  "title": "The Future of Tech",
  "q": "You have more information than the President did 15 years ago in your pocket.",
  "who": "Chris Dixon"
 },
 {
  "slug": "dorsey-buying-companies-with-economic-moats",
  "guest": "Pat Dorsey",
  "date": "2017-08-22",
  "title": "Buying Companies With Economic Moats",
  "q": "On the sell-side you're paid to say yes. On the buy-side you're paid to say no.",
  "who": "Pat Dorsey"
 },
 {
  "slug": "dorsey-buying-companies-with-economic-moats",
  "guest": "Pat Dorsey",
  "date": "2017-08-22",
  "title": "Buying Companies With Economic Moats",
  "q": "If that brand doesn't translate into pricing power, it's frankly not worth what the company spends to maintain it.",
  "who": "Pat Dorsey"
 },
 {
  "slug": "dorsey-buying-companies-with-economic-moats",
  "guest": "Pat Dorsey",
  "date": "2017-08-22",
  "title": "Buying Companies With Economic Moats",
  "q": "Network effects are great but if they're not monetized they don't mean doodly to an investor.",
  "who": "Pat Dorsey"
 },
 {
  "slug": "dorsey-buying-companies-with-economic-moats",
  "guest": "Pat Dorsey",
  "date": "2017-08-22",
  "title": "Buying Companies With Economic Moats",
  "q": "When you have a decision where there's a giant hue and cry and everyone says 'that's the dumbest thing ever,' it's probably worth a hard look.",
  "who": "Pat Dorsey"
 },
 {
  "slug": "dorsey-buying-companies-with-economic-moats",
  "guest": "Pat Dorsey",
  "date": "2017-08-22",
  "title": "Buying Companies With Economic Moats",
  "q": "Don't have a stock off the shelf answer. Have an answer that's specific to that business and doesn't do things just because other people do them.",
  "who": "Pat Dorsey"
 },
 {
  "slug": "dorsey-the-moat-portfolio",
  "guest": "Pat Dorsey",
  "date": "2018-02-20",
  "title": "The Moat Portfolio",
  "q": "We do not buy 60 cent dollars. You cannot look at a dynamic, growing business as a 60 cent dollar.",
  "who": "Pat"
 },
 {
  "slug": "dorsey-the-moat-portfolio",
  "guest": "Pat Dorsey",
  "date": "2018-02-20",
  "title": "The Moat Portfolio",
  "q": "A discussion is about seeking the truth.",
  "who": "Ray Dalio"
 },
 {
  "slug": "dorsey-the-moat-portfolio",
  "guest": "Pat Dorsey",
  "date": "2018-02-20",
  "title": "The Moat Portfolio",
  "q": "Neither is good or bad—craftsmanship versus manufacturing require different skills and different structures.",
  "who": "Pat"
 },
 {
  "slug": "douvos-a-value-investor-lost-in-the-valley",
  "guest": "Chris Douvos",
  "date": "2018-05-01",
  "title": "A Value Investor Lost in the Valley",
  "q": "If you're afraid of being wrong and alone, you'll never be right and alone.",
  "who": "David Salem (referenced)"
 },
 {
  "slug": "douvos-a-value-investor-lost-in-the-valley",
  "guest": "Chris Douvos",
  "date": "2018-05-01",
  "title": "A Value Investor Lost in the Valley",
  "q": "The innovators are followed by the imitators, who are followed by the idiots.",
  "who": "Buffett (via Chris)"
 },
 {
  "slug": "douvos-a-value-investor-lost-in-the-valley",
  "guest": "Chris Douvos",
  "date": "2018-05-01",
  "title": "A Value Investor Lost in the Valley",
  "q": "It always matters in the end.",
  "who": "Chris Douvos"
 },
 {
  "slug": "douvos-a-value-investor-lost-in-the-valley",
  "guest": "Chris Douvos",
  "date": "2018-05-01",
  "title": "A Value Investor Lost in the Valley",
  "q": "Don't try this at home.",
  "who": "Chris Douvos"
 },
 {
  "slug": "drogen-quant-vs-traditional-investors-and-how-alphas-become-betas",
  "guest": "Leigh Drogen",
  "date": "2017-06-13",
  "title": "Quant vs. Traditional Investors and How Alphas Become Betas",
  "q": "They're just simply opting out because of it.",
  "who": "Leigh"
 },
 {
  "slug": "drogen-quant-vs-traditional-investors-and-how-alphas-become-betas",
  "guest": "Leigh Drogen",
  "date": "2017-06-13",
  "title": "Quant vs. Traditional Investors and How Alphas Become Betas",
  "q": "So actually my educational background is in behavioral economics and war theory.",
  "who": "Leigh"
 },
 {
  "slug": "drogen-quant-vs-traditional-investors-and-how-alphas-become-betas",
  "guest": "Leigh Drogen",
  "date": "2017-06-13",
  "title": "Quant vs. Traditional Investors and How Alphas Become Betas",
  "q": "So this was crazy.",
  "who": "Leigh"
 },
 {
  "slug": "drogen-quant-vs-traditional-investors-and-how-alphas-become-betas",
  "guest": "Leigh Drogen",
  "date": "2017-06-13",
  "title": "Quant vs. Traditional Investors and How Alphas Become Betas",
  "q": "Yeah. I think the informational edge is becoming more arbitrage these days.",
  "who": "Leigh"
 },
 {
  "slug": "drogen-sink-or-swim-how-to-combine-quant-and-traditional-asset-management-techniques",
  "guest": "Leigh Drogen",
  "date": "2017-08-01",
  "title": "Sink or Swim: How to Combine Quant and Traditional Asset Management Techniques",
  "q": "If you can get your mindset wrapped around simple systems of measurement and be curious about what's predictive, you'll be surprised often.",
  "who": "Leigh Drogen"
 },
 {
  "slug": "drogen-sink-or-swim-how-to-combine-quant-and-traditional-asset-management-techniques",
  "guest": "Leigh Drogen",
  "date": "2017-08-01",
  "title": "Sink or Swim: How to Combine Quant and Traditional Asset Management Techniques",
  "q": "Traditional managers can compete with quants by combining the best of both worlds.",
  "who": "Leigh Drogen"
 },
 {
  "slug": "egan-designing-better-decisions",
  "guest": "Dan Egan",
  "date": "2017-01-03",
  "title": "Designing Better Decisions",
  "q": "What if we changed this one thing? How does that reveal what's really going on?",
  "who": "Dan Egan"
 },
 {
  "slug": "egan-designing-better-decisions",
  "guest": "Dan Egan",
  "date": "2017-01-03",
  "title": "Designing Better Decisions",
  "q": "The best way to predict the future is to build it.",
  "who": "Abraham Lincoln (via Dan Egan)"
 },
 {
  "slug": "egan-designing-better-decisions",
  "guest": "Dan Egan",
  "date": "2017-01-03",
  "title": "Designing Better Decisions",
  "q": "Never compete against somebody who enjoys what they're doing more than you.",
  "who": "Dan Egan"
 },
 {
  "slug": "egan-designing-better-decisions",
  "guest": "Dan Egan",
  "date": "2017-01-03",
  "title": "Designing Better Decisions",
  "q": "Money is a symptom of poverty.",
  "who": "Ian M. Banks (via Dan Egan)"
 },
 {
  "slug": "ehrsam-hash-power-part-3",
  "guest": "Fred Ehrsam & multiple guests (Olaf Carlson-Wee, Naval Ravikant, Peter Van Valkenburgh, Juan Benet, Muneeb Ali)",
  "date": "2017-10-10",
  "title": "Hash Power - Part 3",
  "q": "Individual reputation ends up being very important relative to your positioning in online communities.",
  "who": "Olaf Carlson-Wee"
 },
 {
  "slug": "ehrsam-hash-power-part-3",
  "guest": "Fred Ehrsam & multiple guests (Olaf Carlson-Wee, Naval Ravikant, Peter Van Valkenburgh, Juan Benet, Muneeb Ali)",
  "date": "2017-10-10",
  "title": "Hash Power - Part 3",
  "q": "Market structure is the highest point of leverage; it determines the behavior that emerges.",
  "who": "Fred Ehrsam"
 },
 {
  "slug": "ehrsam-hash-power-part-3",
  "guest": "Fred Ehrsam & multiple guests (Olaf Carlson-Wee, Naval Ravikant, Peter Van Valkenburgh, Juan Benet, Muneeb Ali)",
  "date": "2017-10-10",
  "title": "Hash Power - Part 3",
  "q": "If I can train you, you're replaceable. If you're a genius, I have to pay what you're worth.",
  "who": "Naval Ravikant"
 },
 {
  "slug": "ehrsam-hash-power-part-3",
  "guest": "Fred Ehrsam & multiple guests (Olaf Carlson-Wee, Naval Ravikant, Peter Van Valkenburgh, Juan Benet, Muneeb Ali)",
  "date": "2017-10-10",
  "title": "Hash Power - Part 3",
  "q": "The code is working for me while I'm not; that's permissionless leverage.",
  "who": "Naval Ravikant"
 },
 {
  "slug": "ehrsam-hash-power-part-3",
  "guest": "Fred Ehrsam & multiple guests (Olaf Carlson-Wee, Naval Ravikant, Peter Van Valkenburgh, Juan Benet, Muneeb Ali)",
  "date": "2017-10-10",
  "title": "Hash Power - Part 3",
  "q": "We will live in a blockchain-based reality in one form or another.",
  "who": "Fred Ehrsam"
 },
 {
  "slug": "faber-factors-dividends-and-angel-investing",
  "guest": "Meb Faber",
  "date": "2017-09-07",
  "title": "Factors, Dividends, and Angel Investing",
  "q": "I'm just happy if I get U.S. stock returns for the next decade in this angel investing.",
  "who": "Meb"
 },
 {
  "slug": "faber-factors-dividends-and-angel-investing",
  "guest": "Meb Faber",
  "date": "2017-09-07",
  "title": "Factors, Dividends, and Angel Investing",
  "q": "Illiquidity is a massive, massive positive—it forces thoughtful entry and prevents daily mark-to-market panic selling.",
  "who": "Meb"
 },
 {
  "slug": "faber-factors-dividends-and-angel-investing",
  "guest": "Meb Faber",
  "date": "2017-09-07",
  "title": "Factors, Dividends, and Angel Investing",
  "q": "Why would you invest in a mutual fund manager who has less than $100,000 invested in their own fund?",
  "who": "Meb"
 },
 {
  "slug": "faber-factors-dividends-and-angel-investing",
  "guest": "Meb Faber",
  "date": "2017-09-07",
  "title": "Factors, Dividends, and Angel Investing",
  "q": "The biggest problem with ETFs is daily liquidity—I wish they traded once at the end of the day.",
  "who": "Meb"
 },
 {
  "slug": "foer-world-without-mind",
  "guest": "Franklin Foer",
  "date": "2017-12-12",
  "title": "World Without Mind",
  "q": "The idea that we could live in a world without gatekeepers is just an illusion. There's always power.",
  "who": "Franklin Foer"
 },
 {
  "slug": "foer-world-without-mind",
  "guest": "Franklin Foer",
  "date": "2017-12-12",
  "title": "World Without Mind",
  "q": "Google stands between us and reality in a way that's unprecedented. It picks winners and losers.",
  "who": "Franklin Foer"
 },
 {
  "slug": "foer-world-without-mind",
  "guest": "Franklin Foer",
  "date": "2017-12-12",
  "title": "World Without Mind",
  "q": "Distraction is the fundamental threat to us as spiritual beings.",
  "who": "Franklin Foer"
 },
 {
  "slug": "foer-world-without-mind",
  "guest": "Franklin Foer",
  "date": "2017-12-12",
  "title": "World Without Mind",
  "q": "We need engineers and computer scientists who are also humanists.",
  "who": "Franklin Foer"
 },
 {
  "slug": "ganti-esoteric-assets",
  "guest": "Rishi Ganti",
  "date": "2017-07-18",
  "title": "Esoteric Assets",
  "q": "The minute there are multiple buyers for anything, prices get efficient very quickly.",
  "who": "Rishi"
 },
 {
  "slug": "ganti-esoteric-assets",
  "guest": "Rishi Ganti",
  "date": "2017-07-18",
  "title": "Esoteric Assets",
  "q": "If you even have two bidders in a market, you're squeezing out all the alpha that exists.",
  "who": "Rishi"
 },
 {
  "slug": "ganti-esoteric-assets",
  "guest": "Rishi Ganti",
  "date": "2017-07-18",
  "title": "Esoteric Assets",
  "q": "To avoid a price mechanism, you have to avoid a market.",
  "who": "Rishi"
 },
 {
  "slug": "ganti-esoteric-assets",
  "guest": "Rishi Ganti",
  "date": "2017-07-18",
  "title": "Esoteric Assets",
  "q": "Once you have the x-ray goggles on, the world's so much more vast than what people give it credit for.",
  "who": "Rishi"
 },
 {
  "slug": "gardner-finding-companies-that-break-the-rules",
  "guest": "David Gardner",
  "date": "2017-09-12",
  "title": "Finding Companies That Break the Rules",
  "q": "Winners keep on winning. After a 10% gain, stock likely to gain another 10%, not drop.",
  "who": "David"
 },
 {
  "slug": "gardner-finding-companies-that-break-the-rules",
  "guest": "David Gardner",
  "date": "2017-09-12",
  "title": "Finding Companies That Break the Rules",
  "q": "Buy discipline is what matters. I don't sell—the real edge is holding forever.",
  "who": "David"
 },
 {
  "slug": "gardner-finding-companies-that-break-the-rules",
  "guest": "David Gardner",
  "date": "2017-09-12",
  "title": "Finding Companies That Break the Rules",
  "q": "Character always wins—I deeply respect entrepreneurs who break rules and solve real pain points.",
  "who": "David"
 },
 {
  "slug": "gardner-finding-companies-that-break-the-rules",
  "guest": "David Gardner",
  "date": "2017-09-12",
  "title": "Finding Companies That Break the Rules",
  "q": "Foolishness is not following the rules everyone else follows and getting outsized returns as a consequence.",
  "who": "David"
 },
 {
  "slug": "gramm-activist-investing",
  "guest": "Jeff Gramm",
  "date": "2016-09-11",
  "title": "Activist Investing",
  "q": "Value investing is a nice way of saying very pessimistic outlook.",
  "who": "Jeff Gramm"
 },
 {
  "slug": "gramm-activist-investing",
  "guest": "Jeff Gramm",
  "date": "2016-09-11",
  "title": "Activist Investing",
  "q": "People are self-interested animals.",
  "who": "Jeff Gramm"
 },
 {
  "slug": "gramm-activist-investing",
  "guest": "Jeff Gramm",
  "date": "2016-09-11",
  "title": "Activist Investing",
  "q": "Great capital allocation is so rare. It can be hard to predict in the future.",
  "who": "Jeff Gramm"
 },
 {
  "slug": "gramm-activist-investing",
  "guest": "Jeff Gramm",
  "date": "2016-09-11",
  "title": "Activist Investing",
  "q": "Boards often don't know how to value companies or think about the value of their companies.",
  "who": "Jeff Gramm"
 },
 {
  "slug": "gray-compound-your-face-off",
  "guest": "Wes Gray",
  "date": "2017-07-25",
  "title": "Compound Your Face Off",
  "q": "I just don't trust any humans anymore. Only computers.",
  "who": "Wes Gray"
 },
 {
  "slug": "gray-compound-your-face-off",
  "guest": "Wes Gray",
  "date": "2017-07-25",
  "title": "Compound Your Face Off",
  "q": "I'm not Warren Buffett. I need systems, not to fuck everything up.",
  "who": "Wes Gray"
 },
 {
  "slug": "gray-compound-your-face-off",
  "guest": "Wes Gray",
  "date": "2017-07-25",
  "title": "Compound Your Face Off",
  "q": "The Marine Corps attracts whack jobs like myself.",
  "who": "Wes Gray"
 },
 {
  "slug": "griffin-pulling-the-thread",
  "guest": "Tren Griffin",
  "date": "2018-05-15",
  "title": "Pulling the Thread",
  "q": "You know it when you see it.",
  "who": "Justin Steven (via Tren)"
 },
 {
  "slug": "griffin-pulling-the-thread",
  "guest": "Tren Griffin",
  "date": "2018-05-15",
  "title": "Pulling the Thread",
  "q": "He likes shooting fish in a barrel with a shotgun and a barrel full of fish.",
  "who": "Tren (on Charlie Munger)"
 },
 {
  "slug": "griffin-pulling-the-thread",
  "guest": "Tren Griffin",
  "date": "2018-05-15",
  "title": "Pulling the Thread",
  "q": "I don't think I've ever met anybody you can't learn something from.",
  "who": "Tren Griffin"
 },
 {
  "slug": "griffin-pulling-the-thread",
  "guest": "Tren Griffin",
  "date": "2018-05-15",
  "title": "Pulling the Thread",
  "q": "Every business is a technology business.",
  "who": "Tren Griffin"
 },
 {
  "slug": "hamed-creative-investing",
  "guest": "Ali Hamed",
  "date": "2018-01-09",
  "title": "Creative Investing",
  "q": "Is this a trade or is it a business? If it's a one-off, we won't do it.",
  "who": "Ali Hamed"
 },
 {
  "slug": "hamed-creative-investing",
  "guest": "Ali Hamed",
  "date": "2018-01-09",
  "title": "Creative Investing",
  "q": "I never want to be the guy winning because I have a secret. If you're nervous discussing it, it's not defensible.",
  "who": "Ali Hamed"
 },
 {
  "slug": "hamed-creative-investing",
  "guest": "Ali Hamed",
  "date": "2018-01-09",
  "title": "Creative Investing",
  "q": "Revenue doesn't prove customer value. Proof is whether they come back and finish what they started.",
  "who": "Ali Hamed"
 },
 {
  "slug": "hamed-creative-investing",
  "guest": "Ali Hamed",
  "date": "2018-01-09",
  "title": "Creative Investing",
  "q": "Free media is completely misaligned with its readers. The reader is the product; advertisers are the customer.",
  "who": "Ali Hamed"
 },
 {
  "slug": "higgins-permanent-equity",
  "guest": "Trish & James Higgins",
  "date": "2017-03-14",
  "title": "Permanent Equity",
  "q": "If you own a bait shop by a fishing spot, you earn above-market returns because you're the only game in town.",
  "who": "James Higgins"
 },
 {
  "slug": "higgins-permanent-equity",
  "guest": "Trish & James Higgins",
  "date": "2017-03-14",
  "title": "Permanent Equity",
  "q": "We think of ourselves as sitting at the intersection of investment capital, sellers seeking exits, and entrepreneurial talent.",
  "who": "James Higgins"
 },
 {
  "slug": "higgins-permanent-equity",
  "guest": "Trish & James Higgins",
  "date": "2017-03-14",
  "title": "Permanent Equity",
  "q": "I was not a majority owner of AQR Capital Management.",
  "who": "Trish Higgins"
 },
 {
  "slug": "higgins-retail-contrarians",
  "guest": "Jim Higgins & Tom Digan (with Rick & Joel)",
  "date": "2017-12-19",
  "title": "Retail Contrarians",
  "q": "Retail isn't real estate; retail is a business. Great real estate will always be in demand.",
  "who": "Rick"
 },
 {
  "slug": "higgins-retail-contrarians",
  "guest": "Jim Higgins & Tom Digan (with Rick & Joel)",
  "date": "2017-12-19",
  "title": "Retail Contrarians",
  "q": "It's all about the real estate. We're not afraid to get on a plane to look at the asset.",
  "who": "Joel"
 },
 {
  "slug": "higgins-retail-contrarians",
  "guest": "Jim Higgins & Tom Digan (with Rick & Joel)",
  "date": "2017-12-19",
  "title": "Retail Contrarians",
  "q": "Eventually markets are reasonably efficient, but defining eventually depends on the sector.",
  "who": "Jim Higgins"
 },
 {
  "slug": "higgins-retail-contrarians",
  "guest": "Jim Higgins & Tom Digan (with Rick & Joel)",
  "date": "2017-12-19",
  "title": "Retail Contrarians",
  "q": "Being a specialist is absolutely an advantage when you're trying to extract true alpha.",
  "who": "Jim Higgins"
 },
 {
  "slug": "higgins-retail-contrarians",
  "guest": "Jim Higgins & Tom Digan (with Rick & Joel)",
  "date": "2017-12-19",
  "title": "Retail Contrarians",
  "q": "This is a classic baby thrown out with the bathwater—every retail security got painted with the same brush.",
  "who": "Tom Digan"
 },
 {
  "slug": "hinkie-data-decisions-and-basketball",
  "guest": "Sam Hinkie",
  "date": "2018-05-22",
  "title": "Data, Decisions, and Basketball",
  "q": "We won't wake up in 30 or 40 years and regret that one opportunity we shortcut.",
  "who": "Sam Hinkie"
 },
 {
  "slug": "hinkie-data-decisions-and-basketball",
  "guest": "Sam Hinkie",
  "date": "2018-05-22",
  "title": "Data, Decisions, and Basketball",
  "q": "If you want particular traits in your children, choose them in your spouse.",
  "who": "Sam Hinkie"
 },
 {
  "slug": "hinkie-data-decisions-and-basketball",
  "guest": "Sam Hinkie",
  "date": "2018-05-22",
  "title": "Data, Decisions, and Basketball",
  "q": "A players hire A players and B players hire C players.",
  "who": "Sam Hinkie"
 },
 {
  "slug": "housel-walking-and-thinking",
  "guest": "Morgan Housel",
  "date": "2016-10-04",
  "title": "Walking and Thinking",
  "q": "The odds are this won't work. 1 in 50, that's great. Better than I thought.",
  "who": "Morgan Housel"
 },
 {
  "slug": "housel-walking-and-thinking",
  "guest": "Morgan Housel",
  "date": "2016-10-04",
  "title": "Walking and Thinking",
  "q": "You only think when you walk. I only think when I walk.",
  "who": "Morgan Housel"
 },
 {
  "slug": "housel-walking-and-thinking",
  "guest": "Morgan Housel",
  "date": "2016-10-04",
  "title": "Walking and Thinking",
  "q": "Almost every great investor gets more humble as time goes on.",
  "who": "Morgan Housel"
 },
 {
  "slug": "hunt-the-three-body-portfolio",
  "guest": "Ben Hunt",
  "date": "2018-01-23",
  "title": "The Three Body Portfolio",
  "q": "There is no algorithm. There is no formula.",
  "who": "Ben Hunt (on the three-body problem)"
 },
 {
  "slug": "hunt-the-three-body-portfolio",
  "guest": "Ben Hunt",
  "date": "2018-01-23",
  "title": "The Three Body Portfolio",
  "q": "You always want to live to fight another day in investing because there always is another day.",
  "who": "Ben Hunt"
 },
 {
  "slug": "hunt-the-three-body-portfolio",
  "guest": "Ben Hunt",
  "date": "2018-01-23",
  "title": "The Three Body Portfolio",
  "q": "Alpha is private information, period, full stop.",
  "who": "Ben Hunt"
 },
 {
  "slug": "hunt-the-three-body-portfolio",
  "guest": "Ben Hunt",
  "date": "2018-01-23",
  "title": "The Three Body Portfolio",
  "q": "If the whole system goes down, I'm not going to make any money, right?",
  "who": "Ben Hunt (on personal risk in 2008)"
 },
 {
  "slug": "hunt-the-three-body-portfolio",
  "guest": "Ben Hunt",
  "date": "2018-01-23",
  "title": "The Three Body Portfolio",
  "q": "A fresh egg should be fingernail clean, not industrially scrubbed.",
  "who": "Ben Hunt"
 },
 {
  "slug": "hy-quant-hedge-funds-and-the-fear-of-death",
  "guest": "week is Khe Hy",
  "date": "2017-04-04",
  "title": "Quant Hedge Funds and the Fear of Death",
  "q": "My guest this week is Khe Hy.",
  "who": "week is Khe Hy"
 },
 {
  "slug": "hy-quant-hedge-funds-and-the-fear-of-death",
  "guest": "week is Khe Hy",
  "date": "2017-04-04",
  "title": "Quant Hedge Funds and the Fear of Death",
  "q": "Talk a little bit about the role of evaluating hedge funds.",
  "who": "week is Khe Hy"
 },
 {
  "slug": "hy-quant-hedge-funds-and-the-fear-of-death",
  "guest": "week is Khe Hy",
  "date": "2017-04-04",
  "title": "Quant Hedge Funds and the Fear of Death",
  "q": "I'll mention this kind of slight nuance to maybe color your answer on how you then evaluated the funds.",
  "who": "week is Khe Hy"
 },
 {
  "slug": "hy-quant-hedge-funds-and-the-fear-of-death",
  "guest": "week is Khe Hy",
  "date": "2017-04-04",
  "title": "Quant Hedge Funds and the Fear of Death",
  "q": "We'll mention the incredible rise of quantitative strategies across the investing landscape.",
  "who": "week is Khe Hy"
 },
 {
  "slug": "jones-adventures-in-sports-business-and-investing",
  "guest": "Dhani Jones",
  "date": "2017-11-14",
  "title": "Adventures in Sports, Business, and Investing",
  "q": "Where most people don't go, I go.",
  "who": "Dhani"
 },
 {
  "slug": "jones-adventures-in-sports-business-and-investing",
  "guest": "Dhani Jones",
  "date": "2017-11-14",
  "title": "Adventures in Sports, Business, and Investing",
  "q": "Everybody wants to be the first one, but nobody wants to take a chance.",
  "who": "Dhani"
 },
 {
  "slug": "jones-adventures-in-sports-business-and-investing",
  "guest": "Dhani Jones",
  "date": "2017-11-14",
  "title": "Adventures in Sports, Business, and Investing",
  "q": "When you're early and you're right, you're still wrong.",
  "who": "Dhani"
 },
 {
  "slug": "jones-adventures-in-sports-business-and-investing",
  "guest": "Dhani Jones",
  "date": "2017-11-14",
  "title": "Adventures in Sports, Business, and Investing",
  "q": "I want to live vicariously through you.",
  "who": "Coach Mike Brown"
 },
 {
  "slug": "judelson-bail-street-with-nycs-leading-bail-bondsman",
  "guest": "Ira Judelson",
  "date": "2017-06-06",
  "title": "Bail Street, with NYC's Leading Bail Bondsman",
  "q": "Well, Rao's is obviously the eatery in Harlem that you can't get a table, there's no reservation.",
  "who": "Ira"
 },
 {
  "slug": "judelson-bail-street-with-nycs-leading-bail-bondsman",
  "guest": "Ira Judelson",
  "date": "2017-06-06",
  "title": "Bail Street, with NYC's Leading Bail Bondsman",
  "q": "There's a lot of very strong people that go there.",
  "who": "Ira"
 },
 {
  "slug": "judelson-bail-street-with-nycs-leading-bail-bondsman",
  "guest": "Ira Judelson",
  "date": "2017-06-06",
  "title": "Bail Street, with NYC's Leading Bail Bondsman",
  "q": "I was in business. I was in business. Oh God, I can't even remember.",
  "who": "Ira"
 },
 {
  "slug": "judelson-bail-street-with-nycs-leading-bail-bondsman",
  "guest": "Ira Judelson",
  "date": "2017-06-06",
  "title": "Bail Street, with NYC's Leading Bail Bondsman",
  "q": "But I did get the defendant. We did actually get him.",
  "who": "Ira"
 },
 {
  "slug": "kalghatgi-moonshot-investing",
  "guest": "Nikhil Kalghatgi",
  "date": "2018-04-09",
  "title": "Moonshot Investing",
  "q": "Moonshot is really an investment strategy, not like a sector.",
  "who": "Nikhil Kalghatgi"
 },
 {
  "slug": "kalghatgi-moonshot-investing",
  "guest": "Nikhil Kalghatgi",
  "date": "2018-04-09",
  "title": "Moonshot Investing",
  "q": "The best gift you can give to an entrepreneur is to expand their mind and their goals.",
  "who": "Nikhil Kalghatgi"
 },
 {
  "slug": "kalghatgi-moonshot-investing",
  "guest": "Nikhil Kalghatgi",
  "date": "2018-04-09",
  "title": "Moonshot Investing",
  "q": "Manufacturing serendipity: figure out what your passions are and what you're really great at—then systematize it.",
  "who": "Nikhil Kalghatgi"
 },
 {
  "slug": "kalghatgi-moonshot-investing",
  "guest": "Nikhil Kalghatgi",
  "date": "2018-04-09",
  "title": "Moonshot Investing",
  "q": "Can you curate experiences? That's a much trickier leveling up of events.",
  "who": "Nikhil Kalghatgi"
 },
 {
  "slug": "karp-opportunities-in-public-and-private-markets",
  "guest": "Jason Karp",
  "date": "2018-05-08",
  "title": "Opportunities in Public and Private Markets",
  "q": "You can't mess it up.",
  "who": "Jason Karp"
 },
 {
  "slug": "karp-opportunities-in-public-and-private-markets",
  "guest": "Jason Karp",
  "date": "2018-05-08",
  "title": "Opportunities in Public and Private Markets",
  "q": "All crypto is greater fool theory.",
  "who": "Jason Karp"
 },
 {
  "slug": "karp-opportunities-in-public-and-private-markets",
  "guest": "Jason Karp",
  "date": "2018-05-08",
  "title": "Opportunities in Public and Private Markets",
  "q": "If your cash flows are actually growing, you could be wrong on valuation by a lot and still win.",
  "who": "Jason Karp"
 },
 {
  "slug": "katsuyama-what-happens-when-you-hit-buy",
  "guest": "Brad Katsuyama",
  "date": "2017-10-31",
  "title": "What Happens When You Hit Buy",
  "q": "Someone wanted to buy shares because I wanted to.",
  "who": "Brad"
 },
 {
  "slug": "katsuyama-what-happens-when-you-hit-buy",
  "guest": "Brad Katsuyama",
  "date": "2017-10-31",
  "title": "What Happens When You Hit Buy",
  "q": "Exchanges are selling advantages, selling tiers of access, not creating fair markets.",
  "who": "Brad"
 },
 {
  "slug": "katsuyama-what-happens-when-you-hit-buy",
  "guest": "Brad Katsuyama",
  "date": "2017-10-31",
  "title": "What Happens When You Hit Buy",
  "q": "We're patching holes that prevent people from extracting rents where they shouldn't be.",
  "who": "Brad"
 },
 {
  "slug": "katsuyama-what-happens-when-you-hit-buy",
  "guest": "Brad Katsuyama",
  "date": "2017-10-31",
  "title": "What Happens When You Hit Buy",
  "q": "What made you good at 10 people might not make you good at 100 or 1000.",
  "who": "Brad"
 },
 {
  "slug": "koppelman-chasing-curiosity",
  "guest": "Brian Koppelman",
  "date": "2017-01-24",
  "title": "Chasing Curiosity",
  "q": "I don't change things when they're still working. That's your move.",
  "who": "Solitary Man character (quoted)"
 },
 {
  "slug": "koppelman-chasing-curiosity",
  "guest": "Brian Koppelman",
  "date": "2017-01-24",
  "title": "Chasing Curiosity",
  "q": "Humans are happiest when accessing their most creative self.",
  "who": "Brian Koppelman"
 },
 {
  "slug": "koppelman-chasing-curiosity",
  "guest": "Brian Koppelman",
  "date": "2017-01-24",
  "title": "Chasing Curiosity",
  "q": "You overestimate what you accomplish in a year; underestimate what you accomplish in 10.",
  "who": "Tony Robbins (cited)"
 },
 {
  "slug": "koppelman-chasing-curiosity",
  "guest": "Brian Koppelman",
  "date": "2017-01-24",
  "title": "Chasing Curiosity",
  "q": "If I knew the answer, I'd have to stop writing it.",
  "who": "Brian Koppelman"
 },
 {
  "slug": "koppelman-chasing-curiosity",
  "guest": "Brian Koppelman",
  "date": "2017-01-24",
  "title": "Chasing Curiosity",
  "q": "The conscious mind disappears and you enter this alpha state.",
  "who": "Brian Koppelman"
 },
 {
  "slug": "leonard-capital-light-compounders-reinvestment-moats",
  "guest": "Connor Leonard",
  "date": "2017-11-21",
  "title": "Capital Light Compounders & Reinvestment Moats",
  "q": "The best businesses are a royalty on the growth of others requiring little capital itself.",
  "who": "Charlie Munger"
 },
 {
  "slug": "leonard-capital-light-compounders-reinvestment-moats",
  "guest": "Connor Leonard",
  "date": "2017-11-21",
  "title": "Capital Light Compounders & Reinvestment Moats",
  "q": "There's not a secret publication with all the best ideas; it's reading and filtering hundreds of data points per year.",
  "who": "Connor"
 },
 {
  "slug": "leonard-capital-light-compounders-reinvestment-moats",
  "guest": "Connor Leonard",
  "date": "2017-11-21",
  "title": "Capital Light Compounders & Reinvestment Moats",
  "q": "I love looking at hundreds of companies a year and only pulling the trigger on one.",
  "who": "Connor"
 },
 {
  "slug": "leonard-capital-light-compounders-reinvestment-moats",
  "guest": "Connor Leonard",
  "date": "2017-11-21",
  "title": "Capital Light Compounders & Reinvestment Moats",
  "q": "If you find one of those ideas that is an absolute no-brainer, you can have a concentrated position because if you're right, it'll work out really well.",
  "who": "Connor"
 },
 {
  "slug": "lowin-hash-power-part-1",
  "guest": "Naval Ravikant & contributors",
  "date": "2017-09-26",
  "title": "Hash Power - Part 1",
  "q": "Money is just a ledger of who owes whom. Bitcoin is the first digital ledger nobody can fake.",
  "who": "Naval Ravikant"
 },
 {
  "slug": "lowin-hash-power-part-1",
  "guest": "Naval Ravikant & contributors",
  "date": "2017-09-26",
  "title": "Hash Power - Part 1",
  "q": "Permissionless networks outinnovate permission networks by a factor of 100 or 1,000. It's not even close.",
  "who": "Naval Ravikant"
 },
 {
  "slug": "lowin-hash-power-part-1",
  "guest": "Naval Ravikant & contributors",
  "date": "2017-09-26",
  "title": "Hash Power - Part 1",
  "q": "This happens very slowly until it doesn't. Then it's very sudden, and by the time you see it coming, it's too late.",
  "who": "Olaf Carlson-Wee"
 },
 {
  "slug": "lowin-hash-power-part-1",
  "guest": "Naval Ravikant & contributors",
  "date": "2017-09-26",
  "title": "Hash Power - Part 1",
  "q": "Blockchains give you coins for giving the network what it wants. Society gives you money for giving society what it wants.",
  "who": "Naval Ravikant"
 },
 {
  "slug": "maddox-the-ace-of-spades",
  "guest": "Eric Maddox",
  "date": "2016-12-13",
  "title": "The Ace of Spades",
  "q": "The old technique never got a single prisoner to open up. 4% success rate across military. My method: 65%.",
  "who": "Eric Maddox"
 },
 {
  "slug": "maddox-the-ace-of-spades",
  "guest": "Eric Maddox",
  "date": "2016-12-13",
  "title": "The Ace of Spades",
  "q": "I don't know much about this topic, but here's what I'm reading—join me. That openness changes everything.",
  "who": "Eric Maddox (on teaching approach)"
 },
 {
  "slug": "maddox-the-ace-of-spades",
  "guest": "Eric Maddox",
  "date": "2016-12-13",
  "title": "The Ace of Spades",
  "q": "Charisma is power plus empathy. A great listener is an attractive person. They know when you're listening.",
  "who": "Eric Maddox"
 },
 {
  "slug": "maddox-the-ace-of-spades",
  "guest": "Eric Maddox",
  "date": "2016-12-13",
  "title": "The Ace of Spades",
  "q": "Courage is knowing it's right to help the enemy at the lower level for the larger strategic mission, even when your soldiers hate it.",
  "who": "Eric Maddox (paraphrasing his Delta commander)"
 },
 {
  "slug": "maloley-ladder-the-fitness-marketplace",
  "guest": "Brett Maloley",
  "date": "2017-10-24",
  "title": "Ladder: The Fitness Marketplace",
  "q": "Business isn't personal, but it's so personal. Rejection is someone saying they don't believe in you.",
  "who": "Brett Maloley"
 },
 {
  "slug": "maloley-ladder-the-fitness-marketplace",
  "guest": "Brett Maloley",
  "date": "2017-10-24",
  "title": "Ladder: The Fitness Marketplace",
  "q": "Brand is arguably the most important and most difficult to create aspect of any business.",
  "who": "Brett Maloley"
 },
 {
  "slug": "maloley-ladder-the-fitness-marketplace",
  "guest": "Brett Maloley",
  "date": "2017-10-24",
  "title": "Ladder: The Fitness Marketplace",
  "q": "Platform business models don't work unless you have real massive scale for network effects.",
  "who": "Brett Maloley"
 },
 {
  "slug": "maloley-ladder-the-fitness-marketplace",
  "guest": "Brett Maloley",
  "date": "2017-10-24",
  "title": "Ladder: The Fitness Marketplace",
  "q": "This will always be probably the most special part of the company, no matter how big it gets.",
  "who": "Brett Maloley"
 },
 {
  "slug": "maloley-shark-tank-with-thatcher-bell-and-taylor-greene",
  "guest": "Brett Hoover & Taylor Greene (Ladder deep-dive)",
  "date": "2018-04-17",
  "title": "Shark Tank with Thatcher Bell and Taylor Greene",
  "q": "Build for the people that really need it—the 85% of the market that's exponentially bigger and growing, not just Peloton 2.0.",
  "who": "Brett Hoover"
 },
 {
  "slug": "maloley-shark-tank-with-thatcher-bell-and-taylor-greene",
  "guest": "Brett Hoover & Taylor Greene (Ladder deep-dive)",
  "date": "2018-04-17",
  "title": "Shark Tank with Thatcher Bell and Taylor Greene",
  "q": "I'm looking for the irrational person motivated by something beyond money, driven by mission and personal experience—those are the ones who change the world and drive the biggest returns.",
  "who": "Taylor Greene"
 },
 {
  "slug": "maloley-shark-tank-with-thatcher-bell-and-taylor-greene",
  "guest": "Brett Hoover & Taylor Greene (Ladder deep-dive)",
  "date": "2018-04-17",
  "title": "Shark Tank with Thatcher Bell and Taylor Greene",
  "q": "Treat VCs like kindergarteners—you have 30 seconds to make or break the pitch. Problem, solution, you.",
  "who": "Taylor Greene"
 },
 {
  "slug": "maloley-shark-tank-with-thatcher-bell-and-taylor-greene",
  "guest": "Brett Hoover & Taylor Greene (Ladder deep-dive)",
  "date": "2018-04-17",
  "title": "Shark Tank with Thatcher Bell and Taylor Greene",
  "q": "The incumbent industry stopped selling health and started selling memberships. This can't go on forever.",
  "who": "Brett Hoover"
 },
 {
  "slug": "mansueto-lessons-from-the-founder-of-morningstar",
  "guest": "Joe Mansueto",
  "date": "2017-02-07",
  "title": "Lessons From the Founder of Morningstar",
  "q": "The sun is but a morning star. No matter where you are, you're still a rising sun.",
  "who": "Joe"
 },
 {
  "slug": "mansueto-lessons-from-the-founder-of-morningstar",
  "guest": "Joe Mansueto",
  "date": "2017-02-07",
  "title": "Lessons From the Founder of Morningstar",
  "q": "We wanted to give individual investors tools to analyze stocks like professionals would.",
  "who": "Joe"
 },
 {
  "slug": "mansueto-lessons-from-the-founder-of-morningstar",
  "guest": "Joe Mansueto",
  "date": "2017-02-07",
  "title": "Lessons From the Founder of Morningstar",
  "q": "Learn to say no and don't try to satisfy all comers.",
  "who": "Joe"
 },
 {
  "slug": "mauboussin-active-asset-management",
  "guest": "Michael Mauboussin",
  "date": "2016-09-20",
  "title": "Active Asset Management",
  "q": "A great client is one who cashes a check when we hand it to him and writes us a check when we ask.",
  "who": "Michael Mauboussin"
 },
 {
  "slug": "mauboussin-active-asset-management",
  "guest": "Michael Mauboussin",
  "date": "2016-09-20",
  "title": "Active Asset Management",
  "q": "Skill is analytical skills and managing behavioral issues; portfolio construction is managing and mitigating behavioral problems.",
  "who": "Michael Mauboussin"
 },
 {
  "slug": "mauboussin-active-asset-management",
  "guest": "Michael Mauboussin",
  "date": "2016-09-20",
  "title": "Active Asset Management",
  "q": "For stock to go up, you must do better than what the market already expects.",
  "who": "Michael Mauboussin"
 },
 {
  "slug": "mauboussin-active-asset-management",
  "guest": "Michael Mauboussin",
  "date": "2016-09-20",
  "title": "Active Asset Management",
  "q": "Articles about buybacks by journalists are drivel—not informed or thoughtful.",
  "who": "Michael Mauboussin"
 },
 {
  "slug": "mauboussin-man-machine-moats-and-power-of-the-outside-view",
  "guest": "Michael Mauboussin",
  "date": "2017-05-16",
  "title": "Man + Machine, Moats, and Power of the Outside View",
  "q": "Markets have to be efficiently inefficient.",
  "who": "Michael Mauboussin"
 },
 {
  "slug": "mauboussin-man-machine-moats-and-power-of-the-outside-view",
  "guest": "Michael Mauboussin",
  "date": "2017-05-16",
  "title": "Man + Machine, Moats, and Power of the Outside View",
  "q": "If you want lots of liquidity, you should realize you're not going to have a lot of control.",
  "who": "Michael Mauboussin"
 },
 {
  "slug": "mauboussin-man-machine-moats-and-power-of-the-outside-view",
  "guest": "Michael Mauboussin",
  "date": "2017-05-16",
  "title": "Man + Machine, Moats, and Power of the Outside View",
  "q": "You haven't accomplished anything until you're liquid.",
  "who": "Bill Gurley (cited by Mauboussin)"
 },
 {
  "slug": "mauboussin-man-machine-moats-and-power-of-the-outside-view",
  "guest": "Michael Mauboussin",
  "date": "2017-05-16",
  "title": "Man + Machine, Moats, and Power of the Outside View",
  "q": "Pre-IPO is the new IPO.",
  "who": "Fidelity executive (cited by Mauboussin)"
 },
 {
  "slug": "moazed-building-modern-monopolies",
  "guest": "Alex Moazed",
  "date": "2017-02-21",
  "title": "Building Modern Monopolies",
  "q": "Software alone is a commodity. The value is in the ecosystem.",
  "who": "Alex Moazed"
 },
 {
  "slug": "moazed-building-modern-monopolies",
  "guest": "Alex Moazed",
  "date": "2017-02-21",
  "title": "Building Modern Monopolies",
  "q": "A lot of the things you're doing in the beginning don't scale at all.",
  "who": "Alex Moazed"
 },
 {
  "slug": "moazed-building-modern-monopolies",
  "guest": "Alex Moazed",
  "date": "2017-02-21",
  "title": "Building Modern Monopolies",
  "q": "You just focus on having equipment ready, I'm going to get you customers.",
  "who": "Alex Moazed"
 },
 {
  "slug": "moazed-building-modern-monopolies",
  "guest": "Alex Moazed",
  "date": "2017-02-21",
  "title": "Building Modern Monopolies",
  "q": "Complex systems that work result from simple systems scaled, not systems designed and dropped in.",
  "who": "Patrick O'Shaughnessy"
 },
 {
  "slug": "moses-the-big-short-and-beyond",
  "guest": "Danny Moses",
  "date": "2017-04-25",
  "title": "The Big Short and Beyond",
  "q": "No trade is as good as it appears. Leverage will always bury you in the end if you have the wrong trade on.",
  "who": "Danny"
 },
 {
  "slug": "moses-the-big-short-and-beyond",
  "guest": "Danny Moses",
  "date": "2017-04-25",
  "title": "The Big Short and Beyond",
  "q": "If you don't underwrite correctly, then it's over. It doesn't matter what you're lending in.",
  "who": "Danny"
 },
 {
  "slug": "moses-the-big-short-and-beyond",
  "guest": "Danny Moses",
  "date": "2017-04-25",
  "title": "The Big Short and Beyond",
  "q": "You're better off knowing what ETF owns your stock than what the company even does. That's scary to me.",
  "who": "Danny"
 },
 {
  "slug": "neumann-the-deployment-age-power-laws-and-venture-capital",
  "guest": "Jerry Neumann",
  "date": "2017-07-11",
  "title": "The Deployment Age, Power Laws, and Venture Capital",
  "q": "People have really bad instincts about what things are going to work.",
  "who": "Jerry Neumann"
 },
 {
  "slug": "neumann-the-deployment-age-power-laws-and-venture-capital",
  "guest": "Jerry Neumann",
  "date": "2017-07-11",
  "title": "The Deployment Age, Power Laws, and Venture Capital",
  "q": "Risk is predictable, uncertainty you can't insure because you don't know the probability distribution.",
  "who": "Jerry Neumann"
 },
 {
  "slug": "neumann-the-deployment-age-power-laws-and-venture-capital",
  "guest": "Jerry Neumann",
  "date": "2017-07-11",
  "title": "The Deployment Age, Power Laws, and Venture Capital",
  "q": "If there was a recipe for building successful billion-dollar companies, you'd have factories churning them out.",
  "who": "Jerry Neumann"
 },
 {
  "slug": "neumann-the-deployment-age-power-laws-and-venture-capital",
  "guest": "Jerry Neumann",
  "date": "2017-07-11",
  "title": "The Deployment Age, Power Laws, and Venture Capital",
  "q": "I always have to sleep on it because the next day you've calmed down and ask if it's still a great idea.",
  "who": "Jerry Neumann"
 },
 {
  "slug": "norton-seek-to-learn-that-which-cannot-be-taught",
  "guest": "Scott Norton",
  "date": "2017-06-27",
  "title": "Seek to Learn That Which Cannot be Taught",
  "q": "Seek to learn that which cannot be taught.",
  "who": "Scott Norton"
 },
 {
  "slug": "norton-seek-to-learn-that-which-cannot-be-taught",
  "guest": "Scott Norton",
  "date": "2017-06-27",
  "title": "Seek to Learn That Which Cannot be Taught",
  "q": "Business is fundamentally creative, not competitive.",
  "who": "Scott Norton"
 },
 {
  "slug": "norton-seek-to-learn-that-which-cannot-be-taught",
  "guest": "Scott Norton",
  "date": "2017-06-27",
  "title": "Seek to Learn That Which Cannot be Taught",
  "q": "If you want to be successful, don't be a go getter, be a go giver.",
  "who": "Scott Norton (quoting his grandfather)"
 },
 {
  "slug": "norton-seek-to-learn-that-which-cannot-be-taught",
  "guest": "Scott Norton",
  "date": "2017-06-27",
  "title": "Seek to Learn That Which Cannot be Taught",
  "q": "When you're in the unknown, you start to be at home with the world.",
  "who": "Scott Norton"
 },
 {
  "slug": "oshaughnessy-premeditated-success",
  "guest": "Jim O'Shaughnessy",
  "date": "2017-03-21",
  "title": "Premeditated Success",
  "q": "Spend two weeks managing cash flow of a small business—suddenly you understand why the cash flow statement matters.",
  "who": "Jim O'Shaughnessy"
 },
 {
  "slug": "oshaughnessy-premeditated-success",
  "guest": "Jim O'Shaughnessy",
  "date": "2017-03-21",
  "title": "Premeditated Success",
  "q": "The harder I work, the luckier I get.",
  "who": "Jim O'Shaughnessy"
 },
 {
  "slug": "oshaughnessy-premeditated-success",
  "guest": "Jim O'Shaughnessy",
  "date": "2017-03-21",
  "title": "Premeditated Success",
  "q": "Luck is the hand you're dealt. Talent and achievement is how you play that hand.",
  "who": "Jim O'Shaughnessy"
 },
 {
  "slug": "oshaughnessy-premeditated-success",
  "guest": "Jim O'Shaughnessy",
  "date": "2017-03-21",
  "title": "Premeditated Success",
  "q": "I know when I enter your office to ask something, I'm fairly certain what your answer will be, but I have to ask anyway.",
  "who": "Chris Loveless (O'Shaughnessy's president)"
 },
 {
  "slug": "oshaughnessy-ten-lessons-after-almost-a-year-of-podcasting",
  "guest": "Patrick O'Shaughnessy (solo episode)",
  "date": "2017-07-05",
  "title": "Ten Lessons After Almost a Year of Podcasting",
  "q": "Conversation is my new favorite way to learn.",
  "who": "Patrick O'Shaughnessy"
 },
 {
  "slug": "oshaughnessy-ten-lessons-after-almost-a-year-of-podcasting",
  "guest": "Patrick O'Shaughnessy (solo episode)",
  "date": "2017-07-05",
  "title": "Ten Lessons After Almost a Year of Podcasting",
  "q": "The less your ego gets involved, the more you will learn.",
  "who": "Patrick O'Shaughnessy"
 },
 {
  "slug": "oshaughnessy-ten-lessons-after-almost-a-year-of-podcasting",
  "guest": "Patrick O'Shaughnessy (solo episode)",
  "date": "2017-07-05",
  "title": "Ten Lessons After Almost a Year of Podcasting",
  "q": "You also get the listeners that you deserve.",
  "who": "Patrick O'Shaughnessy"
 },
 {
  "slug": "oshaughnessy-ten-lessons-after-almost-a-year-of-podcasting",
  "guest": "Patrick O'Shaughnessy (solo episode)",
  "date": "2017-07-05",
  "title": "Ten Lessons After Almost a Year of Podcasting",
  "q": "The means and the end are the same.",
  "who": "Patrick O'Shaughnessy"
 },
 {
  "slug": "parrish-mastering-mental-models",
  "guest": "Shane Parrish",
  "date": "2016-12-27",
  "title": "Mastering Mental Models",
  "q": "The growth mindset is: if I work harder, I can learn how to do it.",
  "who": "Shane Parrish"
 },
 {
  "slug": "parrish-mastering-mental-models",
  "guest": "Shane Parrish",
  "date": "2016-12-27",
  "title": "Mastering Mental Models",
  "q": "Mastering the best of what other people have figured out.",
  "who": "Shane Parrish"
 },
 {
  "slug": "parrish-mastering-mental-models",
  "guest": "Shane Parrish",
  "date": "2016-12-27",
  "title": "Mastering Mental Models",
  "q": "Most of today's bestsellers disappear in 10 years.",
  "who": "Shane Parrish"
 },
 {
  "slug": "parrish-mastering-mental-models",
  "guest": "Shane Parrish",
  "date": "2016-12-27",
  "title": "Mastering Mental Models",
  "q": "You can create more money, but you can't create more time.",
  "who": "Shane Parrish"
 },
 {
  "slug": "pompliano-full-tilt-investing",
  "guest": "Anthony Pompliano",
  "date": "2018-01-30",
  "title": "Full Tilt Investing",
  "q": "I would rather invest in someone who's not as smart but is not going to give up.",
  "who": "Anthony Pompliano"
 },
 {
  "slug": "pompliano-full-tilt-investing",
  "guest": "Anthony Pompliano",
  "date": "2018-01-30",
  "title": "Full Tilt Investing",
  "q": "Computing power is the new steel.",
  "who": "Anthony Pompliano"
 },
 {
  "slug": "pompliano-full-tilt-investing",
  "guest": "Anthony Pompliano",
  "date": "2018-01-30",
  "title": "Full Tilt Investing",
  "q": "Saturdays Are For The Boys has permeated society.",
  "who": "Anthony Pompliano (on Barstool's cultural impact)"
 },
 {
  "slug": "pompliano-full-tilt-investing",
  "guest": "Anthony Pompliano",
  "date": "2018-01-30",
  "title": "Full Tilt Investing",
  "q": "Power in today's world is who can drive eyeballs and have their audience fulfill call to actions.",
  "who": "Anthony Pompliano"
 },
 {
  "slug": "ptak-the-prospects-for-active-management",
  "guest": "Jeff Ptak",
  "date": "2016-12-20",
  "title": "The Prospects for Active Management",
  "q": "The cheapest quintile are 3x as likely to survive than the most expensive quintile.",
  "who": "Jeff Ptak"
 },
 {
  "slug": "ptak-the-prospects-for-active-management",
  "guest": "Jeff Ptak",
  "date": "2016-12-20",
  "title": "The Prospects for Active Management",
  "q": "It's not the action that's important. In many cases, it's inaction.",
  "who": "Jeff Ptak"
 },
 {
  "slug": "ptak-the-prospects-for-active-management",
  "guest": "Jeff Ptak",
  "date": "2016-12-20",
  "title": "The Prospects for Active Management",
  "q": "Unless they're willing to do the work, they should index.",
  "who": "Jeff Ptak"
 },
 {
  "slug": "ptak-the-prospects-for-active-management",
  "guest": "Jeff Ptak",
  "date": "2016-12-20",
  "title": "The Prospects for Active Management",
  "q": "Winners very often don't look like winners for long stretches.",
  "who": "Jeff Ptak"
 },
 {
  "slug": "rachleff-building-something-people-want-to-buy",
  "guest": "Andy Rachleff",
  "date": "2017-06-20",
  "title": "Building Something People Want to Buy",
  "q": "He is the oldest.",
  "who": "Andy"
 },
 {
  "slug": "rachleff-building-something-people-want-to-buy",
  "guest": "Andy Rachleff",
  "date": "2017-06-20",
  "title": "Building Something People Want to Buy",
  "q": "We believe in euthanasia, let's put it that way.",
  "who": "Andy"
 },
 {
  "slug": "rachleff-building-something-people-want-to-buy",
  "guest": "Andy Rachleff",
  "date": "2017-06-20",
  "title": "Building Something People Want to Buy",
  "q": "So let me just finish the other point then we'll come back to this.",
  "who": "Andy"
 },
 {
  "slug": "rachleff-building-something-people-want-to-buy",
  "guest": "Andy Rachleff",
  "date": "2017-06-20",
  "title": "Building Something People Want to Buy",
  "q": "... as the internet was taking off.",
  "who": "Andy"
 },
 {
  "slug": "rasmussen-private-equity-returns-in-public-markets",
  "guest": "Dan Rasmussen",
  "date": "2018-02-27",
  "title": "Private Equity Returns in Public Markets",
  "q": "Private equity is a really fascinating world.",
  "who": "Dan Rasmussen"
 },
 {
  "slug": "reece-tim-cooks-dashboard",
  "guest": "Michael Reece",
  "date": "2018-06-12",
  "title": "Tim Cook's Dashboard",
  "q": "If you're really good students, they employ you.",
  "who": "Michael Reece"
 },
 {
  "slug": "reece-tim-cooks-dashboard",
  "guest": "Michael Reece",
  "date": "2018-06-12",
  "title": "Tim Cook's Dashboard",
  "q": "The future is here already. It's just not uniformly distributed.",
  "who": "Michael Reece"
 },
 {
  "slug": "reece-tim-cooks-dashboard",
  "guest": "Michael Reece",
  "date": "2018-06-12",
  "title": "Tim Cook's Dashboard",
  "q": "Data is data. But information is something completely different.",
  "who": "Michael Reece"
 },
 {
  "slug": "reece-tim-cooks-dashboard",
  "guest": "Michael Reece",
  "date": "2018-06-12",
  "title": "Tim Cook's Dashboard",
  "q": "It's much easier to predict the negative side of the distribution than the positive.",
  "who": "Michael Reece"
 },
 {
  "slug": "rogers-slow-and-steady-wins-the-race",
  "guest": "John Rogers",
  "date": "2017-02-28",
  "title": "Slow and Steady Wins the Race",
  "q": "You're one of the rare firms that talks about 3-5-7 year plans, not 3-5-7 month results.",
  "who": "management teams (via John Rogers)"
 },
 {
  "slug": "rogers-slow-and-steady-wins-the-race",
  "guest": "John Rogers",
  "date": "2017-02-28",
  "title": "Slow and Steady Wins the Race",
  "q": "By the time you're 18 or 19, I can't teach you to see.",
  "who": "Coach Pete Carril"
 },
 {
  "slug": "rogers-slow-and-steady-wins-the-race",
  "guest": "John Rogers",
  "date": "2017-02-28",
  "title": "Slow and Steady Wins the Race",
  "q": "The difficulty of executing and thinking independently does allow for the moat.",
  "who": "John Rogers"
 },
 {
  "slug": "rogers-slow-and-steady-wins-the-race",
  "guest": "John Rogers",
  "date": "2017-02-28",
  "title": "Slow and Steady Wins the Race",
  "q": "Where else should I be?",
  "who": "John Rogers (meeting Daniel Kahneman)"
 },
 {
  "slug": "rowley-vanguards-gerry-oreilly-and-jim-rowley",
  "guest": "Gerry O'Reilly & Jim Rowley",
  "date": "2016-10-18",
  "title": "Vanguard's Gerry O'Reilly and Jim Rowley",
  "q": "Only half the dollars can do better than average, no matter what.",
  "who": "Jim Rowley"
 },
 {
  "slug": "rowley-vanguards-gerry-oreilly-and-jim-rowley",
  "guest": "Gerry O'Reilly & Jim Rowley",
  "date": "2016-10-18",
  "title": "Vanguard's Gerry O'Reilly and Jim Rowley",
  "q": "You start every sentence with 'we' not 'I.' That gets noticed.",
  "who": "Jim Rowley"
 },
 {
  "slug": "rowley-vanguards-gerry-oreilly-and-jim-rowley",
  "guest": "Gerry O'Reilly & Jim Rowley",
  "date": "2016-10-18",
  "title": "Vanguard's Gerry O'Reilly and Jim Rowley",
  "q": "The stock-bond decision is the most powerful risk-return decision you can make.",
  "who": "Jim Rowley"
 },
 {
  "slug": "rowley-vanguards-gerry-oreilly-and-jim-rowley",
  "guest": "Gerry O'Reilly & Jim Rowley",
  "date": "2016-10-18",
  "title": "Vanguard's Gerry O'Reilly and Jim Rowley",
  "q": "I look forward to coming in Monday morning. I think I'm in the minority.",
  "who": "Gerry O'Reilly"
 },
 {
  "slug": "rudder-the-quantified-self",
  "guest": "Christian Rudder",
  "date": "2016-10-11",
  "title": "The Quantified Self",
  "q": "Guys basically go after the youngest women period.",
  "who": "Christian Rudder"
 },
 {
  "slug": "rudder-the-quantified-self",
  "guest": "Christian Rudder",
  "date": "2016-10-11",
  "title": "The Quantified Self",
  "q": "What you do with the results of the math, that's by far the hardest part.",
  "who": "Christian Rudder"
 },
 {
  "slug": "rudder-the-quantified-self",
  "guest": "Christian Rudder",
  "date": "2016-10-11",
  "title": "The Quantified Self",
  "q": "Be persistent but don't be too committed to this one idea if people don't like it.",
  "who": "Christian Rudder"
 },
 {
  "slug": "rudder-the-quantified-self",
  "guest": "Christian Rudder",
  "date": "2016-10-11",
  "title": "The Quantified Self",
  "q": "Luck plays a tremendous amount. Things could've gone sideways very easily.",
  "who": "Christian Rudder"
 },
 {
  "slug": "salem-the-art-of-asset-allocation",
  "guest": "David Salem",
  "date": "2017-05-23",
  "title": "The Art of Asset Allocation",
  "q": "Asset allocation is not about math; it's about behavior.",
  "who": "David Salem"
 },
 {
  "slug": "sawikin-emerging-market-opportunities",
  "guest": "Harvey Sawikin",
  "date": "2018-02-06",
  "title": "Emerging Market Opportunities",
  "q": "I was absolutely sure I was going to get rich. I had no doubt.",
  "who": "Harvey"
 },
 {
  "slug": "sawikin-emerging-market-opportunities",
  "guest": "Harvey Sawikin",
  "date": "2018-02-06",
  "title": "Emerging Market Opportunities",
  "q": "The smell of opportunity.",
  "who": "Harvey"
 },
 {
  "slug": "sawikin-emerging-market-opportunities",
  "guest": "Harvey Sawikin",
  "date": "2018-02-06",
  "title": "Emerging Market Opportunities",
  "q": "Your job is to know whether you're in a bull market or bear market and act accordingly.",
  "who": "George Robinson"
 },
 {
  "slug": "sawikin-emerging-market-opportunities",
  "guest": "Harvey Sawikin",
  "date": "2018-02-06",
  "title": "Emerging Market Opportunities",
  "q": "Can it be that Russian steel companies are competing to see who has the best corporate governance?",
  "who": "Harvey"
 },
 {
  "slug": "seides-a-deep-dive-into-hedge-funds",
  "guest": "Ted Seides",
  "date": "2016-10-25",
  "title": "A Deep Dive into Hedge Funds",
  "q": "Be the hero of your own life.",
  "who": "Ted Seides"
 },
 {
  "slug": "seides-a-deep-dive-into-hedge-funds",
  "guest": "Ted Seides",
  "date": "2016-10-25",
  "title": "A Deep Dive into Hedge Funds",
  "q": "It's a people business. Ultimately you're making an assessment of the individual.",
  "who": "Ted Seides"
 },
 {
  "slug": "seides-a-deep-dive-into-hedge-funds",
  "guest": "Ted Seides",
  "date": "2016-10-25",
  "title": "A Deep Dive into Hedge Funds",
  "q": "Yeah, it worked.",
  "who": "John Paulson"
 },
 {
  "slug": "seides-a-deep-dive-into-hedge-funds",
  "guest": "Ted Seides",
  "date": "2016-10-25",
  "title": "A Deep Dive into Hedge Funds",
  "q": "Hedge fund operations are like going to the dentist; investors have zero patience for mistakes.",
  "who": "Ted Seides"
 },
 {
  "slug": "seides-the-bet-with-buffett",
  "guest": "Ted Seides",
  "date": "2017-05-02",
  "title": "The Bet With Buffett",
  "q": "If hedge fund fees were zero, I'd still invest in some and not others. The fee question is secondary to whether they add value.",
  "who": "Ted"
 },
 {
  "slug": "seides-the-bet-with-buffett",
  "guest": "Ted Seides",
  "date": "2017-05-02",
  "title": "The Bet With Buffett",
  "q": "No one has earned the returns of the S&P 500 over this 9.5 years because almost no one has the capacity to suffer through 2008.",
  "who": "Ted"
 },
 {
  "slug": "seides-the-bet-with-buffett",
  "guest": "Ted Seides",
  "date": "2017-05-02",
  "title": "The Bet With Buffett",
  "q": "Warren is the most favorable buyer because he credibly doesn't have to sell. That's a powerful permanent capital advantage.",
  "who": "Ted"
 },
 {
  "slug": "seides-the-future-of-asset-management",
  "guest": "Ted Seides & Brent Beshore",
  "date": "2017-03-28",
  "title": "The Future of Asset Management",
  "q": "Intuition is a finely tuned algorithm rooted in enormous experience. Gather tons of experience, let subconscious process it.",
  "who": "Patrick O'Shaughnessy"
 },
 {
  "slug": "seides-the-future-of-asset-management",
  "guest": "Ted Seides & Brent Beshore",
  "date": "2017-03-28",
  "title": "The Future of Asset Management",
  "q": "Don't build a system unless you absolutely need to. If you do, make it extremely simple and let it evolve.",
  "who": "Ted Seides (recommending Systems Bible)"
 },
 {
  "slug": "seides-the-future-of-asset-management",
  "guest": "Ted Seides & Brent Beshore",
  "date": "2017-03-28",
  "title": "The Future of Asset Management",
  "q": "Most small businesses fail because they won't do the basics—the hygiene. Floors need cleaning, tooth brushes need using.",
  "who": "Brent Beshore"
 },
 {
  "slug": "seides-the-future-of-asset-management",
  "guest": "Ted Seides & Brent Beshore",
  "date": "2017-03-28",
  "title": "The Future of Asset Management",
  "q": "Lunch is not free. Small businesses lack the business fundamentals: where does cash come from, where does it go.",
  "who": "Brent Beshore"
 },
 {
  "slug": "seims-hash-power-part-2",
  "guest": "Olaf Carlson-Wee, Naval Ravikant, Ari Paul & contributors",
  "date": "2017-10-03",
  "title": "Hash Power - Part 2",
  "q": "Ethereum has no revenues. These aren't currencies; they're commodities that actually do something, unlike gold.",
  "who": "Ari Paul"
 },
 {
  "slug": "seims-hash-power-part-2",
  "guest": "Olaf Carlson-Wee, Naval Ravikant, Ari Paul & contributors",
  "date": "2017-10-03",
  "title": "Hash Power - Part 2",
  "q": "When an asset collapses but doesn't die, that tells you something. There's real value to investigate.",
  "who": "Ari Paul"
 },
 {
  "slug": "seims-hash-power-part-2",
  "guest": "Olaf Carlson-Wee, Naval Ravikant, Ari Paul & contributors",
  "date": "2017-10-03",
  "title": "Hash Power - Part 2",
  "q": "Our edge is at the absolutely earliest stage—investing on protocol whitepapers when others can't parse the tech.",
  "who": "Olaf Carlson-Wee"
 },
 {
  "slug": "seims-hash-power-part-2",
  "guest": "Olaf Carlson-Wee, Naval Ravikant, Ari Paul & contributors",
  "date": "2017-10-03",
  "title": "Hash Power - Part 2",
  "q": "Blockchains are the first indication of large-scale AIs bootstrapping themselves. They allocate resources better than any human can explain.",
  "who": "Naval Ravikant"
 },
 {
  "slug": "shapiro-better-for-you-better-for-the-world",
  "guest": "Craig Shapiro",
  "date": "2016-11-14",
  "title": "Better for You, Better for the World",
  "q": "Don't shine the turd - if something goes wrong, tell me immediately.",
  "who": "Anonymous investor to Craig"
 },
 {
  "slug": "shapiro-better-for-you-better-for-the-world",
  "guest": "Craig Shapiro",
  "date": "2016-11-14",
  "title": "Better for You, Better for the World",
  "q": "Businesses balancing profit and social good generate the greatest returns.",
  "who": "Craig Shapiro"
 },
 {
  "slug": "shapiro-better-for-you-better-for-the-world",
  "guest": "Craig Shapiro",
  "date": "2016-11-14",
  "title": "Better for You, Better for the World",
  "q": "Financial markets haven't shifted alongside culture toward stakeholder value.",
  "who": "Craig Shapiro"
 },
 {
  "slug": "shapiro-watching-a-venture-fund-at-work",
  "guest": "Lauren Loktev, Kanyi Maqubela & Craig Shapiro",
  "date": "2017-01-10",
  "title": "Watching a Venture Fund at Work",
  "q": "Investing in assets that don't exist yet requires hands-on work but also deep thematic conviction.",
  "who": "Craig Shapiro"
 },
 {
  "slug": "shapiro-watching-a-venture-fund-at-work",
  "guest": "Lauren Loktev, Kanyi Maqubela & Craig Shapiro",
  "date": "2017-01-10",
  "title": "Watching a Venture Fund at Work",
  "q": "Fundraising is not a business model.",
  "who": "Kanyi Maqubela"
 },
 {
  "slug": "shapiro-watching-a-venture-fund-at-work",
  "guest": "Lauren Loktev, Kanyi Maqubela & Craig Shapiro",
  "date": "2017-01-10",
  "title": "Watching a Venture Fund at Work",
  "q": "Brand is at least to some extent about relationships.",
  "who": "Kanyi Maqubela"
 },
 {
  "slug": "shapiro-watching-a-venture-fund-at-work",
  "guest": "Lauren Loktev, Kanyi Maqubela & Craig Shapiro",
  "date": "2017-01-10",
  "title": "Watching a Venture Fund at Work",
  "q": "The pace at which you uncover unknown unknowns is how you know a founder is really getting deep into their market.",
  "who": "Kanyi Maqubela"
 },
 {
  "slug": "simler-exploring-the-frontier",
  "guest": "Kevin Simler",
  "date": "2016-11-22",
  "title": "Exploring the Frontier",
  "q": "Palantir was and always will be a startup - in my heart.",
  "who": "Kevin Simler"
 },
 {
  "slug": "simler-exploring-the-frontier",
  "guest": "Kevin Simler",
  "date": "2016-11-22",
  "title": "Exploring the Frontier",
  "q": "If you think the world is playful, it's more fun to be in.",
  "who": "Kevin Simler"
 },
 {
  "slug": "simler-exploring-the-frontier",
  "guest": "Kevin Simler",
  "date": "2016-11-22",
  "title": "Exploring the Frontier",
  "q": "The frontier is not synonymous with growth, but highly implicative of it.",
  "who": "Kevin Simler"
 },
 {
  "slug": "simler-exploring-the-frontier",
  "guest": "Kevin Simler",
  "date": "2016-11-22",
  "title": "Exploring the Frontier",
  "q": "Math unlocks the inner workings of the world, but disconnects from what it means to be human.",
  "who": "Kevin Simler"
 },
 {
  "slug": "singh-the-berkshire-of-software",
  "guest": "Savneet Singh",
  "date": "2018-03-06",
  "title": "The Berkshire of Software",
  "q": "It was a really big decision early on to try to be a holding company, not a fund.",
  "who": "Savneet Singh"
 },
 {
  "slug": "stein-the-state-of-automated-investing",
  "guest": "Jon Stein",
  "date": "2016-11-01",
  "title": "The State of Automated Investing",
  "q": "Inertia is our biggest competitor.",
  "who": "Jon Stein"
 },
 {
  "slug": "stein-the-state-of-automated-investing",
  "guest": "Jon Stein",
  "date": "2016-11-01",
  "title": "The State of Automated Investing",
  "q": "It only exists because we say it exists.",
  "who": "Jon Stein"
 },
 {
  "slug": "stein-the-state-of-automated-investing",
  "guest": "Jon Stein",
  "date": "2016-11-01",
  "title": "The State of Automated Investing",
  "q": "We're building an institution, and by that I mean, building for the long term.",
  "who": "Jon Stein"
 },
 {
  "slug": "stein-the-state-of-automated-investing",
  "guest": "Jon Stein",
  "date": "2016-11-01",
  "title": "The State of Automated Investing",
  "q": "You don't rise to the occasion. You resort to your level of training.",
  "who": "Jon Stein"
 },
 {
  "slug": "stulberg-just-manageable-challenges",
  "guest": "Brad Stulberg",
  "date": "2017-08-08",
  "title": "Just Manageable Challenges",
  "q": "You get stronger when you sleep, not at the gym. The gym just tears you down.",
  "who": "Brad Stulberg"
 },
 {
  "slug": "stulberg-just-manageable-challenges",
  "guest": "Brad Stulberg",
  "date": "2017-08-08",
  "title": "Just Manageable Challenges",
  "q": "It's hard to push a highly motivated person to work hard; it's hard to hold them back.",
  "who": "Brad Stulberg"
 },
 {
  "slug": "stulberg-just-manageable-challenges",
  "guest": "Brad Stulberg",
  "date": "2017-08-08",
  "title": "Just Manageable Challenges",
  "q": "They're great because they're humble, not humble because they're great.",
  "who": "Brad Stulberg"
 },
 {
  "slug": "stulberg-just-manageable-challenges",
  "guest": "Brad Stulberg",
  "date": "2017-08-08",
  "title": "Just Manageable Challenges",
  "q": "Fatigue is an emotion, not just a physical state.",
  "who": "Brad Stulberg"
 },
 {
  "slug": "thorndike-how-skilled-capital-allocators-compound-capital",
  "guest": "Will Thorndike",
  "date": "2017-05-09",
  "title": "How Skilled Capital Allocators Compound Capital",
  "q": "If it's becoming popular, it's probably not as good or opportunistic anymore. Once everyone's doing it, the edge is gone.",
  "who": "Henry Singleton (quoted)"
 },
 {
  "slug": "thorndike-how-skilled-capital-allocators-compound-capital",
  "guest": "Will Thorndike",
  "date": "2017-05-09",
  "title": "How Skilled Capital Allocators Compound Capital",
  "q": "We paint the two sides facing the road. Everything else runs lean—no cuts to content, production, or talent that drives ratings.",
  "who": "Tom Murphy (quoted)"
 },
 {
  "slug": "thorndike-how-skilled-capital-allocators-compound-capital",
  "guest": "Will Thorndike",
  "date": "2017-05-09",
  "title": "How Skilled Capital Allocators Compound Capital",
  "q": "You need to show up and steer the ship every day. You can't predict what opportunities will arise, so you must be prepared to react.",
  "who": "Henry Singleton (quoted)"
 },
 {
  "slug": "tisch-tech-investing-outside-of-silicon-valley",
  "guest": "David Tisch",
  "date": "2017-09-19",
  "title": "Tech Investing Outside of Silicon Valley",
  "q": "Companies without a heart are dead.",
  "who": "David Tisch"
 },
 {
  "slug": "tisch-tech-investing-outside-of-silicon-valley",
  "guest": "David Tisch",
  "date": "2017-09-19",
  "title": "Tech Investing Outside of Silicon Valley",
  "q": "An introduction takes eight seconds of my day. If that's my value add, I suck.",
  "who": "David Tisch"
 },
 {
  "slug": "tisch-tech-investing-outside-of-silicon-valley",
  "guest": "David Tisch",
  "date": "2017-09-19",
  "title": "Tech Investing Outside of Silicon Valley",
  "q": "The biggest mistakes are omissions, not losses. I lose sleep over companies I saw and passed on.",
  "who": "David Tisch"
 },
 {
  "slug": "tisch-tech-investing-outside-of-silicon-valley",
  "guest": "David Tisch",
  "date": "2017-09-19",
  "title": "Tech Investing Outside of Silicon Valley",
  "q": "Every company today needs to become a software company. If software doesn't drive your business, you're in trouble.",
  "who": "David Tisch"
 },
 {
  "slug": "tyle-the-future-of-venture-capital",
  "guest": "Sheel Tyle",
  "date": "2018-01-02",
  "title": "The Future of Venture Capital",
  "q": "Talent is universal, but opportunity is not. There's no reason the next Zuckerberg can't be from Africa.",
  "who": "Sheel Tyle"
 },
 {
  "slug": "tyle-the-future-of-venture-capital",
  "guest": "Sheel Tyle",
  "date": "2018-01-02",
  "title": "The Future of Venture Capital",
  "q": "I would much rather invest than take gambles, and ICOs feel like gambles right now.",
  "who": "Sheel Tyle"
 },
 {
  "slug": "tyle-the-future-of-venture-capital",
  "guest": "Sheel Tyle",
  "date": "2018-01-02",
  "title": "The Future of Venture Capital",
  "q": "Nobody had a taxi thesis when investing in Uber. I didn't have a brokerage thesis investing in Robinhood.",
  "who": "Sheel Tyle"
 },
 {
  "slug": "tyle-the-future-of-venture-capital",
  "guest": "Sheel Tyle",
  "date": "2018-01-02",
  "title": "The Future of Venture Capital",
  "q": "If I don't do this ride-along, how am I going to understand what officers and communities actually need?",
  "who": "Mark43 founder (cited by Sheel)"
 },
 {
  "slug": "urban-grand-theft-life",
  "guest": "Tim Urban & Andrew Finn",
  "date": "2017-10-17",
  "title": "Grand Theft Life",
  "q": "The same thing that makes it unscalable also makes it irreplaceable.",
  "who": "Tim Urban"
 },
 {
  "slug": "urban-grand-theft-life",
  "guest": "Tim Urban & Andrew Finn",
  "date": "2017-10-17",
  "title": "Grand Theft Life",
  "q": "Seeing the actual reality for what it is, of danger, of risk, of opportunity, of possibility.",
  "who": "Tim Urban"
 },
 {
  "slug": "urban-grand-theft-life",
  "guest": "Tim Urban & Andrew Finn",
  "date": "2017-10-17",
  "title": "Grand Theft Life",
  "q": "If you're willing to put in that work and create metaphors rather than use them.",
  "who": "Patrick"
 },
 {
  "slug": "urban-grand-theft-life",
  "guest": "Tim Urban & Andrew Finn",
  "date": "2017-10-17",
  "title": "Grand Theft Life",
  "q": "A human brain runs on 20 Watts; the equivalent computer runs on 20 megawatts.",
  "who": "Tim Urban"
 },
 {
  "slug": "urban-grand-theft-life",
  "guest": "Tim Urban & Andrew Finn",
  "date": "2017-10-17",
  "title": "Grand Theft Life",
  "q": "The brain is plastic. Your life experience has literally physically shaped your neural pathways in a unique way.",
  "who": "Tim Urban"
 },
 {
  "slug": "varty-the-art-of-tracking",
  "guest": "Boyd Varty",
  "date": "2017-04-11",
  "title": "The Art of Tracking",
  "q": "This week's episode is the most unique to date.",
  "who": "Boyd Varty"
 },
 {
  "slug": "varty-the-art-of-tracking",
  "guest": "Boyd Varty",
  "date": "2017-04-11",
  "title": "The Art of Tracking",
  "q": "A little bit different experience than my Saturdays going to a soccer game or something like that.",
  "who": "Boyd Varty"
 },
 {
  "slug": "varty-the-art-of-tracking",
  "guest": "Boyd Varty",
  "date": "2017-04-11",
  "title": "The Art of Tracking",
  "q": "Yeah, and it lays a nice foundation for sort of where the psychology of my work has gone.",
  "who": "Boyd Varty"
 },
 {
  "slug": "varty-the-art-of-tracking",
  "guest": "Boyd Varty",
  "date": "2017-04-11",
  "title": "The Art of Tracking",
  "q": "Okay, yeah, that will be a fun jump-off point.",
  "who": "Boyd Varty"
 },
 {
  "slug": "wenger-world-after-capital",
  "guest": "Albert Wenger",
  "date": "2018-03-13",
  "title": "World After Capital",
  "q": "Oh, it's always been the same thing.",
  "who": "Albert Wenger"
 },
 {
  "slug": "wilson-angel-investing-and-trend-spotting",
  "guest": "Joanne Wilson",
  "date": "2017-11-28",
  "title": "Angel Investing and Trend Spotting",
  "q": "I am the new bank.",
  "who": "Joanne Wilson"
 },
 {
  "slug": "wilson-angel-investing-and-trend-spotting",
  "guest": "Joanne Wilson",
  "date": "2017-11-28",
  "title": "Angel Investing and Trend Spotting",
  "q": "Most of them are unemployable.",
  "who": "Joanne Wilson"
 },
 {
  "slug": "wilson-angel-investing-and-trend-spotting",
  "guest": "Joanne Wilson",
  "date": "2017-11-28",
  "title": "Angel Investing and Trend Spotting",
  "q": "You're going to figure it out, no matter what comes your way.",
  "who": "Joanne Wilson"
 },
 {
  "slug": "wilson-angel-investing-and-trend-spotting",
  "guest": "Joanne Wilson",
  "date": "2017-11-28",
  "title": "Angel Investing and Trend Spotting",
  "q": "Every season you're starting from scratch.",
  "who": "Joanne Wilson"
 },
 {
  "slug": "wolfe-this-is-who-you-are-up-against",
  "guest": "Josh Wolfe",
  "date": "2018-02-13",
  "title": "This is Who You Are Up Against",
  "q": "This is who you're up against.",
  "who": "Patrick"
 },
 {
  "slug": "wolfe-this-is-who-you-are-up-against",
  "guest": "Josh Wolfe",
  "date": "2018-02-13",
  "title": "This is Who You Are Up Against",
  "q": "Avoid boring people.",
  "who": "Jim Watson"
 },
 {
  "slug": "wolfe-this-is-who-you-are-up-against",
  "guest": "Josh Wolfe",
  "date": "2018-02-13",
  "title": "This is Who You Are Up Against",
  "q": "10 years to build the rep, 10 seconds to lose it.",
  "who": "Bill Conway"
 },
 {
  "slug": "wolfe-this-is-who-you-are-up-against",
  "guest": "Josh Wolfe",
  "date": "2018-02-13",
  "title": "This is Who You Are Up Against",
  "q": "We want people to agree with us, just later.",
  "who": "Josh"
 },
 {
  "slug": "yudkoff-really-private-equity",
  "guest": "Royce Yudkoff & Rick Ruback",
  "date": "2017-04-18",
  "title": "REALLY Private Equity",
  "q": "This is Royce, I'll take a crack at it.",
  "who": "Royce Yudkoff & Rick Ruback"
 },
 {
  "slug": "yudkoff-really-private-equity",
  "guest": "Royce Yudkoff & Rick Ruback",
  "date": "2017-04-18",
  "title": "REALLY Private Equity",
  "q": "Rick and I see investors doing just one deal.",
  "who": "Royce Yudkoff & Rick Ruback"
 },
 {
  "slug": "yudkoff-really-private-equity",
  "guest": "Royce Yudkoff & Rick Ruback",
  "date": "2017-04-18",
  "title": "REALLY Private Equity",
  "q": "Could you give me a sense of the scale of this?",
  "who": "Royce Yudkoff & Rick Ruback"
 },
 {
  "slug": "yudkoff-really-private-equity",
  "guest": "Royce Yudkoff & Rick Ruback",
  "date": "2017-04-18",
  "title": "REALLY Private Equity",
  "q": "Well, I think we can fairly say that we're the largest because the school is the largest.",
  "who": "Royce Yudkoff & Rick Ruback"
 },
 {
  "slug": "zweig-business-vs-investing",
  "guest": "Morgan Housel & Jason Zweig",
  "date": "2017-08-15",
  "title": "Business vs. Investing",
  "q": "I have no sunk costs. When something doesn't work, I don't fix it or tweak it, I blow it up and start from an empty screen.",
  "who": "Jason Zweig (quoting Danny Kahneman)"
 },
 {
  "slug": "zweig-business-vs-investing",
  "guest": "Morgan Housel & Jason Zweig",
  "date": "2017-08-15",
  "title": "Business vs. Investing",
  "q": "The distinction between giving up and quitting: give up all the time, but never quit the overall mission.",
  "who": "Morgan Housel (quoting Phil Knight)"
 },
 {
  "slug": "zweig-business-vs-investing",
  "guest": "Morgan Housel & Jason Zweig",
  "date": "2017-08-15",
  "title": "Business vs. Investing",
  "q": "No matter how far you've gone down the wrong path, turn back.",
  "who": "Turkish proverb (cited by Patrick)"
 },
 {
  "slug": "zweig-business-vs-investing",
  "guest": "Morgan Housel & Jason Zweig",
  "date": "2017-08-15",
  "title": "Business vs. Investing",
  "q": "If I don't like a book, I just stop immediately. I've stopped reading books after five sentences.",
  "who": "Jason Zweig"
 },
 {
  "slug": "zweig-the-power-of-serendipity",
  "guest": "Jason Zweig",
  "date": "2016-09-27",
  "title": "The Power of Serendipity",
  "q": "You just seemed like the kind of person I should take a chance on.",
  "who": "Jason's early hiring manager"
 },
 {
  "slug": "zweig-the-power-of-serendipity",
  "guest": "Jason Zweig",
  "date": "2016-09-27",
  "title": "The Power of Serendipity",
  "q": "Good financial advisor is worth platinum. Portfolio management is commodity; financial planning is priceless.",
  "who": "Jason Zweig"
 },
 {
  "slug": "zweig-the-power-of-serendipity",
  "guest": "Jason Zweig",
  "date": "2016-09-27",
  "title": "The Power of Serendipity",
  "q": "Serendipity is something you can influence, you can shape. Luck happens to you.",
  "who": "Jason Zweig"
 },
 {
  "slug": "zweig-the-power-of-serendipity",
  "guest": "Jason Zweig",
  "date": "2016-09-27",
  "title": "The Power of Serendipity",
  "q": "Essay means attempt—bounded in expectations. You're making an attempt to make sense of the world, not solve universe.",
  "who": "Jason Zweig (on Montaigne)"
 }
];
