// AUTO-GENERATED by gen_dashboard_data.py — do not edit
/* eslint-disable */
export const QUOTES: any[] = [
 {
  "slug": "adams-an-internal-locus-of-control",
  "guest": "Kiley Adams",
  "date": "2016-10-28",
  "title": "An Internal Locus of Control",
  "q": "I don't remember.",
  "who": "Kiley Adams"
 },
 {
  "slug": "adams-an-internal-locus-of-control",
  "guest": "Kiley Adams",
  "date": "2016-10-28",
  "title": "An Internal Locus of Control",
  "q": "We're going to see if we can sneak you into Myanmar.",
  "who": "Catholic Bishop"
 },
 {
  "slug": "adams-an-internal-locus-of-control",
  "guest": "Kiley Adams",
  "date": "2016-10-28",
  "title": "An Internal Locus of Control",
  "q": "You don't rise to the occasion. You resort to your level of training.",
  "who": "Kiley Adams"
 },
 {
  "slug": "adams-an-internal-locus-of-control",
  "guest": "Kiley Adams",
  "date": "2016-10-28",
  "title": "An Internal Locus of Control",
  "q": "There is no backward. You don't retreat in a battle.",
  "who": "Kiley Adams"
 },
 {
  "slug": "attia-how-to-live-a-longer-higher-quality-life",
  "guest": "Peter Attia, M.D.",
  "date": "2017-03-07",
  "title": "How to Live a Longer, Higher Quality Life",
  "q": "Mastery is my crack. I have to be mastering something.",
  "who": "Peter Attia"
 },
 {
  "slug": "attia-how-to-live-a-longer-higher-quality-life",
  "guest": "Peter Attia, M.D.",
  "date": "2017-03-07",
  "title": "How to Live a Longer, Higher Quality Life",
  "q": "The only thing worth doing in moderation is moderation.",
  "who": "Peter Attia"
 },
 {
  "slug": "attia-how-to-live-a-longer-higher-quality-life",
  "guest": "Peter Attia, M.D.",
  "date": "2017-03-07",
  "title": "How to Live a Longer, Higher Quality Life",
  "q": "I always followed the path of bliss over financial opportunity; compounding wins.",
  "who": "Peter Attia"
 },
 {
  "slug": "attia-how-to-live-a-longer-higher-quality-life",
  "guest": "Peter Attia, M.D.",
  "date": "2017-03-07",
  "title": "How to Live a Longer, Higher Quality Life",
  "q": "Define wealth by great people in your life, not money or success.",
  "who": "Peter Attia"
 },
 {
  "slug": "beshore-cultivating-a-disaster-resistant-compound-interest-machine",
  "guest": "Brent Beshore",
  "date": "2016-11-08",
  "title": "Cultivating a Disaster Resistant, Compound Interest Machine",
  "q": "We buy boring businesses and make them less boring.",
  "who": "Brent Beshore"
 },
 {
  "slug": "beshore-cultivating-a-disaster-resistant-compound-interest-machine",
  "guest": "Brent Beshore",
  "date": "2016-11-08",
  "title": "Cultivating a Disaster Resistant, Compound Interest Machine",
  "q": "Creating a stable company from scratch is like eating glass.",
  "who": "Brent Beshore"
 },
 {
  "slug": "beshore-cultivating-a-disaster-resistant-compound-interest-machine",
  "guest": "Brent Beshore",
  "date": "2016-11-08",
  "title": "Cultivating a Disaster Resistant, Compound Interest Machine",
  "q": "You need people you can cry in front of and be your worst self.",
  "who": "Brent Beshore"
 },
 {
  "slug": "beshore-cultivating-a-disaster-resistant-compound-interest-machine",
  "guest": "Brent Beshore",
  "date": "2016-11-08",
  "title": "Cultivating a Disaster Resistant, Compound Interest Machine",
  "q": "The single biggest determining factor of success is compounding of knowledge.",
  "who": "Brent Beshore"
 },
 {
  "slug": "beshore-private-equity-venture-capital-and-the-future-of-money-management",
  "guest": "Brent Beshore",
  "date": "2017-01-31",
  "title": "Private Equity, Venture Capital, and the Future of Money Management",
  "q": "Most businesses don't get large on purpose because the founder is the moat.",
  "who": "Brent"
 },
 {
  "slug": "beshore-private-equity-venture-capital-and-the-future-of-money-management",
  "guest": "Brent Beshore",
  "date": "2017-01-31",
  "title": "Private Equity, Venture Capital, and the Future of Money Management",
  "q": "Operating a company is like a knife fight; you get out of bed with a knife and try to keep the wild animals away.",
  "who": "Brent"
 },
 {
  "slug": "beshore-private-equity-venture-capital-and-the-future-of-money-management",
  "guest": "Brent Beshore",
  "date": "2017-01-31",
  "title": "Private Equity, Venture Capital, and the Future of Money Management",
  "q": "The biggest secret is there is no secret, you just got to test stuff and see what works.",
  "who": "Brent"
 },
 {
  "slug": "beshore-private-equity-venture-capital-and-the-future-of-money-management",
  "guest": "Brent Beshore",
  "date": "2017-01-31",
  "title": "Private Equity, Venture Capital, and the Future of Money Management",
  "q": "Nothing is worse than claiming one thing and doing something different.",
  "who": "Brent"
 },
 {
  "slug": "beshore-private-equity-venture-capital-and-the-future-of-money-management",
  "guest": "Brent Beshore",
  "date": "2017-01-31",
  "title": "Private Equity, Venture Capital, and the Future of Money Management",
  "q": "Brand is the distribution of likely outcomes that you can expect from any company or person.",
  "who": "Brent"
 },
 {
  "slug": "brown-the-reformation",
  "guest": "Josh Brown",
  "date": "2016-12-06",
  "title": "The Reformation",
  "q": "This isn't Burger King. You cannot have it your way. We decide portfolio after we know your goals.",
  "who": "Josh Brown (paraphrasing Rick Edelman)"
 },
 {
  "slug": "brown-the-reformation",
  "guest": "Josh Brown",
  "date": "2016-12-06",
  "title": "The Reformation",
  "q": "We're glorifying investors at the end of their careers when they're closed and returns are tough. That's like urging people to chase Amazon but not Bezos.",
  "who": "Josh Brown"
 },
 {
  "slug": "brown-the-reformation",
  "guest": "Josh Brown",
  "date": "2016-12-06",
  "title": "The Reformation",
  "q": "If you don't have a process and chase the dream, you're taking risks you don't need to take.",
  "who": "Josh Brown"
 },
 {
  "slug": "brown-the-reformation",
  "guest": "Josh Brown",
  "date": "2016-12-06",
  "title": "The Reformation",
  "q": "Slack is the first technology that creates virtual serendipity across dispersed teams, like cities do for innovation.",
  "who": "Josh Brown"
 },
 {
  "slug": "cassel-investing-in-tiny-stocks",
  "guest": "Ian Cassel",
  "date": "2017-02-14",
  "title": "Investing In Tiny Stocks",
  "q": "An intelligent fanatic is someone with genuine intellectual interest in something.",
  "who": "Ian"
 },
 {
  "slug": "cassel-investing-in-tiny-stocks",
  "guest": "Ian Cassel",
  "date": "2017-02-14",
  "title": "Investing In Tiny Stocks",
  "q": "Most of these companies can't be owned by large institutions because of minimum position sizes.",
  "who": "Ian"
 },
 {
  "slug": "cassel-investing-in-tiny-stocks",
  "guest": "Ian Cassel",
  "date": "2017-02-14",
  "title": "Investing In Tiny Stocks",
  "q": "I'd rather spend time studying the history of great companies when they were small.",
  "who": "Ian"
 },
 {
  "slug": "chilton-the-human-blitzkrieg",
  "guest": "Dave Chilton",
  "date": "2017-05-30",
  "title": "The Human Blitzkrieg",
  "q": "Everywhere I go, people say the book made a difference in their lives.",
  "who": "Dave Chilton"
 },
 {
  "slug": "chilton-the-human-blitzkrieg",
  "guest": "Dave Chilton",
  "date": "2017-05-30",
  "title": "The Human Blitzkrieg",
  "q": "I've never been sued, never sued anybody, never had major conflicts—I just kept it light and loose.",
  "who": "Dave Chilton"
 },
 {
  "slug": "cole-small-bets-huge-payoffs",
  "guest": "Chris Cole",
  "date": "2016-11-29",
  "title": "Small Bets, Huge Payoffs",
  "q": "A black swan is when fear turns to horror. A positive black swan is any surprise non-linear benefit.",
  "who": "Chris Cole"
 },
 {
  "slug": "cole-small-bets-huge-payoffs",
  "guest": "Chris Cole",
  "date": "2016-11-29",
  "title": "Small Bets, Huge Payoffs",
  "q": "I'm right 1-2 times out of 10, but those times pay for everything.",
  "who": "Chris Cole"
 },
 {
  "slug": "cole-small-bets-huge-payoffs",
  "guest": "Chris Cole",
  "date": "2016-11-29",
  "title": "Small Bets, Huge Payoffs",
  "q": "You can't destroy risk. You take returns from the future and bring them to the present, and you take tails and push them into the future.",
  "who": "Chris Cole"
 },
 {
  "slug": "cole-small-bets-huge-payoffs",
  "guest": "Chris Cole",
  "date": "2016-11-29",
  "title": "Small Bets, Huge Payoffs",
  "q": "Dennis Rodman is 6 standard deviations away from the mean in rebounding. Rodman is better at rebounding than Michael Jordan is at scoring.",
  "who": "Chris Cole"
 },
 {
  "slug": "drogen-quant-vs-traditional-investors-and-how-alphas-become-betas",
  "guest": "Leigh Drogen",
  "date": "2017-06-13",
  "title": "Quant vs. Traditional Investors and How Alphas Become Betas",
  "q": "They're just simply opting out because of it.",
  "who": "Leigh"
 },
 {
  "slug": "drogen-quant-vs-traditional-investors-and-how-alphas-become-betas",
  "guest": "Leigh Drogen",
  "date": "2017-06-13",
  "title": "Quant vs. Traditional Investors and How Alphas Become Betas",
  "q": "So actually my educational background is in behavioral economics and war theory.",
  "who": "Leigh"
 },
 {
  "slug": "drogen-quant-vs-traditional-investors-and-how-alphas-become-betas",
  "guest": "Leigh Drogen",
  "date": "2017-06-13",
  "title": "Quant vs. Traditional Investors and How Alphas Become Betas",
  "q": "So this was crazy.",
  "who": "Leigh"
 },
 {
  "slug": "drogen-quant-vs-traditional-investors-and-how-alphas-become-betas",
  "guest": "Leigh Drogen",
  "date": "2017-06-13",
  "title": "Quant vs. Traditional Investors and How Alphas Become Betas",
  "q": "Yeah. I think the informational edge is becoming more arbitrage these days.",
  "who": "Leigh"
 },
 {
  "slug": "egan-designing-better-decisions",
  "guest": "Dan Egan",
  "date": "2017-01-03",
  "title": "Designing Better Decisions",
  "q": "What if we changed this one thing? How does that reveal what's really going on?",
  "who": "Dan Egan"
 },
 {
  "slug": "egan-designing-better-decisions",
  "guest": "Dan Egan",
  "date": "2017-01-03",
  "title": "Designing Better Decisions",
  "q": "The best way to predict the future is to build it.",
  "who": "Abraham Lincoln (via Dan Egan)"
 },
 {
  "slug": "egan-designing-better-decisions",
  "guest": "Dan Egan",
  "date": "2017-01-03",
  "title": "Designing Better Decisions",
  "q": "Never compete against somebody who enjoys what they're doing more than you.",
  "who": "Dan Egan"
 },
 {
  "slug": "egan-designing-better-decisions",
  "guest": "Dan Egan",
  "date": "2017-01-03",
  "title": "Designing Better Decisions",
  "q": "Money is a symptom of poverty.",
  "who": "Ian M. Banks (via Dan Egan)"
 },
 {
  "slug": "ganti-esoteric-assets",
  "guest": "Rishi Ganti",
  "date": "2017-07-18",
  "title": "Esoteric Assets",
  "q": "The minute there are multiple buyers for anything, prices get efficient very quickly.",
  "who": "Rishi"
 },
 {
  "slug": "ganti-esoteric-assets",
  "guest": "Rishi Ganti",
  "date": "2017-07-18",
  "title": "Esoteric Assets",
  "q": "If you even have two bidders in a market, you're squeezing out all the alpha that exists.",
  "who": "Rishi"
 },
 {
  "slug": "ganti-esoteric-assets",
  "guest": "Rishi Ganti",
  "date": "2017-07-18",
  "title": "Esoteric Assets",
  "q": "To avoid a price mechanism, you have to avoid a market.",
  "who": "Rishi"
 },
 {
  "slug": "ganti-esoteric-assets",
  "guest": "Rishi Ganti",
  "date": "2017-07-18",
  "title": "Esoteric Assets",
  "q": "Once you have the x-ray goggles on, the world's so much more vast than what people give it credit for.",
  "who": "Rishi"
 },
 {
  "slug": "gramm-activist-investing",
  "guest": "Jeff Gramm",
  "date": "2016-09-11",
  "title": "Activist Investing",
  "q": "Value investing is a nice way of saying very pessimistic outlook.",
  "who": "Jeff Gramm"
 },
 {
  "slug": "gramm-activist-investing",
  "guest": "Jeff Gramm",
  "date": "2016-09-11",
  "title": "Activist Investing",
  "q": "People are self-interested animals.",
  "who": "Jeff Gramm"
 },
 {
  "slug": "gramm-activist-investing",
  "guest": "Jeff Gramm",
  "date": "2016-09-11",
  "title": "Activist Investing",
  "q": "Great capital allocation is so rare. It can be hard to predict in the future.",
  "who": "Jeff Gramm"
 },
 {
  "slug": "gramm-activist-investing",
  "guest": "Jeff Gramm",
  "date": "2016-09-11",
  "title": "Activist Investing",
  "q": "Boards often don't know how to value companies or think about the value of their companies.",
  "who": "Jeff Gramm"
 },
 {
  "slug": "higgins-permanent-equity",
  "guest": "Trish & James Higgins",
  "date": "2017-03-14",
  "title": "Permanent Equity",
  "q": "If you own a bait shop by a fishing spot, you earn above-market returns because you're the only game in town.",
  "who": "James Higgins"
 },
 {
  "slug": "higgins-permanent-equity",
  "guest": "Trish & James Higgins",
  "date": "2017-03-14",
  "title": "Permanent Equity",
  "q": "We think of ourselves as sitting at the intersection of investment capital, sellers seeking exits, and entrepreneurial talent.",
  "who": "James Higgins"
 },
 {
  "slug": "higgins-permanent-equity",
  "guest": "Trish & James Higgins",
  "date": "2017-03-14",
  "title": "Permanent Equity",
  "q": "I was not a majority owner of AQR Capital Management.",
  "who": "Trish Higgins"
 },
 {
  "slug": "housel-walking-and-thinking",
  "guest": "Morgan Housel",
  "date": "2016-10-04",
  "title": "Walking and Thinking",
  "q": "The odds are this won't work. 1 in 50, that's great. Better than I thought.",
  "who": "Morgan Housel"
 },
 {
  "slug": "housel-walking-and-thinking",
  "guest": "Morgan Housel",
  "date": "2016-10-04",
  "title": "Walking and Thinking",
  "q": "You only think when you walk. I only think when I walk.",
  "who": "Morgan Housel"
 },
 {
  "slug": "housel-walking-and-thinking",
  "guest": "Morgan Housel",
  "date": "2016-10-04",
  "title": "Walking and Thinking",
  "q": "Almost every great investor gets more humble as time goes on.",
  "who": "Morgan Housel"
 },
 {
  "slug": "hy-quant-hedge-funds-and-the-fear-of-death",
  "guest": "week is Khe Hy",
  "date": "2017-04-04",
  "title": "Quant Hedge Funds and the Fear of Death",
  "q": "My guest this week is Khe Hy.",
  "who": "week is Khe Hy"
 },
 {
  "slug": "hy-quant-hedge-funds-and-the-fear-of-death",
  "guest": "week is Khe Hy",
  "date": "2017-04-04",
  "title": "Quant Hedge Funds and the Fear of Death",
  "q": "Talk a little bit about the role of evaluating hedge funds.",
  "who": "week is Khe Hy"
 },
 {
  "slug": "hy-quant-hedge-funds-and-the-fear-of-death",
  "guest": "week is Khe Hy",
  "date": "2017-04-04",
  "title": "Quant Hedge Funds and the Fear of Death",
  "q": "I'll mention this kind of slight nuance to maybe color your answer on how you then evaluated the funds.",
  "who": "week is Khe Hy"
 },
 {
  "slug": "hy-quant-hedge-funds-and-the-fear-of-death",
  "guest": "week is Khe Hy",
  "date": "2017-04-04",
  "title": "Quant Hedge Funds and the Fear of Death",
  "q": "We'll mention the incredible rise of quantitative strategies across the investing landscape.",
  "who": "week is Khe Hy"
 },
 {
  "slug": "judelson-bail-street-with-nycs-leading-bail-bondsman",
  "guest": "Ira Judelson",
  "date": "2017-06-06",
  "title": "Bail Street, with NYC's Leading Bail Bondsman",
  "q": "Well, Rao's is obviously the eatery in Harlem that you can't get a table, there's no reservation.",
  "who": "Ira"
 },
 {
  "slug": "judelson-bail-street-with-nycs-leading-bail-bondsman",
  "guest": "Ira Judelson",
  "date": "2017-06-06",
  "title": "Bail Street, with NYC's Leading Bail Bondsman",
  "q": "There's a lot of very strong people that go there.",
  "who": "Ira"
 },
 {
  "slug": "judelson-bail-street-with-nycs-leading-bail-bondsman",
  "guest": "Ira Judelson",
  "date": "2017-06-06",
  "title": "Bail Street, with NYC's Leading Bail Bondsman",
  "q": "I was in business. I was in business. Oh God, I can't even remember.",
  "who": "Ira"
 },
 {
  "slug": "judelson-bail-street-with-nycs-leading-bail-bondsman",
  "guest": "Ira Judelson",
  "date": "2017-06-06",
  "title": "Bail Street, with NYC's Leading Bail Bondsman",
  "q": "But I did get the defendant. We did actually get him.",
  "who": "Ira"
 },
 {
  "slug": "koppelman-chasing-curiosity",
  "guest": "Brian Koppelman",
  "date": "2017-01-24",
  "title": "Chasing Curiosity",
  "q": "I don't change things when they're still working. That's your move.",
  "who": "Solitary Man character (quoted)"
 },
 {
  "slug": "koppelman-chasing-curiosity",
  "guest": "Brian Koppelman",
  "date": "2017-01-24",
  "title": "Chasing Curiosity",
  "q": "Humans are happiest when accessing their most creative self.",
  "who": "Brian Koppelman"
 },
 {
  "slug": "koppelman-chasing-curiosity",
  "guest": "Brian Koppelman",
  "date": "2017-01-24",
  "title": "Chasing Curiosity",
  "q": "You overestimate what you accomplish in a year; underestimate what you accomplish in 10.",
  "who": "Tony Robbins (cited)"
 },
 {
  "slug": "koppelman-chasing-curiosity",
  "guest": "Brian Koppelman",
  "date": "2017-01-24",
  "title": "Chasing Curiosity",
  "q": "If I knew the answer, I'd have to stop writing it.",
  "who": "Brian Koppelman"
 },
 {
  "slug": "koppelman-chasing-curiosity",
  "guest": "Brian Koppelman",
  "date": "2017-01-24",
  "title": "Chasing Curiosity",
  "q": "The conscious mind disappears and you enter this alpha state.",
  "who": "Brian Koppelman"
 },
 {
  "slug": "maddox-the-ace-of-spades",
  "guest": "Eric Maddox",
  "date": "2016-12-13",
  "title": "The Ace of Spades",
  "q": "The old technique never got a single prisoner to open up. 4% success rate across military. My method: 65%.",
  "who": "Eric Maddox"
 },
 {
  "slug": "maddox-the-ace-of-spades",
  "guest": "Eric Maddox",
  "date": "2016-12-13",
  "title": "The Ace of Spades",
  "q": "I don't know much about this topic, but here's what I'm reading—join me. That openness changes everything.",
  "who": "Eric Maddox (on teaching approach)"
 },
 {
  "slug": "maddox-the-ace-of-spades",
  "guest": "Eric Maddox",
  "date": "2016-12-13",
  "title": "The Ace of Spades",
  "q": "Charisma is power plus empathy. A great listener is an attractive person. They know when you're listening.",
  "who": "Eric Maddox"
 },
 {
  "slug": "maddox-the-ace-of-spades",
  "guest": "Eric Maddox",
  "date": "2016-12-13",
  "title": "The Ace of Spades",
  "q": "Courage is knowing it's right to help the enemy at the lower level for the larger strategic mission, even when your soldiers hate it.",
  "who": "Eric Maddox (paraphrasing his Delta commander)"
 },
 {
  "slug": "mansueto-lessons-from-the-founder-of-morningstar",
  "guest": "Joe Mansueto",
  "date": "2017-02-07",
  "title": "Lessons From the Founder of Morningstar",
  "q": "The sun is but a morning star. No matter where you are, you're still a rising sun.",
  "who": "Joe"
 },
 {
  "slug": "mansueto-lessons-from-the-founder-of-morningstar",
  "guest": "Joe Mansueto",
  "date": "2017-02-07",
  "title": "Lessons From the Founder of Morningstar",
  "q": "We wanted to give individual investors tools to analyze stocks like professionals would.",
  "who": "Joe"
 },
 {
  "slug": "mansueto-lessons-from-the-founder-of-morningstar",
  "guest": "Joe Mansueto",
  "date": "2017-02-07",
  "title": "Lessons From the Founder of Morningstar",
  "q": "Learn to say no and don't try to satisfy all comers.",
  "who": "Joe"
 },
 {
  "slug": "mauboussin-active-asset-management",
  "guest": "Michael Mauboussin",
  "date": "2016-09-20",
  "title": "Active Asset Management",
  "q": "A great client is one who cashes a check when we hand it to him and writes us a check when we ask.",
  "who": "Michael Mauboussin"
 },
 {
  "slug": "mauboussin-active-asset-management",
  "guest": "Michael Mauboussin",
  "date": "2016-09-20",
  "title": "Active Asset Management",
  "q": "Skill is analytical skills and managing behavioral issues; portfolio construction is managing and mitigating behavioral problems.",
  "who": "Michael Mauboussin"
 },
 {
  "slug": "mauboussin-active-asset-management",
  "guest": "Michael Mauboussin",
  "date": "2016-09-20",
  "title": "Active Asset Management",
  "q": "For stock to go up, you must do better than what the market already expects.",
  "who": "Michael Mauboussin"
 },
 {
  "slug": "mauboussin-active-asset-management",
  "guest": "Michael Mauboussin",
  "date": "2016-09-20",
  "title": "Active Asset Management",
  "q": "Articles about buybacks by journalists are drivel—not informed or thoughtful.",
  "who": "Michael Mauboussin"
 },
 {
  "slug": "mauboussin-man-machine-moats-and-power-of-the-outside-view",
  "guest": "Michael Mauboussin",
  "date": "2017-05-16",
  "title": "Man + Machine, Moats, and Power of the Outside View",
  "q": "Markets have to be efficiently inefficient.",
  "who": "Michael Mauboussin"
 },
 {
  "slug": "mauboussin-man-machine-moats-and-power-of-the-outside-view",
  "guest": "Michael Mauboussin",
  "date": "2017-05-16",
  "title": "Man + Machine, Moats, and Power of the Outside View",
  "q": "If you want lots of liquidity, you should realize you're not going to have a lot of control.",
  "who": "Michael Mauboussin"
 },
 {
  "slug": "mauboussin-man-machine-moats-and-power-of-the-outside-view",
  "guest": "Michael Mauboussin",
  "date": "2017-05-16",
  "title": "Man + Machine, Moats, and Power of the Outside View",
  "q": "You haven't accomplished anything until you're liquid.",
  "who": "Bill Gurley (cited by Mauboussin)"
 },
 {
  "slug": "mauboussin-man-machine-moats-and-power-of-the-outside-view",
  "guest": "Michael Mauboussin",
  "date": "2017-05-16",
  "title": "Man + Machine, Moats, and Power of the Outside View",
  "q": "Pre-IPO is the new IPO.",
  "who": "Fidelity executive (cited by Mauboussin)"
 },
 {
  "slug": "moazed-building-modern-monopolies",
  "guest": "Alex Moazed",
  "date": "2017-02-21",
  "title": "Building Modern Monopolies",
  "q": "Software alone is a commodity. The value is in the ecosystem.",
  "who": "Alex Moazed"
 },
 {
  "slug": "moazed-building-modern-monopolies",
  "guest": "Alex Moazed",
  "date": "2017-02-21",
  "title": "Building Modern Monopolies",
  "q": "A lot of the things you're doing in the beginning don't scale at all.",
  "who": "Alex Moazed"
 },
 {
  "slug": "moazed-building-modern-monopolies",
  "guest": "Alex Moazed",
  "date": "2017-02-21",
  "title": "Building Modern Monopolies",
  "q": "You just focus on having equipment ready, I'm going to get you customers.",
  "who": "Alex Moazed"
 },
 {
  "slug": "moazed-building-modern-monopolies",
  "guest": "Alex Moazed",
  "date": "2017-02-21",
  "title": "Building Modern Monopolies",
  "q": "Complex systems that work result from simple systems scaled, not systems designed and dropped in.",
  "who": "Patrick O'Shaughnessy"
 },
 {
  "slug": "moses-the-big-short-and-beyond",
  "guest": "Danny Moses",
  "date": "2017-04-25",
  "title": "The Big Short and Beyond",
  "q": "No trade is as good as it appears. Leverage will always bury you in the end if you have the wrong trade on.",
  "who": "Danny"
 },
 {
  "slug": "moses-the-big-short-and-beyond",
  "guest": "Danny Moses",
  "date": "2017-04-25",
  "title": "The Big Short and Beyond",
  "q": "If you don't underwrite correctly, then it's over. It doesn't matter what you're lending in.",
  "who": "Danny"
 },
 {
  "slug": "moses-the-big-short-and-beyond",
  "guest": "Danny Moses",
  "date": "2017-04-25",
  "title": "The Big Short and Beyond",
  "q": "You're better off knowing what ETF owns your stock than what the company even does. That's scary to me.",
  "who": "Danny"
 },
 {
  "slug": "neumann-the-deployment-age-power-laws-and-venture-capital",
  "guest": "Jerry Neumann",
  "date": "2017-07-11",
  "title": "The Deployment Age, Power Laws, and Venture Capital",
  "q": "People have really bad instincts about what things are going to work.",
  "who": "Jerry Neumann"
 },
 {
  "slug": "neumann-the-deployment-age-power-laws-and-venture-capital",
  "guest": "Jerry Neumann",
  "date": "2017-07-11",
  "title": "The Deployment Age, Power Laws, and Venture Capital",
  "q": "Risk is predictable, uncertainty you can't insure because you don't know the probability distribution.",
  "who": "Jerry Neumann"
 },
 {
  "slug": "neumann-the-deployment-age-power-laws-and-venture-capital",
  "guest": "Jerry Neumann",
  "date": "2017-07-11",
  "title": "The Deployment Age, Power Laws, and Venture Capital",
  "q": "If there was a recipe for building successful billion-dollar companies, you'd have factories churning them out.",
  "who": "Jerry Neumann"
 },
 {
  "slug": "neumann-the-deployment-age-power-laws-and-venture-capital",
  "guest": "Jerry Neumann",
  "date": "2017-07-11",
  "title": "The Deployment Age, Power Laws, and Venture Capital",
  "q": "I always have to sleep on it because the next day you've calmed down and ask if it's still a great idea.",
  "who": "Jerry Neumann"
 },
 {
  "slug": "norton-seek-to-learn-that-which-cannot-be-taught",
  "guest": "Scott Norton",
  "date": "2017-06-27",
  "title": "Seek to Learn That Which Cannot be Taught",
  "q": "Seek to learn that which cannot be taught.",
  "who": "Scott Norton"
 },
 {
  "slug": "norton-seek-to-learn-that-which-cannot-be-taught",
  "guest": "Scott Norton",
  "date": "2017-06-27",
  "title": "Seek to Learn That Which Cannot be Taught",
  "q": "Business is fundamentally creative, not competitive.",
  "who": "Scott Norton"
 },
 {
  "slug": "norton-seek-to-learn-that-which-cannot-be-taught",
  "guest": "Scott Norton",
  "date": "2017-06-27",
  "title": "Seek to Learn That Which Cannot be Taught",
  "q": "If you want to be successful, don't be a go getter, be a go giver.",
  "who": "Scott Norton (quoting his grandfather)"
 },
 {
  "slug": "norton-seek-to-learn-that-which-cannot-be-taught",
  "guest": "Scott Norton",
  "date": "2017-06-27",
  "title": "Seek to Learn That Which Cannot be Taught",
  "q": "When you're in the unknown, you start to be at home with the world.",
  "who": "Scott Norton"
 },
 {
  "slug": "oshaughnessy-premeditated-success",
  "guest": "Jim O'Shaughnessy",
  "date": "2017-03-21",
  "title": "Premeditated Success",
  "q": "Spend two weeks managing cash flow of a small business—suddenly you understand why the cash flow statement matters.",
  "who": "Jim O'Shaughnessy"
 },
 {
  "slug": "oshaughnessy-premeditated-success",
  "guest": "Jim O'Shaughnessy",
  "date": "2017-03-21",
  "title": "Premeditated Success",
  "q": "The harder I work, the luckier I get.",
  "who": "Jim O'Shaughnessy"
 },
 {
  "slug": "oshaughnessy-premeditated-success",
  "guest": "Jim O'Shaughnessy",
  "date": "2017-03-21",
  "title": "Premeditated Success",
  "q": "Luck is the hand you're dealt. Talent and achievement is how you play that hand.",
  "who": "Jim O'Shaughnessy"
 },
 {
  "slug": "oshaughnessy-premeditated-success",
  "guest": "Jim O'Shaughnessy",
  "date": "2017-03-21",
  "title": "Premeditated Success",
  "q": "I know when I enter your office to ask something, I'm fairly certain what your answer will be, but I have to ask anyway.",
  "who": "Chris Loveless (O'Shaughnessy's president)"
 },
 {
  "slug": "oshaughnessy-ten-lessons-after-almost-a-year-of-podcasting",
  "guest": "Patrick O'Shaughnessy (solo episode)",
  "date": "2017-07-05",
  "title": "Ten Lessons After Almost a Year of Podcasting",
  "q": "Conversation is my new favorite way to learn.",
  "who": "Patrick O'Shaughnessy"
 },
 {
  "slug": "oshaughnessy-ten-lessons-after-almost-a-year-of-podcasting",
  "guest": "Patrick O'Shaughnessy (solo episode)",
  "date": "2017-07-05",
  "title": "Ten Lessons After Almost a Year of Podcasting",
  "q": "The less your ego gets involved, the more you will learn.",
  "who": "Patrick O'Shaughnessy"
 },
 {
  "slug": "oshaughnessy-ten-lessons-after-almost-a-year-of-podcasting",
  "guest": "Patrick O'Shaughnessy (solo episode)",
  "date": "2017-07-05",
  "title": "Ten Lessons After Almost a Year of Podcasting",
  "q": "You also get the listeners that you deserve.",
  "who": "Patrick O'Shaughnessy"
 },
 {
  "slug": "oshaughnessy-ten-lessons-after-almost-a-year-of-podcasting",
  "guest": "Patrick O'Shaughnessy (solo episode)",
  "date": "2017-07-05",
  "title": "Ten Lessons After Almost a Year of Podcasting",
  "q": "The means and the end are the same.",
  "who": "Patrick O'Shaughnessy"
 },
 {
  "slug": "parrish-mastering-mental-models",
  "guest": "Shane Parrish",
  "date": "2016-12-27",
  "title": "Mastering Mental Models",
  "q": "The growth mindset is: if I work harder, I can learn how to do it.",
  "who": "Shane Parrish"
 },
 {
  "slug": "parrish-mastering-mental-models",
  "guest": "Shane Parrish",
  "date": "2016-12-27",
  "title": "Mastering Mental Models",
  "q": "Mastering the best of what other people have figured out.",
  "who": "Shane Parrish"
 },
 {
  "slug": "parrish-mastering-mental-models",
  "guest": "Shane Parrish",
  "date": "2016-12-27",
  "title": "Mastering Mental Models",
  "q": "Most of today's bestsellers disappear in 10 years.",
  "who": "Shane Parrish"
 },
 {
  "slug": "parrish-mastering-mental-models",
  "guest": "Shane Parrish",
  "date": "2016-12-27",
  "title": "Mastering Mental Models",
  "q": "You can create more money, but you can't create more time.",
  "who": "Shane Parrish"
 },
 {
  "slug": "ptak-the-prospects-for-active-management",
  "guest": "Jeff Ptak",
  "date": "2016-12-20",
  "title": "The Prospects for Active Management",
  "q": "The cheapest quintile are 3x as likely to survive than the most expensive quintile.",
  "who": "Jeff Ptak"
 },
 {
  "slug": "ptak-the-prospects-for-active-management",
  "guest": "Jeff Ptak",
  "date": "2016-12-20",
  "title": "The Prospects for Active Management",
  "q": "It's not the action that's important. In many cases, it's inaction.",
  "who": "Jeff Ptak"
 },
 {
  "slug": "ptak-the-prospects-for-active-management",
  "guest": "Jeff Ptak",
  "date": "2016-12-20",
  "title": "The Prospects for Active Management",
  "q": "Unless they're willing to do the work, they should index.",
  "who": "Jeff Ptak"
 },
 {
  "slug": "ptak-the-prospects-for-active-management",
  "guest": "Jeff Ptak",
  "date": "2016-12-20",
  "title": "The Prospects for Active Management",
  "q": "Winners very often don't look like winners for long stretches.",
  "who": "Jeff Ptak"
 },
 {
  "slug": "rachleff-building-something-people-want-to-buy",
  "guest": "Andy Rachleff",
  "date": "2017-06-20",
  "title": "Building Something People Want to Buy",
  "q": "He is the oldest.",
  "who": "Andy"
 },
 {
  "slug": "rachleff-building-something-people-want-to-buy",
  "guest": "Andy Rachleff",
  "date": "2017-06-20",
  "title": "Building Something People Want to Buy",
  "q": "We believe in euthanasia, let's put it that way.",
  "who": "Andy"
 },
 {
  "slug": "rachleff-building-something-people-want-to-buy",
  "guest": "Andy Rachleff",
  "date": "2017-06-20",
  "title": "Building Something People Want to Buy",
  "q": "So let me just finish the other point then we'll come back to this.",
  "who": "Andy"
 },
 {
  "slug": "rachleff-building-something-people-want-to-buy",
  "guest": "Andy Rachleff",
  "date": "2017-06-20",
  "title": "Building Something People Want to Buy",
  "q": "... as the internet was taking off.",
  "who": "Andy"
 },
 {
  "slug": "rogers-slow-and-steady-wins-the-race",
  "guest": "John Rogers",
  "date": "2017-02-28",
  "title": "Slow and Steady Wins the Race",
  "q": "You're one of the rare firms that talks about 3-5-7 year plans, not 3-5-7 month results.",
  "who": "management teams (via John Rogers)"
 },
 {
  "slug": "rogers-slow-and-steady-wins-the-race",
  "guest": "John Rogers",
  "date": "2017-02-28",
  "title": "Slow and Steady Wins the Race",
  "q": "By the time you're 18 or 19, I can't teach you to see.",
  "who": "Coach Pete Carril"
 },
 {
  "slug": "rogers-slow-and-steady-wins-the-race",
  "guest": "John Rogers",
  "date": "2017-02-28",
  "title": "Slow and Steady Wins the Race",
  "q": "The difficulty of executing and thinking independently does allow for the moat.",
  "who": "John Rogers"
 },
 {
  "slug": "rogers-slow-and-steady-wins-the-race",
  "guest": "John Rogers",
  "date": "2017-02-28",
  "title": "Slow and Steady Wins the Race",
  "q": "Where else should I be?",
  "who": "John Rogers (meeting Daniel Kahneman)"
 },
 {
  "slug": "rowley-vanguards-gerry-oreilly-and-jim-rowley",
  "guest": "Gerry O'Reilly & Jim Rowley",
  "date": "2016-10-18",
  "title": "Vanguard's Gerry O'Reilly and Jim Rowley",
  "q": "Only half the dollars can do better than average, no matter what.",
  "who": "Jim Rowley"
 },
 {
  "slug": "rowley-vanguards-gerry-oreilly-and-jim-rowley",
  "guest": "Gerry O'Reilly & Jim Rowley",
  "date": "2016-10-18",
  "title": "Vanguard's Gerry O'Reilly and Jim Rowley",
  "q": "You start every sentence with 'we' not 'I.' That gets noticed.",
  "who": "Jim Rowley"
 },
 {
  "slug": "rowley-vanguards-gerry-oreilly-and-jim-rowley",
  "guest": "Gerry O'Reilly & Jim Rowley",
  "date": "2016-10-18",
  "title": "Vanguard's Gerry O'Reilly and Jim Rowley",
  "q": "The stock-bond decision is the most powerful risk-return decision you can make.",
  "who": "Jim Rowley"
 },
 {
  "slug": "rowley-vanguards-gerry-oreilly-and-jim-rowley",
  "guest": "Gerry O'Reilly & Jim Rowley",
  "date": "2016-10-18",
  "title": "Vanguard's Gerry O'Reilly and Jim Rowley",
  "q": "I look forward to coming in Monday morning. I think I'm in the minority.",
  "who": "Gerry O'Reilly"
 },
 {
  "slug": "rudder-the-quantified-self",
  "guest": "Christian Rudder",
  "date": "2016-10-11",
  "title": "The Quantified Self",
  "q": "Guys basically go after the youngest women period.",
  "who": "Christian Rudder"
 },
 {
  "slug": "rudder-the-quantified-self",
  "guest": "Christian Rudder",
  "date": "2016-10-11",
  "title": "The Quantified Self",
  "q": "What you do with the results of the math, that's by far the hardest part.",
  "who": "Christian Rudder"
 },
 {
  "slug": "rudder-the-quantified-self",
  "guest": "Christian Rudder",
  "date": "2016-10-11",
  "title": "The Quantified Self",
  "q": "Be persistent but don't be too committed to this one idea if people don't like it.",
  "who": "Christian Rudder"
 },
 {
  "slug": "rudder-the-quantified-self",
  "guest": "Christian Rudder",
  "date": "2016-10-11",
  "title": "The Quantified Self",
  "q": "Luck plays a tremendous amount. Things could've gone sideways very easily.",
  "who": "Christian Rudder"
 },
 {
  "slug": "salem-the-art-of-asset-allocation",
  "guest": "David Salem",
  "date": "2017-05-23",
  "title": "The Art of Asset Allocation",
  "q": "Asset allocation is not about math; it's about behavior.",
  "who": "David Salem"
 },
 {
  "slug": "seides-a-deep-dive-into-hedge-funds",
  "guest": "Ted Seides",
  "date": "2016-10-25",
  "title": "A Deep Dive into Hedge Funds",
  "q": "Be the hero of your own life.",
  "who": "Ted Seides"
 },
 {
  "slug": "seides-a-deep-dive-into-hedge-funds",
  "guest": "Ted Seides",
  "date": "2016-10-25",
  "title": "A Deep Dive into Hedge Funds",
  "q": "It's a people business. Ultimately you're making an assessment of the individual.",
  "who": "Ted Seides"
 },
 {
  "slug": "seides-a-deep-dive-into-hedge-funds",
  "guest": "Ted Seides",
  "date": "2016-10-25",
  "title": "A Deep Dive into Hedge Funds",
  "q": "Yeah, it worked.",
  "who": "John Paulson"
 },
 {
  "slug": "seides-a-deep-dive-into-hedge-funds",
  "guest": "Ted Seides",
  "date": "2016-10-25",
  "title": "A Deep Dive into Hedge Funds",
  "q": "Hedge fund operations are like going to the dentist; investors have zero patience for mistakes.",
  "who": "Ted Seides"
 },
 {
  "slug": "seides-the-bet-with-buffett",
  "guest": "Ted Seides",
  "date": "2017-05-02",
  "title": "The Bet With Buffett",
  "q": "If hedge fund fees were zero, I'd still invest in some and not others. The fee question is secondary to whether they add value.",
  "who": "Ted"
 },
 {
  "slug": "seides-the-bet-with-buffett",
  "guest": "Ted Seides",
  "date": "2017-05-02",
  "title": "The Bet With Buffett",
  "q": "No one has earned the returns of the S&P 500 over this 9.5 years because almost no one has the capacity to suffer through 2008.",
  "who": "Ted"
 },
 {
  "slug": "seides-the-bet-with-buffett",
  "guest": "Ted Seides",
  "date": "2017-05-02",
  "title": "The Bet With Buffett",
  "q": "Warren is the most favorable buyer because he credibly doesn't have to sell. That's a powerful permanent capital advantage.",
  "who": "Ted"
 },
 {
  "slug": "seides-the-future-of-asset-management",
  "guest": "Ted Seides & Brent Beshore",
  "date": "2017-03-28",
  "title": "The Future of Asset Management",
  "q": "Intuition is a finely tuned algorithm rooted in enormous experience. Gather tons of experience, let subconscious process it.",
  "who": "Patrick O'Shaughnessy"
 },
 {
  "slug": "seides-the-future-of-asset-management",
  "guest": "Ted Seides & Brent Beshore",
  "date": "2017-03-28",
  "title": "The Future of Asset Management",
  "q": "Don't build a system unless you absolutely need to. If you do, make it extremely simple and let it evolve.",
  "who": "Ted Seides (recommending Systems Bible)"
 },
 {
  "slug": "seides-the-future-of-asset-management",
  "guest": "Ted Seides & Brent Beshore",
  "date": "2017-03-28",
  "title": "The Future of Asset Management",
  "q": "Most small businesses fail because they won't do the basics—the hygiene. Floors need cleaning, tooth brushes need using.",
  "who": "Brent Beshore"
 },
 {
  "slug": "seides-the-future-of-asset-management",
  "guest": "Ted Seides & Brent Beshore",
  "date": "2017-03-28",
  "title": "The Future of Asset Management",
  "q": "Lunch is not free. Small businesses lack the business fundamentals: where does cash come from, where does it go.",
  "who": "Brent Beshore"
 },
 {
  "slug": "shapiro-better-for-you-better-for-the-world",
  "guest": "Craig Shapiro",
  "date": "2016-11-14",
  "title": "Better for You, Better for the World",
  "q": "Don't shine the turd - if something goes wrong, tell me immediately.",
  "who": "Anonymous investor to Craig"
 },
 {
  "slug": "shapiro-better-for-you-better-for-the-world",
  "guest": "Craig Shapiro",
  "date": "2016-11-14",
  "title": "Better for You, Better for the World",
  "q": "Businesses balancing profit and social good generate the greatest returns.",
  "who": "Craig Shapiro"
 },
 {
  "slug": "shapiro-better-for-you-better-for-the-world",
  "guest": "Craig Shapiro",
  "date": "2016-11-14",
  "title": "Better for You, Better for the World",
  "q": "Financial markets haven't shifted alongside culture toward stakeholder value.",
  "who": "Craig Shapiro"
 },
 {
  "slug": "shapiro-watching-a-venture-fund-at-work",
  "guest": "Lauren Loktev, Kanyi Maqubela & Craig Shapiro",
  "date": "2017-01-10",
  "title": "Watching a Venture Fund at Work",
  "q": "Investing in assets that don't exist yet requires hands-on work but also deep thematic conviction.",
  "who": "Craig Shapiro"
 },
 {
  "slug": "shapiro-watching-a-venture-fund-at-work",
  "guest": "Lauren Loktev, Kanyi Maqubela & Craig Shapiro",
  "date": "2017-01-10",
  "title": "Watching a Venture Fund at Work",
  "q": "Fundraising is not a business model.",
  "who": "Kanyi Maqubela"
 },
 {
  "slug": "shapiro-watching-a-venture-fund-at-work",
  "guest": "Lauren Loktev, Kanyi Maqubela & Craig Shapiro",
  "date": "2017-01-10",
  "title": "Watching a Venture Fund at Work",
  "q": "Brand is at least to some extent about relationships.",
  "who": "Kanyi Maqubela"
 },
 {
  "slug": "shapiro-watching-a-venture-fund-at-work",
  "guest": "Lauren Loktev, Kanyi Maqubela & Craig Shapiro",
  "date": "2017-01-10",
  "title": "Watching a Venture Fund at Work",
  "q": "The pace at which you uncover unknown unknowns is how you know a founder is really getting deep into their market.",
  "who": "Kanyi Maqubela"
 },
 {
  "slug": "simler-exploring-the-frontier",
  "guest": "Kevin Simler",
  "date": "2016-11-22",
  "title": "Exploring the Frontier",
  "q": "Palantir was and always will be a startup - in my heart.",
  "who": "Kevin Simler"
 },
 {
  "slug": "simler-exploring-the-frontier",
  "guest": "Kevin Simler",
  "date": "2016-11-22",
  "title": "Exploring the Frontier",
  "q": "If you think the world is playful, it's more fun to be in.",
  "who": "Kevin Simler"
 },
 {
  "slug": "simler-exploring-the-frontier",
  "guest": "Kevin Simler",
  "date": "2016-11-22",
  "title": "Exploring the Frontier",
  "q": "The frontier is not synonymous with growth, but highly implicative of it.",
  "who": "Kevin Simler"
 },
 {
  "slug": "simler-exploring-the-frontier",
  "guest": "Kevin Simler",
  "date": "2016-11-22",
  "title": "Exploring the Frontier",
  "q": "Math unlocks the inner workings of the world, but disconnects from what it means to be human.",
  "who": "Kevin Simler"
 },
 {
  "slug": "stein-the-state-of-automated-investing",
  "guest": "Jon Stein",
  "date": "2016-11-01",
  "title": "The State of Automated Investing",
  "q": "Inertia is our biggest competitor.",
  "who": "Jon Stein"
 },
 {
  "slug": "stein-the-state-of-automated-investing",
  "guest": "Jon Stein",
  "date": "2016-11-01",
  "title": "The State of Automated Investing",
  "q": "It only exists because we say it exists.",
  "who": "Jon Stein"
 },
 {
  "slug": "stein-the-state-of-automated-investing",
  "guest": "Jon Stein",
  "date": "2016-11-01",
  "title": "The State of Automated Investing",
  "q": "We're building an institution, and by that I mean, building for the long term.",
  "who": "Jon Stein"
 },
 {
  "slug": "stein-the-state-of-automated-investing",
  "guest": "Jon Stein",
  "date": "2016-11-01",
  "title": "The State of Automated Investing",
  "q": "You don't rise to the occasion. You resort to your level of training.",
  "who": "Jon Stein"
 },
 {
  "slug": "thorndike-how-skilled-capital-allocators-compound-capital",
  "guest": "Will Thorndike",
  "date": "2017-05-09",
  "title": "How Skilled Capital Allocators Compound Capital",
  "q": "If it's becoming popular, it's probably not as good or opportunistic anymore. Once everyone's doing it, the edge is gone.",
  "who": "Henry Singleton (quoted)"
 },
 {
  "slug": "thorndike-how-skilled-capital-allocators-compound-capital",
  "guest": "Will Thorndike",
  "date": "2017-05-09",
  "title": "How Skilled Capital Allocators Compound Capital",
  "q": "We paint the two sides facing the road. Everything else runs lean—no cuts to content, production, or talent that drives ratings.",
  "who": "Tom Murphy (quoted)"
 },
 {
  "slug": "thorndike-how-skilled-capital-allocators-compound-capital",
  "guest": "Will Thorndike",
  "date": "2017-05-09",
  "title": "How Skilled Capital Allocators Compound Capital",
  "q": "You need to show up and steer the ship every day. You can't predict what opportunities will arise, so you must be prepared to react.",
  "who": "Henry Singleton (quoted)"
 },
 {
  "slug": "varty-the-art-of-tracking",
  "guest": "Boyd Varty",
  "date": "2017-04-11",
  "title": "The Art of Tracking",
  "q": "This week's episode is the most unique to date.",
  "who": "Boyd Varty"
 },
 {
  "slug": "varty-the-art-of-tracking",
  "guest": "Boyd Varty",
  "date": "2017-04-11",
  "title": "The Art of Tracking",
  "q": "A little bit different experience than my Saturdays going to a soccer game or something like that.",
  "who": "Boyd Varty"
 },
 {
  "slug": "varty-the-art-of-tracking",
  "guest": "Boyd Varty",
  "date": "2017-04-11",
  "title": "The Art of Tracking",
  "q": "Yeah, and it lays a nice foundation for sort of where the psychology of my work has gone.",
  "who": "Boyd Varty"
 },
 {
  "slug": "varty-the-art-of-tracking",
  "guest": "Boyd Varty",
  "date": "2017-04-11",
  "title": "The Art of Tracking",
  "q": "Okay, yeah, that will be a fun jump-off point.",
  "who": "Boyd Varty"
 },
 {
  "slug": "yudkoff-really-private-equity",
  "guest": "Royce Yudkoff & Rick Ruback",
  "date": "2017-04-18",
  "title": "REALLY Private Equity",
  "q": "This is Royce, I'll take a crack at it.",
  "who": "Royce Yudkoff & Rick Ruback"
 },
 {
  "slug": "yudkoff-really-private-equity",
  "guest": "Royce Yudkoff & Rick Ruback",
  "date": "2017-04-18",
  "title": "REALLY Private Equity",
  "q": "Rick and I see investors doing just one deal.",
  "who": "Royce Yudkoff & Rick Ruback"
 },
 {
  "slug": "yudkoff-really-private-equity",
  "guest": "Royce Yudkoff & Rick Ruback",
  "date": "2017-04-18",
  "title": "REALLY Private Equity",
  "q": "Could you give me a sense of the scale of this?",
  "who": "Royce Yudkoff & Rick Ruback"
 },
 {
  "slug": "yudkoff-really-private-equity",
  "guest": "Royce Yudkoff & Rick Ruback",
  "date": "2017-04-18",
  "title": "REALLY Private Equity",
  "q": "Well, I think we can fairly say that we're the largest because the school is the largest.",
  "who": "Royce Yudkoff & Rick Ruback"
 },
 {
  "slug": "zweig-the-power-of-serendipity",
  "guest": "Jason Zweig",
  "date": "2016-09-27",
  "title": "The Power of Serendipity",
  "q": "You just seemed like the kind of person I should take a chance on.",
  "who": "Jason's early hiring manager"
 },
 {
  "slug": "zweig-the-power-of-serendipity",
  "guest": "Jason Zweig",
  "date": "2016-09-27",
  "title": "The Power of Serendipity",
  "q": "Good financial advisor is worth platinum. Portfolio management is commodity; financial planning is priceless.",
  "who": "Jason Zweig"
 },
 {
  "slug": "zweig-the-power-of-serendipity",
  "guest": "Jason Zweig",
  "date": "2016-09-27",
  "title": "The Power of Serendipity",
  "q": "Serendipity is something you can influence, you can shape. Luck happens to you.",
  "who": "Jason Zweig"
 },
 {
  "slug": "zweig-the-power-of-serendipity",
  "guest": "Jason Zweig",
  "date": "2016-09-27",
  "title": "The Power of Serendipity",
  "q": "Essay means attempt—bounded in expectations. You're making an attempt to make sense of the world, not solve universe.",
  "who": "Jason Zweig (on Montaigne)"
 }
];
