// AUTO-GENERATED by gen_dashboard_data.py - do not edit
/* eslint-disable */
export const STATS: any = {"totalEpisodes": 476, "totalHours": 576, "totalWords": 5726932, "uniqueGuests": 436, "repeatGuests": 58, "companies": 1661, "themes": 14, "lessons": 805, "firstDate": "2016-09-11", "lastDate": "2026-07-14", "medianMins": 71, "firstYearMed": 66, "lastYearMed": 71, "aiFirst": 7, "aiLast": 38, "topGuestType": "Founder / Operator", "firstYear": 2016, "lastYear": 2026};
