// AUTO-GENERATED by gen_dashboard_data.py — do not edit
/* eslint-disable */
export const STATS: any = {
 "totalEpisodes": 476,
 "totalHours": 526,
 "totalWords": 5726932,
 "uniqueGuests": 378,
 "repeatGuests": 32,
 "firstDate": "2016-09-11",
 "lastDate": "2026-07-14",
 "analyzedCount": 45
};
